#!/bin/sh

name="testing-receiver"

case $1 in
    start|boot)
        [ ! -f /usr/bin/${name} ] && ln -s /usr/bin/amxrt /usr/bin/${name}
        $name -D
        ;;
    stop|shutdown)
        if [ -f /var/run/${name}.pid ]; then
            kill $(cat /var/run/${name}.pid)
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage : $0 [start|boot|stop]"
        ;;
esac
