##################################################################################
#                                                                                #
#       Copyright © 2020 MaxLinear, Inc.                                         #
#                                                                                #
#  For licensing information, see the file 'LICENSE' in the root folder of       #
#  this software module.                                                         #
##################################################################################

obj-$(CONFIG_DSL_DFE_LOOPBACK) += dsl_dfe_loopback.o

