#!/bin/sh /etc/rc.common

. /lib/functions/system.sh

START=19

FIRMWARE_IMAGES_DIR="/opt/intel/wave/images"
KENRELO_BJECTS_DIR="/opt/intel/lib/modules/4.9.184/net/"

start() {
    echo "MaxLinear WIFI START" > /dev/console
    echo "MaxLinear WIFI START - createConfig" > /dev/console

    cp -f /lib/netifd/swpal-netifd-wireless.sh /lib/netifd/netifd-wireless.sh

    # start purple wireless hardware manager service(pwhm) only
    # if mxl vendor module is compiled and loaded
    if [ ! -e "/usr/lib/amx/wld/modules/mod-whm-mxl.so" ]; then
	rm /etc/rc.d/S60prplmesh_whm
    else
    # if pwhm is managing Wireless move wireless configuration
    # file since netifd is not functional and this configuration
    # file is not used.
	if [ -e "/etc/config/wireless" ]; then
		for i in $(uci -q show wireless | grep wifi-device | cut -d '=' -f1 | cut -d '.' -f2); do
			uci -q del wireless.$i
		done
		echo "# Wireless is managed by prplMesh Wireless Hardware Manager" >> /etc/config/wireless
		echo "# this is Backup of previous configuration that was available at /etc/config/wireless" >> /etc/config/wireless
		mv /etc/config/wireless /etc/config/netifd.wireless.backup
	fi
    fi

#    # pull call data from mtd and extract it
#    CAL_MTD=$(cat /proc/mtd | grep calibration | cut -d: -f1)
#    gunzip /dev/${CAL_MTD} -c | gzip > /tmp/eeprom.tar.gz
#    tar xvfz /tmp/eeprom.tar.gz -C /tmp
#    tar xvfz /tmp/wlanconfig.gz -C /tmp
#    cp /tmp/cal_wlan* /lib/firmware/

#    for filename in $FIRMWARE_IMAGES_DIR/*; do
#        if [ ! -L /lib/firmware/$(basename $filename) ]; then
#            cp -rs $filename /lib/firmware/
#        fi
#    done

    for filename in $KENRELO_BJECTS_DIR/mtlk*; do
        if [ ! -L /lib/modules/$(uname -r)/$(basename $filename) ]; then
            cp -rs $filename /lib/modules/$(uname -r)/
        fi
    done

    if [ !  -f "/etc/config/wireless" ]; then
        /sbin/wifi config
        /usr/local/sbin/wireless_def_config
    fi
	
}

stop() {
    echo "MaxLinear WIFI STOP" > /dev/console

}
