#!/bin/sh

VENDOR_PATH="/opt/intel"
csdconfigfile=$VENDOR_PATH"/csd/config/.config_upgrade"
config_update_reset()
{
	if [ -f $csdconfigfile ]; then
		cp -rf /rom/etc/config/* /etc/config/
		chown -R rpcd:rpcd /etc/config/*
		chmod -R 640 /etc/config/*
		sed -i '/objcrc/d' $VENDOR_PATH/servd/etc/servd.conf
		rm -f $VENDOR_PATH/etc/nextmac.conf
		rm -rf $csdconfigfile
	fi
}

boot_hook_add preinit_main config_update_reset
