#!/bin/sh

update_ipsec_link()
{
	ln -sf /tmp/ipsec/ipsec.conf /etc/ipsec.conf
	ln -sf /tmp/ipsec/strongswan.conf /etc/strongswan.conf
	ln -sf /tmp/ipsec/ipsec.secrets /etc/ipsec.secrets
}

boot_hook_add preinit_main update_ipsec_link
