/******************************************************************************

                         Copyright (c) 2012, 2014, 2015
                        Lantiq Beteiligungs-GmbH & Co. KG

  For licensing information, see the file 'LICENSE' in the root folder of
  this software module.

******************************************************************************/

#define QCLI_MAX_STR 1024
typedef enum {
	CLI_ACTION_MARK = 1,
	CLI_ACTION_DROP, 
	CLI_ACTION_DSCP,
	CLI_ACTION_VLAN,
	CLI_ACTION_POLICER,
	CLI_ACTION_POLICYRT,
	CLI_ACTION_ACCL,
	CLI_ACTION_FRAG
}classcfg_cli_actions;

typedef enum {
	CLI_TCP_ACK = 1,
	CLI_TCP_SYN,
	CLI_TCP_FIN, 
	CLI_TCP_RST, 
	CLI_TCP_URG
}classcfg_cli_tcp_flags;

typedef enum {
	CLI_PROTO_ICMP = 1,
	CLI_PROTO_TCP,
	CLI_PROTO_UDP,
	CLI_PROTO_ALL,
}classcfg_cli_protocol;

typedef enum {
	CLI_DHCP_EXACT  = 1,
	CLI_DHCP_PREFIX,
	CLI_DHCP_SUFFIX,
	CLI_DHCP_SUBSTR
}classcfg_cli_dhcp_mode;

typedef enum {
	CLI_MATCH_APP  = 1,
	CLI_MATCH_L7,
	CLI_MATCH_DHCP,
}classcfg_cli_mapp_type;

typedef enum {
	CLI_APP_APP1  = 1,
	CLI_APP_APP2,
}classcfg_cli_app_num;


int32_t classcfg_main(int32_t,char**);
typedef enum {
  CLI_CLSCFG_PARAM_VENDOR=0,
  CLI_CLSCFG_PARAM_MODE ,
  CLI_CLSCFG_PARAM_V6VENDOR,
  CLI_CLSCFG_PARAM_CLIENT,
  CLI_CLSCFG_PARAM_CLASS,
  CLI_CLSCFG_PARAM_VINFO,
  CLI_CLSCFG_PARAM_SMAC,
  CLI_CLSCFG_PARAM_DMAC,
  CLI_CLSCFG_PARAM_802_3_SSAP,
  CLI_CLSCFG_PARAM_802_3_DSAP,  
  CLI_CLSCFG_PARAM_VLAN_ID_INNER,
  CLI_CLSCFG_PARAM_VLAN_ID_OUTER,
  CLI_CLSCFG_PARAM_VLAN_PRIO_INNER,
  CLI_CLSCFG_PARAM_VLAN_PRIO_OUTER,
  CLI_CLSCFG_PARAM_VLAN_DEI_INNER,
  CLI_CLSCFG_PARAM_VLAN_DEI_OUTER, 
  CLI_CLSCFG_PARAM_LLC,
  CLI_CLSCFG_PARAM_SNAPOUI,  
  CLI_CLSCFG_PARAM_POLICER, 
  CLI_CLSCFG_PARAM_CR,
  CLI_CLSCFG_PARAM_CBS,
  CLI_CLSCFG_PARAM_PR,
  CLI_CLSCFG_PARAM_PBS,
  CLI_CLSCFG_PARAM_EBS,
  CLI_CLSCFG_PARAM_ACTDROP,
  CLI_CLSCFG_PARAM_ACTDSCP,
  CLI_CLSCFG_PARAM_ACTETHPRIO,
  CLI_CLSCFG_PARAM_MARK,
  CLI_CLSCFG_PARAM_MARK_ING,
  CLI_CLSCFG_PARAM_MARK_PRIORITY,
  CLI_CLSCFG_PARAM_MARK_LOC,
  CLI_CLSCFG_PARAM_ACCL,
  CLI_CLSCFG_PARAM_FRAG,
  CLI_CLSCFG_PARAM_VID_INNER,
  CLI_CLSCFG_PARAM_VID_OUTER,
  CLI_CLSCFG_PARAM_PCP_INNER,
  CLI_CLSCFG_PARAM_PCP_OUTER, 
  CLI_CLSCFG_PARAM_POLICYRT,  
  CLI_CLSCFG_PARAM_GW,  
  CLI_CLSCFG_PARAM_IFACE,
  CLI_CLSCFG_PARAM_METRIC,  
  CLI_CLSCFG_PARAM_APP_NAME, 
  CLI_CLSCFG_PARAM_L7_PROTO_NAME, 
  CLI_CLSCFG_PARAM_SUBPROTO_NAME,
  CLI_CLSCFG_PARAM_SRC_IP_INNER,
  CLI_CLSCFG_PARAM_DST_IP_INNER,
  CLI_CLSCFG_PARAM_ETH_TYPE,
  CLI_CLSCFG_PARAM_IP_HDR_LEN_MIN,
  CLI_CLSCFG_PARAM_IP_HDR_LEN_MAX,
  CLI_CLSCFG_PARAM_IP_HDR_DSCP,
  CLI_CLSCFG_PARAM_ENGINE
}x_classcfg_param_list;

