/* attention, this file was automatically generated by swig and Perl scripts */
#include "dsl_fapi_cli.h"
#include "ifx_types.h"
#include "ifxos_common.h"
#include "ifxos_print.h"

#ifdef INCLUDE_CLI_SUPPORT

#define EMPTY " "
#include "lib_cli_config.h"
#include "lib_cli_core.h"

#define FAPI_DSL_CRLF IFXOS_CRLF

/** \addtogroup FAPI_DSL_CLI_COMMANDS
   @{
*/

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_get" FAPI_DSL_CRLF
		"Short Form: lg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- bool enable \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char status[16]" FAPI_DSL_CRLF
		"- bool upstream \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char firmware_version[64]" FAPI_DSL_CRLF
		"- char link_status[20]" FAPI_DSL_CRLF
		"- char standards_supported[512]" FAPI_DSL_CRLF
		"- unsigned char xtse[8]" FAPI_DSL_CRLF
		"- char standard_used[20]" FAPI_DSL_CRLF
		"- unsigned char xtse_used[8]" FAPI_DSL_CRLF
		"- char line_encoding[5]" FAPI_DSL_CRLF
		"- char allowed_profiles[40]" FAPI_DSL_CRLF
		"- char current_profile[5]" FAPI_DSL_CRLF
		"- char power_management_state[4]" FAPI_DSL_CRLF
		"- unsigned int success_failure_cause" FAPI_DSL_CRLF
		"- unsigned int last_state_transmitted_downstream" FAPI_DSL_CRLF
		"- unsigned int last_state_transmitted_upstream" FAPI_DSL_CRLF
		"- unsigned int us0_mask" FAPI_DSL_CRLF
		"- int trellis_ds" FAPI_DSL_CRLF
		"- int trellis_us" FAPI_DSL_CRLF
		"- unsigned int act_snr_mode_ds" FAPI_DSL_CRLF
		"- unsigned int act_snr_mode_us" FAPI_DSL_CRLF
		"- int line_number" FAPI_DSL_CRLF
		"- unsigned int upstream_max_bit_rate" FAPI_DSL_CRLF
		"- unsigned int downstream_max_bit_rate" FAPI_DSL_CRLF
		"- int upstream_noise_margin" FAPI_DSL_CRLF
		"- int downstream_noise_margin" FAPI_DSL_CRLF
		"- char snr_mpb_us[256]" FAPI_DSL_CRLF
		"- char snr_mpb_ds[256]" FAPI_DSL_CRLF
		"- int upstream_power" FAPI_DSL_CRLF
		"- int downstream_power" FAPI_DSL_CRLF
		"- unsigned char xtur_vendor[4]" FAPI_DSL_CRLF
		"- unsigned char xtur_country[2]" FAPI_DSL_CRLF
		"- unsigned int xtur_ansi_std" FAPI_DSL_CRLF
		"- unsigned int xtur_ansi_rev" FAPI_DSL_CRLF
		"- unsigned int xtuc_vendor[4]" FAPI_DSL_CRLF
		"- unsigned short xtuc_country[2]" FAPI_DSL_CRLF
		"- unsigned int xtuc_ansi_std" FAPI_DSL_CRLF
		"- unsigned int xtuc_ansi_rev" FAPI_DSL_CRLF
		"- char upbokler_pb[26]" FAPI_DSL_CRLF
		"- char rxthrsh_ds[26]" FAPI_DSL_CRLF
		"- unsigned int act_ra_mode_ds" FAPI_DSL_CRLF
		"- unsigned int act_ra_mode_us" FAPI_DSL_CRLF
		"- unsigned int snr_mroc_us" FAPI_DSL_CRLF
		"- int upstream_attenuation" FAPI_DSL_CRLF
		"- int downstream_attenuation" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d enable=%u status=\"%s\" upstream=%u firmware_version=\"%s\" link_status=\"%s\" standards_supported=\"%s\" xtse=\"%x %x %x %x %x %x %x %x\" standard_used=\"%s\" xtse_used=\"%x %x %x %x %x %x %x %x\" line_encoding=\"%s\" allowed_profiles=\"%s\" current_profile=\"%s\" power_management_state=\"%s\" success_failure_cause=%u last_state_transmitted_downstream=%u last_state_transmitted_upstream=%u us0_mask=%u trellis_ds=%d trellis_us=%d act_snr_mode_ds=%u act_snr_mode_us=%u line_number=%d upstream_max_bit_rate=%u downstream_max_bit_rate=%u upstream_noise_margin=%d downstream_noise_margin=%d snr_mpb_us=\"%s\" snr_mpb_ds=\"%s\" upstream_power=%d downstream_power=%d xtur_vendor=\"%x %x %x %x\" xtur_country=\"%x %x\" xtur_ansi_std=%u xtur_ansi_rev=%u xtuc_vendor=\"%u %u %u %u\" xtuc_country=\"%hu %hu\" xtuc_ansi_std=%u xtuc_ansi_rev=%u upbokler_pb=\"%s\" rxthrsh_ds=\"%s\" act_ra_mode_ds=%u act_ra_mode_us=%u snr_mroc_us=%u upstream_attenuation=%d downstream_attenuation=%d " FAPI_DSL_CRLF,
		(int)fct_ret, obj.enable, obj.status, obj.upstream,
		obj.firmware_version, obj.link_status,
		obj.standards_supported, obj.xtse[0], obj.xtse[1],
		obj.xtse[2], obj.xtse[3], obj.xtse[4], obj.xtse[5],
		obj.xtse[6], obj.xtse[7], obj.standard_used, obj.xtse_used[0],
		obj.xtse_used[1], obj.xtse_used[2], obj.xtse_used[3],
		obj.xtse_used[4], obj.xtse_used[5], obj.xtse_used[6],
		obj.xtse_used[7], obj.line_encoding, obj.allowed_profiles,
		obj.current_profile, obj.power_management_state,
		obj.success_failure_cause,
		obj.last_state_transmitted_downstream,
		obj.last_state_transmitted_upstream, obj.us0_mask,
		obj.trellis_ds, obj.trellis_us, obj.act_snr_mode_ds,
		obj.act_snr_mode_us, obj.line_number,
		obj.upstream_max_bit_rate, obj.downstream_max_bit_rate,
		obj.upstream_noise_margin, obj.downstream_noise_margin,
		obj.snr_mpb_us, obj.snr_mpb_ds, obj.upstream_power,
		obj.downstream_power, obj.xtur_vendor[0], obj.xtur_vendor[1],
		obj.xtur_vendor[2], obj.xtur_vendor[3], obj.xtur_country[0],
		obj.xtur_country[1], obj.xtur_ansi_std, obj.xtur_ansi_rev,
		obj.xtuc_vendor[0], obj.xtuc_vendor[1], obj.xtuc_vendor[2],
		obj.xtuc_vendor[3], obj.xtuc_country[0], obj.xtuc_country[1],
		obj.xtuc_ansi_std, obj.xtuc_ansi_rev, obj.upbokler_pb,
		obj.rxthrsh_ds, obj.act_ra_mode_ds, obj.act_ra_mode_us,
		obj.snr_mroc_us, obj.upstream_attenuation,
		obj.downstream_attenuation);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_set" FAPI_DSL_CRLF
		"Short Form: ls" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- bool enable \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char status[16]" FAPI_DSL_CRLF
		"- bool upstream \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char firmware_version[64]" FAPI_DSL_CRLF
		"- char link_status[20]" FAPI_DSL_CRLF
		"- char standards_supported[512]" FAPI_DSL_CRLF
		"- unsigned char xtse[8]" FAPI_DSL_CRLF
		"- char standard_used[20]" FAPI_DSL_CRLF
		"- unsigned char xtse_used[8]" FAPI_DSL_CRLF
		"- char line_encoding[5]" FAPI_DSL_CRLF
		"- char allowed_profiles[40]" FAPI_DSL_CRLF
		"- char current_profile[5]" FAPI_DSL_CRLF
		"- char power_management_state[4]" FAPI_DSL_CRLF
		"- unsigned int success_failure_cause" FAPI_DSL_CRLF
		"- unsigned int last_state_transmitted_downstream" FAPI_DSL_CRLF
		"- unsigned int last_state_transmitted_upstream" FAPI_DSL_CRLF
		"- unsigned int us0_mask" FAPI_DSL_CRLF
		"- int trellis_ds" FAPI_DSL_CRLF
		"- int trellis_us" FAPI_DSL_CRLF
		"- unsigned int act_snr_mode_ds" FAPI_DSL_CRLF
		"- unsigned int act_snr_mode_us" FAPI_DSL_CRLF
		"- int line_number" FAPI_DSL_CRLF
		"- unsigned int upstream_max_bit_rate" FAPI_DSL_CRLF
		"- unsigned int downstream_max_bit_rate" FAPI_DSL_CRLF
		"- int upstream_noise_margin" FAPI_DSL_CRLF
		"- int downstream_noise_margin" FAPI_DSL_CRLF
		"- char snr_mpb_us[256]" FAPI_DSL_CRLF
		"- char snr_mpb_ds[256]" FAPI_DSL_CRLF
		"- int upstream_power" FAPI_DSL_CRLF
		"- int downstream_power" FAPI_DSL_CRLF
		"- unsigned char xtur_vendor[4]" FAPI_DSL_CRLF
		"- unsigned char xtur_country[2]" FAPI_DSL_CRLF
		"- unsigned int xtur_ansi_std" FAPI_DSL_CRLF
		"- unsigned int xtur_ansi_rev" FAPI_DSL_CRLF
		"- unsigned int xtuc_vendor[4]" FAPI_DSL_CRLF
		"- unsigned short xtuc_country[2]" FAPI_DSL_CRLF
		"- unsigned int xtuc_ansi_std" FAPI_DSL_CRLF
		"- unsigned int xtuc_ansi_rev" FAPI_DSL_CRLF
		"- char upbokler_pb[26]" FAPI_DSL_CRLF
		"- char rxthrsh_ds[26]" FAPI_DSL_CRLF
		"- unsigned int act_ra_mode_ds" FAPI_DSL_CRLF
		"- unsigned int act_ra_mode_us" FAPI_DSL_CRLF
		"- unsigned int snr_mroc_us" FAPI_DSL_CRLF
		"- int upstream_attenuation" FAPI_DSL_CRLF
		"- int downstream_attenuation" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd,
		"%bu %s%bu %s%s%s%bx[8] %s%bx[8] %s%s%s%s%u %u %u %u %d %d %u %u %d %u %u %d %d %s%s%d %d %bx[4] %bx[2] %u %u %u[4] %hu[2] %u %u %s%s%u %u %u %d %d",
		&obj.enable, &obj.status, &obj.upstream,
		&obj.firmware_version, &obj.link_status,
		&obj.standards_supported, &obj.xtse[0], &obj.standard_used,
		&obj.xtse_used[0], &obj.line_encoding, &obj.allowed_profiles,
		&obj.current_profile, &obj.power_management_state,
		&obj.success_failure_cause,
		&obj.last_state_transmitted_downstream,
		&obj.last_state_transmitted_upstream, &obj.us0_mask,
		&obj.trellis_ds, &obj.trellis_us, &obj.act_snr_mode_ds,
		&obj.act_snr_mode_us, &obj.line_number,
		&obj.upstream_max_bit_rate, &obj.downstream_max_bit_rate,
		&obj.upstream_noise_margin, &obj.downstream_noise_margin,
		&obj.snr_mpb_us, &obj.snr_mpb_ds, &obj.upstream_power,
		&obj.downstream_power, &obj.xtur_vendor[0],
		&obj.xtur_country[0], &obj.xtur_ansi_std, &obj.xtur_ansi_rev,
		&obj.xtuc_vendor[0], &obj.xtuc_country[0], &obj.xtuc_ansi_std,
		&obj.xtuc_ansi_rev, &obj.upbokler_pb, &obj.rxthrsh_ds,
		&obj.act_ra_mode_ds, &obj.act_ra_mode_us, &obj.snr_mroc_us,
		&obj.upstream_attenuation, &obj.downstream_attenuation);
	if (ret != 67)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_get" FAPI_DSL_CRLF
		"Short Form: lsg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int total_start" FAPI_DSL_CRLF
		"- unsigned int showtime_start" FAPI_DSL_CRLF
		"- unsigned int last_showtime_start" FAPI_DSL_CRLF
		"- unsigned int current_day_start" FAPI_DSL_CRLF
		"- unsigned int quarter_hour_start" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d total_start=%u showtime_start=%u last_showtime_start=%u current_day_start=%u quarter_hour_start=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.total_start, obj.showtime_start,
		obj.last_showtime_start, obj.current_day_start,
		obj.quarter_hour_start);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_set" FAPI_DSL_CRLF
		"Short Form: lss" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int total_start" FAPI_DSL_CRLF
		"- unsigned int showtime_start" FAPI_DSL_CRLF
		"- unsigned int last_showtime_start" FAPI_DSL_CRLF
		"- unsigned int current_day_start" FAPI_DSL_CRLF
		"- unsigned int quarter_hour_start" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u",
		&obj.total_start, &obj.showtime_start,
		&obj.last_showtime_start, &obj.current_day_start,
		&obj.quarter_hour_start);
	if (ret != 5)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_total_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_total_get" FAPI_DSL_CRLF
		"Short Form: lstg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_total_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d errored_secs=%u severely_errored_secs=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.errored_secs, obj.severely_errored_secs);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_total_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_total_set" FAPI_DSL_CRLF
		"Short Form: lsts" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u",
		&obj.errored_secs, &obj.severely_errored_secs);
	if (ret != 2)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_total_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_showtime_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_showtime_get" FAPI_DSL_CRLF
		"Short Form: lssg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_showtime_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d errored_secs=%u severely_errored_secs=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.errored_secs, obj.severely_errored_secs);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_showtime_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_showtime_set" FAPI_DSL_CRLF
		"Short Form: lsss" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u",
		&obj.errored_secs, &obj.severely_errored_secs);
	if (ret != 2)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_showtime_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_last_showtime_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_last_showtime_get" FAPI_DSL_CRLF
		"Short Form: lslsg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_last_showtime_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d errored_secs=%u severely_errored_secs=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.errored_secs, obj.severely_errored_secs);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_last_showtime_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_last_showtime_set" FAPI_DSL_CRLF
		"Short Form: lslss" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u",
		&obj.errored_secs, &obj.severely_errored_secs);
	if (ret != 2)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_last_showtime_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_current_day_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_current_day_get" FAPI_DSL_CRLF
		"Short Form: lscdg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_current_day_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d errored_secs=%u severely_errored_secs=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.errored_secs, obj.severely_errored_secs);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_current_day_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_current_day_set" FAPI_DSL_CRLF
		"Short Form: lscds" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u",
		&obj.errored_secs, &obj.severely_errored_secs);
	if (ret != 2)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_current_day_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_quarter_hour_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_quarter_hour_get" FAPI_DSL_CRLF
		"Short Form: lsqhg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_stats_quarter_hour_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d errored_secs=%u severely_errored_secs=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.errored_secs, obj.severely_errored_secs);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_stats_quarter_hour_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_stats_quarter_hour_set" FAPI_DSL_CRLF
		"Short Form: lsqhs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int errored_secs" FAPI_DSL_CRLF
		"- unsigned int severely_errored_secs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u",
		&obj.errored_secs, &obj.severely_errored_secs);
	if (ret != 2)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_stats_quarter_hour_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_test_params_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_test_params_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_test_params_get" FAPI_DSL_CRLF
		"Short Form: ltpg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int hlogg_ds" FAPI_DSL_CRLF
		"- unsigned int hlogg_us" FAPI_DSL_CRLF
		"- char hlogps_ds[2562]" FAPI_DSL_CRLF
		"- char hlogps_us[2562]" FAPI_DSL_CRLF
		"- unsigned int hlogmt_ds" FAPI_DSL_CRLF
		"- unsigned int hlogmt_us" FAPI_DSL_CRLF
		"- unsigned int qlng_ds" FAPI_DSL_CRLF
		"- unsigned int qlng_us" FAPI_DSL_CRLF
		"- char qlnps_ds[2049]" FAPI_DSL_CRLF
		"- char qlnps_us[2049]" FAPI_DSL_CRLF
		"- unsigned int qlnmt_ds" FAPI_DSL_CRLF
		"- unsigned int qlnmt_us" FAPI_DSL_CRLF
		"- unsigned int snrg_ds" FAPI_DSL_CRLF
		"- unsigned int snrg_us" FAPI_DSL_CRLF
		"- char snrps_ds[2049]" FAPI_DSL_CRLF
		"- char snrps_us[2049]" FAPI_DSL_CRLF
		"- unsigned int snrmt_ds" FAPI_DSL_CRLF
		"- unsigned int snrmt_us" FAPI_DSL_CRLF
		"- char latn_ds[24]" FAPI_DSL_CRLF
		"- char latn_us[24]" FAPI_DSL_CRLF
		"- char satn_ds[24]" FAPI_DSL_CRLF
		"- char satn_us[24]" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_line_test_params_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d hlogg_ds=%u hlogg_us=%u hlogps_ds=\"%s\" hlogps_us=\"%s\" hlogmt_ds=%u hlogmt_us=%u qlng_ds=%u qlng_us=%u qlnps_ds=\"%s\" qlnps_us=\"%s\" qlnmt_ds=%u qlnmt_us=%u snrg_ds=%u snrg_us=%u snrps_ds=\"%s\" snrps_us=\"%s\" snrmt_ds=%u snrmt_us=%u latn_ds=\"%s\" latn_us=\"%s\" satn_ds=\"%s\" satn_us=\"%s\" " FAPI_DSL_CRLF,
		(int)fct_ret, obj.hlogg_ds, obj.hlogg_us, obj.hlogps_ds,
		obj.hlogps_us, obj.hlogmt_ds, obj.hlogmt_us, obj.qlng_ds,
		obj.qlng_us, obj.qlnps_ds, obj.qlnps_us, obj.qlnmt_ds,
		obj.qlnmt_us, obj.snrg_ds, obj.snrg_us, obj.snrps_ds,
		obj.snrps_us, obj.snrmt_ds, obj.snrmt_us, obj.latn_ds,
		obj.latn_us, obj.satn_ds, obj.satn_us);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_line_test_params_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_line_test_params_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: line_test_params_set" FAPI_DSL_CRLF
		"Short Form: ltps" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int hlogg_ds" FAPI_DSL_CRLF
		"- unsigned int hlogg_us" FAPI_DSL_CRLF
		"- char hlogps_ds[2562]" FAPI_DSL_CRLF
		"- char hlogps_us[2562]" FAPI_DSL_CRLF
		"- unsigned int hlogmt_ds" FAPI_DSL_CRLF
		"- unsigned int hlogmt_us" FAPI_DSL_CRLF
		"- unsigned int qlng_ds" FAPI_DSL_CRLF
		"- unsigned int qlng_us" FAPI_DSL_CRLF
		"- char qlnps_ds[2049]" FAPI_DSL_CRLF
		"- char qlnps_us[2049]" FAPI_DSL_CRLF
		"- unsigned int qlnmt_ds" FAPI_DSL_CRLF
		"- unsigned int qlnmt_us" FAPI_DSL_CRLF
		"- unsigned int snrg_ds" FAPI_DSL_CRLF
		"- unsigned int snrg_us" FAPI_DSL_CRLF
		"- char snrps_ds[2049]" FAPI_DSL_CRLF
		"- char snrps_us[2049]" FAPI_DSL_CRLF
		"- unsigned int snrmt_ds" FAPI_DSL_CRLF
		"- unsigned int snrmt_us" FAPI_DSL_CRLF
		"- char latn_ds[24]" FAPI_DSL_CRLF
		"- char latn_us[24]" FAPI_DSL_CRLF
		"- char satn_ds[24]" FAPI_DSL_CRLF
		"- char satn_us[24]" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd,
		"%u %u %s%s%u %u %u %u %s%s%u %u %u %u %s%s%u %u %s%s%s%s",
		&obj.hlogg_ds, &obj.hlogg_us, &obj.hlogps_ds, &obj.hlogps_us,
		&obj.hlogmt_ds, &obj.hlogmt_us, &obj.qlng_ds, &obj.qlng_us,
		&obj.qlnps_ds, &obj.qlnps_us, &obj.qlnmt_ds, &obj.qlnmt_us,
		&obj.snrg_ds, &obj.snrg_us, &obj.snrps_ds, &obj.snrps_us,
		&obj.snrmt_ds, &obj.snrmt_us, &obj.latn_ds, &obj.latn_us,
		&obj.satn_ds, &obj.satn_us);
	if (ret != 22)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_line_test_params_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_get" FAPI_DSL_CRLF
		"Short Form: cg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- bool enable \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char status[16]" FAPI_DSL_CRLF
		"- char link_encapsulation_supported[82]" FAPI_DSL_CRLF
		"- char link_encapsulation_used[40]" FAPI_DSL_CRLF
		"- unsigned int lpath" FAPI_DSL_CRLF
		"- unsigned int intlvdepth" FAPI_DSL_CRLF
		"- int intlvblock" FAPI_DSL_CRLF
		"- unsigned int actual_interleaving_delay" FAPI_DSL_CRLF
		"- int actinp" FAPI_DSL_CRLF
		"- bool inpreport \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- int nfec" FAPI_DSL_CRLF
		"- int rfec" FAPI_DSL_CRLF
		"- int lsymb" FAPI_DSL_CRLF
		"- unsigned int upstream_curr_rate" FAPI_DSL_CRLF
		"- unsigned int downstream_curr_rate" FAPI_DSL_CRLF
		"- unsigned int actndr" FAPI_DSL_CRLF
		"- unsigned int actndr_ds" FAPI_DSL_CRLF
		"- unsigned int actndr_us" FAPI_DSL_CRLF
		"- unsigned int actinprein" FAPI_DSL_CRLF
		"- unsigned int actinprein_ds" FAPI_DSL_CRLF
		"- unsigned int actinprein_us" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d enable=%u status=\"%s\" link_encapsulation_supported=\"%s\" link_encapsulation_used=\"%s\" lpath=%u intlvdepth=%u intlvblock=%d actual_interleaving_delay=%u actinp=%d inpreport=%u nfec=%d rfec=%d lsymb=%d upstream_curr_rate=%u downstream_curr_rate=%u actndr=%u actndr_ds=%u actndr_us=%u actinprein=%u actinprein_ds=%u actinprein_us=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.enable, obj.status,
		obj.link_encapsulation_supported, obj.link_encapsulation_used,
		obj.lpath, obj.intlvdepth, obj.intlvblock,
		obj.actual_interleaving_delay, obj.actinp, obj.inpreport,
		obj.nfec, obj.rfec, obj.lsymb, obj.upstream_curr_rate,
		obj.downstream_curr_rate, obj.actndr, obj.actndr_ds,
		obj.actndr_us, obj.actinprein, obj.actinprein_ds,
		obj.actinprein_us);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_set" FAPI_DSL_CRLF
		"Short Form: cs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- bool enable \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char status[16]" FAPI_DSL_CRLF
		"- char link_encapsulation_supported[82]" FAPI_DSL_CRLF
		"- char link_encapsulation_used[40]" FAPI_DSL_CRLF
		"- unsigned int lpath" FAPI_DSL_CRLF
		"- unsigned int intlvdepth" FAPI_DSL_CRLF
		"- int intlvblock" FAPI_DSL_CRLF
		"- unsigned int actual_interleaving_delay" FAPI_DSL_CRLF
		"- int actinp" FAPI_DSL_CRLF
		"- bool inpreport \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- int nfec" FAPI_DSL_CRLF
		"- int rfec" FAPI_DSL_CRLF
		"- int lsymb" FAPI_DSL_CRLF
		"- unsigned int upstream_curr_rate" FAPI_DSL_CRLF
		"- unsigned int downstream_curr_rate" FAPI_DSL_CRLF
		"- unsigned int actndr" FAPI_DSL_CRLF
		"- unsigned int actndr_ds" FAPI_DSL_CRLF
		"- unsigned int actndr_us" FAPI_DSL_CRLF
		"- unsigned int actinprein" FAPI_DSL_CRLF
		"- unsigned int actinprein_ds" FAPI_DSL_CRLF
		"- unsigned int actinprein_us" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd,
		"%bu %s%s%s%u %u %d %u %d %bu %d %d %d %u %u %u %u %u %u %u %u",
		&obj.enable, &obj.status, &obj.link_encapsulation_supported,
		&obj.link_encapsulation_used, &obj.lpath, &obj.intlvdepth,
		&obj.intlvblock, &obj.actual_interleaving_delay, &obj.actinp,
		&obj.inpreport, &obj.nfec, &obj.rfec, &obj.lsymb,
		&obj.upstream_curr_rate, &obj.downstream_curr_rate,
		&obj.actndr, &obj.actndr_ds, &obj.actndr_us, &obj.actinprein,
		&obj.actinprein_ds, &obj.actinprein_us);
	if (ret != 21)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_get" FAPI_DSL_CRLF
		"Short Form: csg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int total_start" FAPI_DSL_CRLF
		"- unsigned int showtime_start" FAPI_DSL_CRLF
		"- unsigned int last_showtime_start" FAPI_DSL_CRLF
		"- unsigned int current_day_start" FAPI_DSL_CRLF
		"- unsigned int quarter_hour_start" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d total_start=%u showtime_start=%u last_showtime_start=%u current_day_start=%u quarter_hour_start=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.total_start, obj.showtime_start,
		obj.last_showtime_start, obj.current_day_start,
		obj.quarter_hour_start);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_set" FAPI_DSL_CRLF
		"Short Form: css" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int total_start" FAPI_DSL_CRLF
		"- unsigned int showtime_start" FAPI_DSL_CRLF
		"- unsigned int last_showtime_start" FAPI_DSL_CRLF
		"- unsigned int current_day_start" FAPI_DSL_CRLF
		"- unsigned int quarter_hour_start" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u",
		&obj.total_start, &obj.showtime_start,
		&obj.last_showtime_start, &obj.current_day_start,
		&obj.quarter_hour_start);
	if (ret != 5)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_total_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_total_get" FAPI_DSL_CRLF
		"Short Form: cstg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_total_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d xtu_rfec_errors=%u xtu_cfec_errors=%u xtu_rhec_errors=%u xtu_chec_errors=%u xtu_rcrc_errors=%u xtu_ccrc_errors=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.xtu_rfec_errors, obj.xtu_cfec_errors,
		obj.xtu_rhec_errors, obj.xtu_chec_errors, obj.xtu_rcrc_errors,
		obj.xtu_ccrc_errors);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_total_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_total_set" FAPI_DSL_CRLF
		"Short Form: csts" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u %u",
		&obj.xtu_rfec_errors, &obj.xtu_cfec_errors,
		&obj.xtu_rhec_errors, &obj.xtu_chec_errors,
		&obj.xtu_rcrc_errors, &obj.xtu_ccrc_errors);
	if (ret != 6)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_total_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_showtime_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_showtime_get" FAPI_DSL_CRLF
		"Short Form: cssg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_showtime_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d xtu_rfec_errors=%u xtu_cfec_errors=%u xtu_rhec_errors=%u xtu_chec_errors=%u xtu_rcrc_errors=%u xtu_ccrc_errors=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.xtu_rfec_errors, obj.xtu_cfec_errors,
		obj.xtu_rhec_errors, obj.xtu_chec_errors, obj.xtu_rcrc_errors,
		obj.xtu_ccrc_errors);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_showtime_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_showtime_set" FAPI_DSL_CRLF
		"Short Form: csss" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u %u",
		&obj.xtu_rfec_errors, &obj.xtu_cfec_errors,
		&obj.xtu_rhec_errors, &obj.xtu_chec_errors,
		&obj.xtu_rcrc_errors, &obj.xtu_ccrc_errors);
	if (ret != 6)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_showtime_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_last_showtime_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_last_showtime_get" FAPI_DSL_CRLF
		"Short Form: cslsg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_last_showtime_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d xtu_rfec_errors=%u xtu_cfec_errors=%u xtu_rhec_errors=%u xtu_chec_errors=%u xtu_rcrc_errors=%u xtu_ccrc_errors=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.xtu_rfec_errors, obj.xtu_cfec_errors,
		obj.xtu_rhec_errors, obj.xtu_chec_errors, obj.xtu_rcrc_errors,
		obj.xtu_ccrc_errors);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_last_showtime_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_last_showtime_set" FAPI_DSL_CRLF
		"Short Form: cslss" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u %u",
		&obj.xtu_rfec_errors, &obj.xtu_cfec_errors,
		&obj.xtu_rhec_errors, &obj.xtu_chec_errors,
		&obj.xtu_rcrc_errors, &obj.xtu_ccrc_errors);
	if (ret != 6)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_last_showtime_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_current_day_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_current_day_get" FAPI_DSL_CRLF
		"Short Form: cscdg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_current_day_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d xtu_rfec_errors=%u xtu_cfec_errors=%u xtu_rhec_errors=%u xtu_chec_errors=%u xtu_rcrc_errors=%u xtu_ccrc_errors=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.xtu_rfec_errors, obj.xtu_cfec_errors,
		obj.xtu_rhec_errors, obj.xtu_chec_errors, obj.xtu_rcrc_errors,
		obj.xtu_ccrc_errors);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_current_day_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_current_day_set" FAPI_DSL_CRLF
		"Short Form: cscds" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u %u",
		&obj.xtu_rfec_errors, &obj.xtu_cfec_errors,
		&obj.xtu_rhec_errors, &obj.xtu_chec_errors,
		&obj.xtu_rcrc_errors, &obj.xtu_ccrc_errors);
	if (ret != 6)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_current_day_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_quarter_hour_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_quarter_hour_get" FAPI_DSL_CRLF
		"Short Form: csqhg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_channel_stats_quarter_hour_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d xtu_rfec_errors=%u xtu_cfec_errors=%u xtu_rhec_errors=%u xtu_chec_errors=%u xtu_rcrc_errors=%u xtu_ccrc_errors=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.xtu_rfec_errors, obj.xtu_cfec_errors,
		obj.xtu_rhec_errors, obj.xtu_chec_errors, obj.xtu_rcrc_errors,
		obj.xtu_ccrc_errors);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_channel_stats_quarter_hour_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_channel_stats_interval_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: channel_stats_quarter_hour_set" FAPI_DSL_CRLF
		"Short Form: csqhs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- unsigned int xtu_rfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_cfec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rhec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_chec_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_rcrc_errors" FAPI_DSL_CRLF
		"- unsigned int xtu_ccrc_errors" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd, "%u %u %u %u %u %u",
		&obj.xtu_rfec_errors, &obj.xtu_cfec_errors,
		&obj.xtu_rhec_errors, &obj.xtu_chec_errors,
		&obj.xtu_rcrc_errors, &obj.xtu_ccrc_errors);
	if (ret != 6)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_channel_stats_quarter_hour_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_x_lantiq_com_config_get(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_x_lantiq_com_config_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: x_lantiq_com_config_get" FAPI_DSL_CRLF
		"Short Form: xlccg" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		"- bool bitswap_us_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_us_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_us \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_us_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_us_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool virtual_noise_us \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool virtual_noise_ds \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char vectoring[9]" FAPI_DSL_CRLF
		"- unsigned char xtse[8]" FAPI_DSL_CRLF
		"- char link_encapsulation_config[80]" FAPI_DSL_CRLF
		"- char dsl_next_mode[5]" FAPI_DSL_CRLF
		"- char next_tc_mode[4]" FAPI_DSL_CRLF
		"- char dsl_act_seq[12]" FAPI_DSL_CRLF
		"- char dsl_act_mode[8]" FAPI_DSL_CRLF
		"- bool dsl_remember \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	fct_ret = fapi_dsl_x_lantiq_com_config_get(p_ctx, &obj);
	return IFXOS_FPrintf(p_out,
		"status=%d bitswap_us_v=%u bitswap_us_a=%u bitswap_ds_v=%u bitswap_ds_a=%u retx_us=%u retx_ds_v=%u retx_ds_a=%u sra_us_v=%u sra_us_a=%u sra_ds_v=%u sra_ds_a=%u virtual_noise_us=%u virtual_noise_ds=%u vectoring=\"%s\" xtse=\"%x %x %x %x %x %x %x %x\" link_encapsulation_config=\"%s\" dsl_next_mode=\"%s\" next_tc_mode=\"%s\" dsl_act_seq=\"%s\" dsl_act_mode=\"%s\" dsl_remember=%u " FAPI_DSL_CRLF,
		(int)fct_ret, obj.bitswap_us_v, obj.bitswap_us_a,
		obj.bitswap_ds_v, obj.bitswap_ds_a, obj.retx_us,
		obj.retx_ds_v, obj.retx_ds_a, obj.sra_us_v, obj.sra_us_a,
		obj.sra_ds_v, obj.sra_ds_a, obj.virtual_noise_us,
		obj.virtual_noise_ds, obj.vectoring, obj.xtse[0], obj.xtse[1],
		obj.xtse[2], obj.xtse[3], obj.xtse[4], obj.xtse[5],
		obj.xtse[6], obj.xtse[7], obj.link_encapsulation_config,
		obj.dsl_next_mode, obj.next_tc_mode, obj.dsl_act_seq,
		obj.dsl_act_mode, obj.dsl_remember);
}

/** Handle command

   \param[in] p_ctx     FAPI_DSL context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_fapi_dsl_x_lantiq_com_config_set(
	struct fapi_dsl_ctx *p_ctx,
	const char *p_cmd,
	clios_file_io_t *p_out)
{
	int ret = 0;
	enum fapi_dsl_status fct_ret = (enum fapi_dsl_status)0;
	struct dsl_fapi_x_lantiq_com_config_obj obj;

#ifndef FAPI_DSL_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: x_lantiq_com_config_set" FAPI_DSL_CRLF
		"Short Form: xlccs" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Input Parameter" FAPI_DSL_CRLF
		"- bool bitswap_us_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_us_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool bitswap_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_us \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool retx_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_us_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_us_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_ds_v \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool sra_ds_a \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool virtual_noise_us \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- bool virtual_noise_ds \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		"- char vectoring[9]" FAPI_DSL_CRLF
		"- unsigned char xtse[8]" FAPI_DSL_CRLF
		"- char link_encapsulation_config[80]" FAPI_DSL_CRLF
		"- char dsl_next_mode[5]" FAPI_DSL_CRLF
		"- char next_tc_mode[4]" FAPI_DSL_CRLF
		"- char dsl_act_seq[12]" FAPI_DSL_CRLF
		"- char dsl_act_mode[8]" FAPI_DSL_CRLF
		"- bool dsl_remember \n   false = 0\n   true = 1" FAPI_DSL_CRLF
		FAPI_DSL_CRLF
		"Output Parameter" FAPI_DSL_CRLF
		"- enum fapi_dsl_status status" FAPI_DSL_CRLF
		FAPI_DSL_CRLF;
#else
#undef usage
#define usage ""
#endif

	ret = cli_check_help__file(p_cmd, usage, p_out);
	if (ret != 0)
		return ret;
	ret = cli_sscanf(p_cmd,
		"%bu %bu %bu %bu %bu %bu %bu %bu %bu %bu %bu %bu %bu %s%bx[8] %s%s%s%s%s%bu",
		&obj.bitswap_us_v, &obj.bitswap_us_a, &obj.bitswap_ds_v,
		&obj.bitswap_ds_a, &obj.retx_us, &obj.retx_ds_v,
		&obj.retx_ds_a, &obj.sra_us_v, &obj.sra_us_a, &obj.sra_ds_v,
		&obj.sra_ds_a, &obj.virtual_noise_us, &obj.virtual_noise_ds,
		&obj.vectoring, &obj.xtse[0], &obj.link_encapsulation_config,
		&obj.dsl_next_mode, &obj.next_tc_mode, &obj.dsl_act_seq,
		&obj.dsl_act_mode, &obj.dsl_remember);
	if (ret != 28)
		return cli_check_help__file("-h", usage, p_out);
	fct_ret = fapi_dsl_x_lantiq_com_config_set(p_ctx, &obj);
	return IFXOS_FPrintf(p_out, "status=%d " FAPI_DSL_CRLF,
		(int)fct_ret);
}

/** Register autogenerated commands */
int dsl_fapi_cli_autogen_commands_register(struct cli_core_context_s *p_core_ctx)
{
unsigned int group_mask = 0;
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lg", "line_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ls", "line_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lsg",
	"line_stats_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lss",
	"line_stats_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lstg",
	"line_stats_total_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_total_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lsts",
	"line_stats_total_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_total_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lssg",
	"line_stats_showtime_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_showtime_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lsss",
	"line_stats_showtime_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_showtime_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lslsg",
	"line_stats_last_showtime_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_last_showtime_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lslss",
	"line_stats_last_showtime_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_last_showtime_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lscdg",
	"line_stats_current_day_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_current_day_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lscds",
	"line_stats_current_day_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_current_day_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lsqhg",
	"line_stats_quarter_hour_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_quarter_hour_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "lsqhs",
	"line_stats_quarter_hour_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_stats_quarter_hour_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ltpg",
	"line_test_params_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_test_params_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ltps",
	"line_test_params_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_line_test_params_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cg",
	"channel_get", (cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cs",
	"channel_set", (cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "csg",
	"channel_stats_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "css",
	"channel_stats_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cstg",
	"channel_stats_total_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_total_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "csts",
	"channel_stats_total_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_total_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cssg",
	"channel_stats_showtime_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_showtime_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "csss",
	"channel_stats_showtime_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_showtime_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cslsg",
	"channel_stats_last_showtime_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_last_showtime_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cslss",
	"channel_stats_last_showtime_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_last_showtime_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cscdg",
	"channel_stats_current_day_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_current_day_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cscds",
	"channel_stats_current_day_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_current_day_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "csqhg",
	"channel_stats_quarter_hour_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_quarter_hour_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "csqhs",
	"channel_stats_quarter_hour_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_channel_stats_quarter_hour_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "xlccg",
	"x_lantiq_com_config_get",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_x_lantiq_com_config_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "xlccs",
	"x_lantiq_com_config_set",
	(cli_cmd_user_fct_file_t)cli_fapi_dsl_x_lantiq_com_config_set);
return IFX_SUCCESS;
}

/*! @} */

#endif
