#!/bin/sh
. /etc/profile.d/intel.sh
. /etc/ugw_notify_defs.sh
. /etc/profile.d/ugw_framework_env.sh 


_help()
{
	echo "Resets system configuration and applications.";
	echo "Default call is to reset only the system configuration."
	echo "Usage: $0 [ options ]";
	echo "Selective factory reset config:-"
	echo "     For now supported -wifi,-qos,-firewall";
	echo "     Example to reset wifi releated config"
	echo "     $0 wifi "
	echo "Supported options:-";
	echo "     factoryreset   Reset all applications";
	exit $1;
}

[ -n "$1" ] && {
	case "$1" in
		-h) _help 0;
		;;
		wifi) WiFi=1;
		;;
		qos) QoS=1;
		;;
		network) network=1;
		;;
		firewall) firewall=1;
		;;
		*) _help 1;
        esac
}

#selective factory reset examples.
[ -n "$WiFi" ] && {
	echo " WiFi releated config getting reset ..."
	rm -rf /overlay/upper/etc/config/wireless
	ubus call csd factoryreset '{ "object":"Device.WiFi."}'
	exit;
}

[ -n "$QoS" ] && {
	echo " QoS releated config getting reset ..."
	rm -rf /overlay/upper/etc/config/qos
	ubus call csd factoryreset '{ "object":"Device.QoS."}'
	exit;
}

[ -n "$firewall" ] && {
	echo " Firewall releated config getting reset ..."
	ubus call servd notify '{"nid":'$NOTIFY_FACTORY_RESET',"type":false}';
	ubus call csd factoryreset '{ "object":"Device.Firewall."}'
	exit;
}

[ -n "$network" ] && {
	## multiple objects to reset example ','
	echo " Network releated config getting reset ..."
	ubus call csd factoryreset '{ "object":"Device.IP.,Device.PPP."}'
	exit;
}

[ -z "$1" ] && {
	rm -rf /overlay/.fs_state
	sync
}

reboot

