#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

base_mac_get() {
	mac_addr=$(awk 'BEGIN{RS=" ";FS="="} $1 == "ethaddr" {print $2}' /proc/cmdline)
	[ -z "$mac_addr" ] && mac_addr='ac:9a:96:00:00:00'
	echo $mac_addr
}

# Generate mac address based on the base_mac
gen_mac() {
        index=${1-0}
        base_addr=$(base_mac_get)
        carry=0
        for offset in 15 12 9 6 3 0; do
                index=$((index - carry + 1))
                octet=$(printf "%02X" $((0x${base_addr:$offset:2} + 0x$index)))
                if [ ${#octet} = 2 ]; then
                        mac_addr="${base_addr:0:$offset}$octet${base_addr:$((offset + 2))}"
                        echo "$mac_addr"
                        return 0
                fi
                carry=$((0x100 - 0x${base_addr:$offset:2}))
        done
}

modify_wifi() {
        interface=$1
        macaddr=$2
        uci batch <<EOF
set wireless.${interface}.macaddr='${macaddr}'
EOF

}

. /lib/functions/uci-defaults.sh
. /lib/functions/lantiq.sh


board=$(lantiq_board_name)

case "$board" in
EASY350*|EASY550*)
        macaddr=`gen_mac 4`
        modify_wifi "radio0" "$macaddr"
        modify_wifi "default_radio100" "$macaddr"
        macaddr=`gen_mac 5`
        modify_wifi "default_radio10" "$macaddr"
        macaddr=`gen_mac 6`
        modify_wifi "default_radio11" "$macaddr"
        macaddr=`gen_mac 7`
        modify_wifi "default_radio12" "$macaddr"
        macaddr=`gen_mac 8`
        modify_wifi "default_radio13" "$macaddr"
        macaddr=`gen_mac 9`
        modify_wifi "default_radio26" "$macaddr"

        macaddr=`gen_mac 10`
        modify_wifi "radio2" "$macaddr"
        modify_wifi "default_radio102" "$macaddr"
        macaddr=`gen_mac 11`
        modify_wifi "default_radio42" "$macaddr"
        macaddr=`gen_mac 12`
        modify_wifi "default_radio43" "$macaddr"
        macaddr=`gen_mac 13`
        modify_wifi "default_radio44" "$macaddr"
        macaddr=`gen_mac 14`
        modify_wifi "default_radio45" "$macaddr"
        macaddr=`gen_mac 15`
        modify_wifi "default_radio58" "$macaddr"
        ;;

esac

uci commit wireless
exit 0
