#!/bin/sh
#

add_container_config() {
uci set lxc-auto.iface_1=network
uci batch << EOF
set lxc-auto.iface_1.type='veth'
set lxc-auto.iface_1.flags='up'
set lxc-auto.iface_1.link='br-lan'
set lxc-auto.iface_1.hwaddr='00:FF:AA:00:00:01'
set lxc-auto.iface_1.name='veth_0'
set lxc-auto.iface_1.mtu='1500'
set lxc-auto.iface_1.ipv4='192.168.1.101'
EOF

local id=$(uci add lxc-auto container)
local arch=$(grep -w "LEDE_ARCH" /etc/os-release | cut -d\" -f2)
if [ "$arch" == "x86_64" ] ; then
	arch="x86_64"
else
	arch="mips"
fi
uci batch << EOF
set lxc-auto.${id}.container_name='openwrt_container'
set lxc-auto.${id}.container_command='down'
set lxc-auto.${id}.container_path='default'
set lxc-auto.${id}.arch='$arch'
set lxc-auto.${id}.rootfs_targz_url='NULL'
set lxc-auto.${id}.container_privilege='unprivileged'
set lxc-auto.${id}.lxcuser='lxcuser'
set lxc-auto.${id}.lxcuser_home='/home/lxcuser/'
set lxc-auto.${id}.uid_rootmap='20000'
set lxc-auto.${id}.uid_range='1000'
set lxc-auto.${id}.gid_rootmap='20000'
set lxc-auto.${id}.gid_range='1000'
set lxc-auto.${id}.kill_timeout='0'
set lxc-auto.${id}.utsname='openwrt'
set lxc-auto.${id}.network_ipv4_gw='192.168.1.1'
add_list lxc-auto.${id}.interfaces='iface_1'
add_list lxc-auto.${id}.mount_auto='proc sys cgroup'
add_list lxc-auto.${id}.mount_auto='proc:rw sys:rw cgroup-full:rw'
add_list lxc-auto.${id}.include_path='/usr/share/lxc/config/openwrt.common.conf'
EOF

local id=$(uci add lxc-auto container)
uci batch << EOF
set lxc-auto.${id}.container_name='buildroot_container'
set lxc-auto.${id}.container_command='down'
set lxc-auto.${id}.container_path='default'
set lxc-auto.${id}.arch='$arch'
set lxc-auto.${id}.rootfs_targz_url='NULL'
set lxc-auto.${id}.container_privilege='unprivileged'
set lxc-auto.${id}.lxcuser='lxcuser' 
set lxc-auto.${id}.lxcuser_home='/home/lxcuser/' 
set lxc-auto.${id}.uid_rootmap='20000'
set lxc-auto.${id}.uid_range='1000'
set lxc-auto.${id}.gid_rootmap='20000'
set lxc-auto.${id}.gid_range='1000'
set lxc-auto.${id}.kill_timeout='0'
set lxc-auto.${id}.utsname='buildroot'
set lxc-auto.${id}.network_ipv4_gw='192.168.1.1'
add_list lxc-auto.${id}.interfaces='iface_1'
add_list lxc-auto.${id}.mount_auto='proc sys cgroup'
add_list lxc-auto.${id}.mount_auto='proc:rw sys:rw cgroup-full:rw'
add_list lxc-auto.${id}.include_path='/usr/share/lxc/config/openwrt.common.conf'
EOF

}


. /lib/functions/uci-defaults.sh

add_container_config

uci commit lxc-auto

exit 0

