#!/bin/sh

[ -d /var/cache/netdata ] || {
	mkdir -m 0755 -p /var/cache/netdata
	chown nobody /var/cache/netdata
}

[ -d /var/lib/netdata ] || {
	mkdir -m 0755 -p /var/lib/netdata
	chown nobody /var/lib/netdata
}

[ -d /var/log/netdata ] || {
	mkdir -m 0755 -p /var/log/netdata
	chown nobody /var/log/netdata
}
