obj-$(CONFIG_PPA)		+= platform/ ppa_api/ qos/ mac_violation_mirror/
obj-$(CONFIG_DSL_DFE_LOOPBACK)	+= dsl_dfe_loopback/
obj-$(CONFIG_LOOP_ETH_DEV)	+= loop_eth_dev/
obj-$(CONFIG_LTQ_PORT_MIRROR)	+= portmirror/
obj-$(CONFIG_PTM_VECTORING)	+= vectoring/
