We cant run test on nec-wx3000hp until LCM-579 is fixed:

  $ [ "$DUT_BOARD" = "nec-wx3000hp" ] && exit 80
  [1]

Create R alias:

  $ alias R="${CRAM_REMOTE_COMMAND:-}"

Check that ubus has expected datamodels available:

  $ R "ubus list | grep '[[:upper:]]' | grep -v '\.[[:digit:]]'"
  ACLManager
  ACLManager.Role
  Bridging
  Bridging.Bridge
  Bridging.Bridge.Port
  Bridging.Bridge.Port.Stats
  Bridging.Bridge.STP
  Bridging.Bridge.VLAN
  Bridging.Bridge.VLANPort
  Buttons
  Buttons.Button
  CaptivePortal
  CaptivePortal.LANInterface
  Cthulhu
  Cthulhu.Config
  Cthulhu.Container
  Cthulhu.Container.Instances
  Cthulhu.Container.Instances.Plugins.NetworkConfig
  Cthulhu.Container.Instances.Plugins.NetworkConfig.AccessInterfaces
  Cthulhu.Container.Instances.Plugins.NetworkConfig.FirewallRules
  Cthulhu.Container.Instances.Plugins.NetworkConfig.PortForwarding
  Cthulhu.Information
  Cthulhu.Plugins
  Cthulhu.Plugins.NetworkConfig
  Cthulhu.Plugins.NetworkConfig.FirewallRules
  Cthulhu.Plugins.NetworkConfig.FirewallRules.Rules
  Cthulhu.Plugins.NetworkConfig.Interfaces
  Cthulhu.Sandbox
  Cthulhu.Sandbox.Instances
  Cthulhu.Sandbox.Instances.Plugins.DHCP
  Cthulhu.Sandbox.Instances.Plugins.DHCP.Interfaces
  DHCPv4Client
  DHCPv4Client.Client
  DHCPv4Server
  DHCPv4Server.Pool
  DHCPv6Client
  DHCPv6Client.Client
  DHCPv6Server
  DHCPv6Server.Pool
  DNS
  DNS.Client
  DNS.Client.Server
  DNS.Relay
  DNS.Relay.Forwarding
  DNS.Relay.X_PRPL-COM_Config
  DNS.X_PRPL-COM_ForwardZone
  DNS.X_PRPL-COM_Host
  DNS.X_PRPL-COM_RebindProtection
  DNS.X_PRPL-COM_RebindProtection.DomainExceptions
  DNS.X_PRPL-COM_RebindProtection.IPExceptions
  DNSSD
  DNSSD.Service
  DSLite
  DSLite.InterfaceSetting
  Device
  Device.Bridging
  Device.Buttons
  Device.CWMPManagementServer
  Device.CaptivePortal
  Device.DHCPv4
  Device.DHCPv4.Server
  Device.DHCPv6
  Device.DHCPv6.Server
  Device.DNS
  Device.DNS.SD
  Device.DSLite
  Device.DeviceInfo
  Device.DynamicDNS
  Device.Ethernet
  Device.Firewall
  Device.Hosts
  Device.IP
  Device.IP.Diagnostics
  Device.InterfaceStack
  Device.LEDs
  Device.Logical
  Device.ManagementServer
  Device.NAT
  Device.NeighborDiscovery
  Device.PCP
  Device.PPP
  Device.PacketInterception
  Device.QoS
  Device.RouterAdvertisement
  Device.Routing
  Device.SSH
  Device.Security
  Device.SoftwareModules
  Device.Syslog
  Device.Time
  Device.UPnP
  Device.UserInterface
  Device.Users
  Device.WiFi
  Device.XPON
  Device.X_PRPL-COM_MultiSettings
  Device.X_PRPL-COM_PersistentConfiguration
  Device.X_PRPL-COM_WANManager
  DeviceInfo
  DeviceInfo.DeviceImageFile
  DeviceInfo.FirmwareImage
  DeviceInfo.Location
  DeviceInfo.LogRotate
  DeviceInfo.MemoryStatus
  DeviceInfo.ProcessStatus
  DeviceInfo.ProcessStatus.Process
  DeviceInfo.Processor
  DeviceInfo.VendorConfigFile
  DeviceInfo.VendorLogFile
  Devices
  Devices.Config
  Devices.Config.global
  Devices.Device
  Devices.Query
  DynamicDNS
  DynamicDNS.Client
  DynamicDNS.Server
  Ethernet
  Ethernet.Interface
  Ethernet.Link
  Ethernet.Link.Stats
  Ethernet.VLANTermination
  Ethernet.VLANTermination.Stats
  Firewall
  Firewall.Chain
  Firewall.ConnectionTracking
  Firewall.ConnectionTracking.SIP
  Firewall.DMZ
  Firewall.Level
  Firewall.Pinhole
  Firewall.Policy
  Firewall.Service
  Firewall.X_PRPL-COM_InterfaceSetting
  Firewall.X_PRPL-COM_Log
  Firewall.X_PRPL-COM_WANAccess
  Firewall.X_PRPL-COM_WANAccess.BlockList
  Hosts
  Hosts.AccessControl
  Hosts.Host
  IP
  IP.ActivePort
  IP.Interface
  IPDiagnostics
  IPDiagnostics.IPPing
  IPDiagnostics.IPPing.Process
  IPDiagnostics.TraceRoute
  IPDiagnostics.TraceRoute.Process
  IPDiagnostics.TraceRoute.RouteHops
  IPDiagnostics.X_PRPL-COM_DownloadConfig
  IPDiagnostics.X_PRPL-COM_DownloadResult
  IPDiagnostics.X_PRPL-COM_DownloadResult.Config
  IPDiagnostics.X_PRPL-COM_DownloadResult.IncrementalResult
  IPDiagnostics.X_PRPL-COM_DownloadResult.Process
  IPDiagnostics.X_PRPL-COM_UploadConfig
  IPDiagnostics.X_PRPL-COM_UploadResult
  IPDiagnostics.X_PRPL-COM_UploadResult.Config
  IPDiagnostics.X_PRPL-COM_UploadResult.IncrementalResult
  IPDiagnostics.X_PRPL-COM_UploadResult.PerConnectionResult
  IPDiagnostics.X_PRPL-COM_UploadResult.Process
  LEDs
  LEDs.LED
  Logical
  Logical.Interface
  Logical.X_PRPL-COM_Subnet
  Logical.X_PRPL-COM_Subnet.Config
  ManagementServer
  ManagementServer.ACSTransfers
  ManagementServer.ACSTransfers.ACSTransfer
  ManagementServer.ConnRequest
  ManagementServer.InternalSettings
  ManagementServer.ManageableDevice
  ManagementServer.State
  ManagementServer.Stats
  ManagementServer.Subscription
  MultiSettings
  MultiSettings.Profile
  NAT
  NAT.InterfaceSetting
  NAT.PortMapping
  NAT.PortTrigger
  NeighborDiscovery
  NeighborDiscovery.InterfaceSetting
  NetDev
  NetDev.ConversionTable
  NetDev.ConversionTable.Protocol
  NetDev.ConversionTable.Scope
  NetDev.ConversionTable.Table
  NetDev.Link
  NetDev.Stats
  NetModel
  NetModel.Intf
  PCP
  PCP.Client
  PPP
  PPP.Interface
  PPP.Interface.IPCP
  PPP.Interface.IPv6CP
  PPP.Interface.PPPoE
  PPP.Interface.Stats
  PacketInterception
  PacketInterception.CommunicationConfig
  PacketInterception.CommunicationConfig.Socket
  PacketInterception.Condition
  PacketInterception.Interception
  PacketInterception.PacketHandler
  PersistentConfiguration
  PersistentConfiguration.BackupFile
  PersistentConfiguration.Config
  PersistentConfiguration.Config.Security
  PersistentConfiguration.Service
  ProcessMonitor
  ProcessMonitor.Test
  ProxyManager
  QoS
  QoS.Classification
  QoS.Node
  QoS.Queue
  QoS.QueueStats
  QoS.Scheduler
  QoS.Shaper
  Rlyeh
  Rlyeh.Images
  RouterAdvertisement
  RouterAdvertisement.InterfaceSetting
  Routing
  Routing.RIP
  Routing.RIP.InterfaceSetting
  Routing.RouteInformation
  Routing.RouteInformation.InterfaceSetting
  Routing.RouteInformation.InterfaceSetting.Option
  Routing.Router
  Routing.Router.IPv6Forwarding
  SSH
  SSH.AuthorizedKey
  SSH.Server
  Security
  Security.Certificate
  SoftwareModules
  SoftwareModules.DeploymentUnit
  SoftwareModules.ExecEnv
  SoftwareModules.ExecutionUnit
  SoftwareModules.NetworkConfig
  SoftwareModules.NetworkConfig.Interfaces
  SoftwareModules.Plugins
  Syslog
  Syslog.Action
  Syslog.Filter
  Syslog.Source
  Syslog.Template
  System
  Time
  Time.Client
  Time.Server
  Timingila
  Timingila.ProxyManager
  UPnP
  UPnP.Device
  UPnP.IGDConfig
  Unbound
  UserInterface
  UserInterface.HTTPAccess
  Users
  Users.Group
  Users.Role
  Users.SupportedShell
  Users.User
  WANManager
  WANManager.WAN
  WiFi
  WiFi.AccessPoint
  WiFi.AutoCommitMgr
  WiFi.AutoNeighbourAddition
  WiFi.EndPoint
  WiFi.Radio
  WiFi.SSID
  WiFi.Vendor
  WiFi.wps_DefParam
  XPON
  XPON.ONU
  X_PRPL-ORG
  X_PRPL-ORG.prplMeshAgent
  X_PRPL-ORG.prplMeshAgent.Fronthaul
