#!/bin/sh

if [ -f $IPKG_INSTROOT/lib/pon.sh ]; then
	. $IPKG_INSTROOT/lib/pon.sh
fi

if [ ! -f /etc/config/optic ]; then
	touch /etc/config/optic
fi

case $(pon_board_name) in
# This change is required to reduce impact of the power 1v8 noise
# affecting PLLs and SerDes performance.
# This is a workaround for SFU-B boards which should be fixed.
prx321-sfu* | prx321-hgu*)
	uci set optic.common.loop_timing_power_save=0
	;;
# Use high power loop timing mode on all URX boards by default
lgm* | urx851*)
	uci set optic.common.loop_timing_power_save=0
	;;
esac
