# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MXL_NP_NET_CORE) += xpcs/
obj-$(CONFIG_MXL_NP_NET_CORE) += gswip/
obj-$(CONFIG_MXL_NP_NET_CORE) += p34x/
obj-$(CONFIG_MXL_NP_NET_CORE) += cqm/
obj-$(CONFIG_MXL_NP_NET_CORE) += dpm/
obj-$(CONFIG_MXL_NP_NET_CORE) += datapath_wa/
obj-$(CONFIG_MXL_NP_NET_CORE) += umt/
obj-$(CONFIG_MXL_NP_NET_CORE) += vpn/
obj-$(CONFIG_LGM_TOE) += toe/
obj-$(CONFIG_QOS_TC) += qos_tc/
obj-$(CONFIG_QOS_NOTIFY) += qos_notify/
obj-$(CONFIG_DP_OAM) += dp_oam/
obj-$(CONFIG_DP_MCAST_BRIDGE_FILTER) += bridge_filter/
obj-$(CONFIG_DP_ETH_REINSERT) += dp_eth_reinsert/
obj-$(CONFIG_MXL_MIB_COUNTERS) += mib_counters/
obj-y += directpath/
