#!/bin/sh

if [ -f $IPKG_INSTROOT/lib/pon.sh ]; then
	.  $IPKG_INSTROOT/lib/pon.sh
fi

if [ ! -f /etc/config/optic ]; then
	touch  /etc/config/optic
fi

eeprom_dmi=$(pon_transceiver_eeprom_path "dmi")
eeprom_serial_id=$(pon_transceiver_eeprom_path "serial_id")

uci set optic.sfp_eeprom=optic
uci set optic.sfp_eeprom.comment="settings for pon v1.17 or later"
uci set optic.sfp_eeprom.dmi="$eeprom_dmi"
uci set optic.sfp_eeprom.serial_id="$eeprom_serial_id"

old_eeprom=$(uci -q get optic.eeprom)
if [ -n "$old_eeprom" ]; then
	uci set optic.eeprom.comment="settings for pon v1.16 or older"
fi
