#!/bin/sh /etc/rc.common
# Program:
#       Config LED behavior during boot-up and interface connect/disconnect
# History:
# 2021/11/26    Ray Chang First release

START=13
USE_PROCD=1

lgm_cpe_check()
{
    cpename="LGM"
    banner="$(cat /etc/banner)"

    [[ ! "$banner" =~ "$cpename" ]] &&
    {
        #Not LGM board
        exit;
    }
}

led_behavior_boot()
{
    #Blink 1s period, Include wifi2.4GHz, wifi5GHz Low Band, wifi5GHz High Band
    period_time=1000
    strfilter="G" #filter by WIFI led

    dir='/sys/class/leds'
    for eachfile in "$dir"/*
    do
        if [[ "$eachfile" =~ "$strfilter" ]];then
            strLED="${eachfile##*/}"

            if [ -f /sys/class/leds/"$strLED"/state ];then
                echo none > /sys/class/leds/"$strLED"/trigger
            else
                echo transient > /sys/class/leds/"$strLED"/trigger
                echo $period_time > /sys/class/leds/"$strLED"/duration
                echo 1 > /sys/class/leds/"$strLED"/state
                echo 1 > /sys/class/leds/"$strLED"/activate
            fi
        fi
    done
}

start_service() {

    lgm_cpe_check
    led_behavior_boot

    procd_open_instance
    procd_set_param command /opt/intel/bin/led-lgm.sh
    procd_close_instance
}

stop_service()
{
	#echo "LED Stop" > /dev/console
	procd_kill led-lgm
}
