# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SOC_LGM)	+= lgm_soc.o
obj-$(CONFIG_MXL_NOC_FIREWALL) += lgm_noc_firewall.o
obj-$(CONFIG_MXL_NOC_FW_DEFAULT) += lgm_noc_fw_dm.o
obj-$(CONFIG_MXL_SEC_GEN_POOL) += lgm_gen_pool.o
obj-$(CONFIG_MXL_FW_DOWNLOAD) += lgm_fw_download.o
obj-$(CONFIG_MXL_LGM_SYSCTL) += lgm_sysctl.o
obj-$(CONFIG_MXL_SKB_EXT) += mxl_skb_ext.o
obj-$(CONFIG_MXL_SKB_EXT_EXTMARK) += mxl_skb_ext_extmark.o
