variables:
  CI_DESIGNATED_BRANCH: prplos-22.03

include:
  - local: .gitlab/build.yml
  - local: .gitlab/release.yml
  - local: .gitlab/cdrouter.yml
  - local: .gitlab/cdrouter/prpl-haze.yml
  - local: .gitlab/cdrouter/turris-omnia.yml
  - local: .gitlab/cdrouter/urx851-hdk-3.yml
  - local: .gitlab/cdrouter/mxl25641-hdk-6.yml
  - local: .gitlab/cdrouter/wnc-freedom.yml
  - local: .gitlab/coverity.yml
  - local: .gitlab/docker.yml
  - local: .gitlab/docker/builder/gitlab.yml
  - local: .gitlab/docker/testbed/gitlab.yml
  - local: .gitlab/docker/sdk/gitlab.yml
  - local: .gitlab/docker/ib/gitlab.yml
  - local: .gitlab/docker/ib/lcm/gitlab.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/prpl-haze.yml
  - local: .gitlab/testbed/turris-omnia.yml
  - local: .gitlab/testbed/urx851-hdk-3.yml
  - local: .gitlab/testbed/urx851-b0-dk-pon.yml
  - local: .gitlab/testbed/mxl25641-hdk-6.yml
  - local: .gitlab/testbed/wnc-freedom.yml

stages:
  - docker
  - docker test
  - docker deploy
  - build
  - release
  - docker SDK and IB
  - docker SDK and IB test
  - docker SDK and IB deploy
  - docker IB LCM container
  - run
  - cdrouter
  - coverity

.build test mxl_x86 mxl_wlan_hostap_ng prpl security:
  image: registry.gitlab.com/prpl-foundation/prplos/prplos/prplos-next/builder-osp@sha256:c3e7d58f4ca821b78386da1a36c8a9646805cdc5b746500464411c245b95d049
  extends: .build test config
  artifacts:
  tags:
    - firmware-builder-osp

build test mxl_x86_osp_tb341 mxl_wlan_hostap_ng prpl security:
  image: registry.gitlab.com/prpl-foundation/prplos/prplos/prplos-next/builder-osp@sha256:c3e7d58f4ca821b78386da1a36c8a9646805cdc5b746500464411c245b95d049
  extends: .build test config
  artifacts:
  tags:
    - firmware-builder-osp

build test mxl_x86_osp_tb341_v2 mxl_wlan_hostap_ng_wav700 prpl security:
  image: registry.gitlab.com/prpl-foundation/prplos/prplos/prplos-next/builder-osp@sha256:c3e7d58f4ca821b78386da1a36c8a9646805cdc5b746500464411c245b95d049
  extends: .build test config
  artifacts:
  tags:
    - firmware-builder-osp

build test mvebu prpl security:
  extends: .build test config

build test x86_64 prpl security:
  extends: .build test config

build test ipq807x prpl security:
  extends: .build test config

build test qca_ipq95xx prpl security:
  extends: .build test config

coverity scan ipq807x prpl:
  extends: .coverity scan config
  variables:
    CI_COVERITY_COMPILER_TEMPLATE_LIST: >
      aarch64-openwrt-linux-gcc
      aarch64-openwrt-linux-musl-gcc

run test Turris Omnia initramfs:
  needs:
    - job: build test mvebu prpl security
      optional: true
  extends: .turris-omnia testbed

run test Haze initramfs:
  needs:
    - job: build test ipq807x prpl security
      optional: true
  extends: .prpl-haze testbed

run test URX851-HDK-3 with system on eMMC:
  needs:
    - job: build test mxl_x86_osp_tb341 mxl_wlan_hostap_ng prpl security
      optional: true
  extends: .urx851-hdk-3 testbed

.run test URX851-B0-DK-PON with system on eMMC:
  needs:
    - job: build test mxl_x86 mxl_wlan_hostap_ng prpl security
      optional: true
  extends: .urx851-b0-dk-pon testbed

run test MXL25641-HDK-6 with system on eMMC:
  needs:
    - job: build test mxl_x86_osp_tb341_v2 mxl_wlan_hostap_ng_wav700 prpl security
      optional: true
  extends: .mxl25641-hdk-6 testbed

run test Freedom initramfs:
  needs:
    - job: build test qca_ipq95xx prpl security
      optional: true
  extends: .wnc-freedom testbed
