#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /etc/ugw_notify_defs.sh;
. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 3 ]
then
	echo "WPS Button pressed for less than 3 seconds..treating as spurious" > /dev/console
elif [ "$SEEN" -gt 3 ]
then
	echo "WPS Button pressed for $SEEN seconds..Activating PBC functionality" > /dev/console
	echo "enable WPS on wlan0.1" > /dev/console
	hostapd_cli -i wlan0.1 wps_pbc

	# sleep 1
	# echo "enable WPS on wlan2.2" > /dev/console
	# hostapd_cli -i wlan2.2 wps_pbc
fi

return 0
