#!/bin/sh

. /lib/functions/uci-defaults.sh
. /lib/pon.sh

interface="lct"

case $(pon_board_name) in
*w5500*)
	# This has a w5500 module as management port
	interface="mgmt"
	;;
*eth | *hgu*)
	# This is configured for Ethernet WAN (or a HGU board)
	interface="bridge"
	;;
*)
	# This is configured for PON WAN
	interface="lct"
	;;
esac

local ip=$(awk 'BEGIN{RS=" ";FS="="} $1 == "ip" {print $2}' /proc/cmdline)
local ipaddr=$(echo $ip | awk 'BEGIN{FS=":"} {print $1}')
local gateway=$(echo $ip | awk 'BEGIN{FS=":"} {print $3}')
local netmask=$(echo $ip | awk 'BEGIN{FS=":"} {print $4}')
[ -n "$ipaddr" ] && uci set network.$interface.ipaddr=$ipaddr
[ -n "$gateway" ] && uci set network.$interface.gateway=$gateway
[ -n "$netmask" ] && uci set network.$interface.netmask=$netmask
