#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10

start_service() {
	for card in /proc/net/mtlk/card*; do
		index=${card##/proc/net/mtlk/card}
		procd_open_instance
		procd_set_param command /opt/intel/bin/dump_handler -i "$index" -f /opt/intel/wave/
		procd_set_param env PATH="${PATH}":/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:"${LD_LIBRARY_PATH}"
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	done
}
