#!/bin/sh /etc/rc.common

START=23

start() {
	ipaddr=$(fw_printenv -n ipaddr)
	netmask=$(fw_printenv -n netmask)
	gateway=$(fw_printenv -n gatewayip)
	
	if [ -n "$ipaddr" ] && [ -n "$netmask" ] && [ -n "$gateway" ]; then
		$(uci set network.lan.ipaddr=$ipaddr)
		$(uci set network.lan.netmask=$netmask)
		$(uci set network.lan.gateway=$gateway)
	fi

	OUTPUT=$(cat /proc/cmdline)
	INDEX=$(awk -v a="$OUTPUT" -v b=ethaddr 'BEGIN{print index(a,b)}')
	INDEX="$((INDEX-1))"
	ETHVAR=${OUTPUT:INDEX:25}
	unparsed_macaddr=$(echo "$ETHVAR" | cut -d ' ' -f1)
	cmdline_macaddr=$(echo "$unparsed_macaddr" | cut -d= -f2)

	if [ -z "$cmdline_macaddr" ]; then
		echo "Empty MAC Address assigned at bootloader prompt, skipping MAC Address assignment" > /dev/console
	    return
	fi

	filtered_mac=$(echo $cmdline_macaddr | tr -d ':')
	mac_with_offset=$(( 0x$filtered_mac + 4 ))
	brlan_macaddr=$(printf "%012x" $mac_with_offset | sed 's/../&:/g;s/:$//')

	# Ethernet Manager overrides LAN mac address so using ubus command to set LAN mac address)
	ubus call Ethernet.Link.3 _set '{"parameters": {"MACAddress":'"'$brlan_macaddr'"'}}'

	lan_port_id=$(uci get network.eth0_1)
	if [ -z "$lan_port_id" ]; then
		$(uci set network.eth0_1="device")
		$(uci set network.eth0_1.name="eth0_1")
	fi
	$(uci set network.eth0_1.macaddr=$brlan_macaddr)

	first_octet=ae
	mid_octet=${cmdline_macaddr:6:15}
	last_octet=0

	for i in 1 2 3 4
	do
		last_octet=$((last_octet+1))
		lan_port_macaddr=$first_octet':'$mid_octet':'$(printf "%02x" $last_octet)
		port_idx=$((i+1))

		lan_port_id=$(uci get network.eth0_$port_idx)
		if [ -z "$lan_port_id" ]; then
			$(uci set network.eth0_$port_idx="device")
			$(uci set network.eth0_$port_idx.name="eth0_$port_idx")
		fi
		$(uci set network.eth0_$port_idx.macaddr=$lan_port_macaddr)
	done

	$(uci commit network)
	$(reload_config)
	ubus call Ethernet.Link.2 _set '{"parameters": {"MACAddress":'"'$cmdline_macaddr'"'}}'
}
