#!/bin/sh /etc/rc.common
# Add Physical Interfaces to PPA.
#

START=20
USE_PROCD=1

. $IPKG_INSTROOT/etc/profile.d/intel.sh
. $IPKG_INSTROOT/usr/share/libubox/jshn.sh

CFG=/etc/board.json
PWHMCFG=/etc/networklayout.json
sys_cli_ppa_file=/tmp/ppacmd_lines

generate_ppa_config() {
	local ifname
	if [ "$1" == "lan" ]
	then
		json_select network
			json_select "$1"
				if json_is_a ports array
				then
					json_select ports
					idx=1
					while json_is_a ${idx} string 
					do
						json_get_var port $idx
						if [ ${idx} == 1 ]
						then
							ifname="$port"
						else
							ifname="$ifname $port"
						fi
						idx=$(( idx + 1 ))
					done
					json_select ..
				fi
			json_select ..
		json_select ..
	else [ "$1" == "wan" ]
		json_select network
			json_select "$1"
				json_get_var ifname device
			json_select ..
		json_select ..
	fi

	if [ "$1" == "lan" -o "$1" == "wan" ]
	then
		[ -n "$ifname" ] || return
		echo "config ppa '$1'" >> /etc/config/ppa
		echo "  option type '$1'" >> /etc/config/ppa
		echo "  option ifname '$ifname'" >> /etc/config/ppa
	fi
}

prepare_ppa_cmds() {
	local section="$1"
	local section_type
	local i

	config_get section_type $section type
	config_get ifname $section ifname

	if [ $section_type == "lan" ]
	then
		for i in $ifname
		do
			echo "addlan -i $i" >> $sys_cli_ppa_file
		done
	elif [ $section_type == "wan" ]
	then
		for i in $ifname
		do
			echo "addwan -i $i" >> $sys_cli_ppa_file
		done
	fi
}

prepare_ppa_cmds_wireless() {
	if [ -s $PWHMCFG ]
	then
		json_init
		json_load_file $PWHMCFG
		json_select "Bridges"
		json_select "Lan"

		if json_is_a Ports array
		then
			json_select Ports
			json_get_keys keys
			idx=1
			for key in $keys
			do
				json_select "$key"
				if [ ${idx}  -gt  5 ]
				then
					json_get_var ifname Name
					[ -n $ifname ] && echo "addlan -i $ifname" >> $sys_cli_ppa_file
				fi
			json_select ".."
			idx=$(( idx + 1 ))
			done
			json_close_array
		fi

		json_close_object
		json_select "Guest"

		if json_is_a Ports array
		then
			json_select Ports
			json_get_keys keys
			for key in $keys
			do
				json_select "$key"
				json_get_var ifname Name
				[ -n $ifname ] && echo "addlan -i $ifname" >> $sys_cli_ppa_file
				json_select ".."
			done
			json_close_array
		fi
		json_close_object
	fi
}

start_service() {
	if [ ! -s /etc/config/ppa ]
	then
		[ -s $CFG ] || /bin/board_detect || exit 1

		json_init
		json_load "$(cat ${CFG})"

		json_get_keys keys
		json_get_keys keys network
		for key in $keys; do generate_ppa_config $key; done
	fi
	if [ -s "$sys_cli_ppa_file" ]
	then
		rm "$sys_cli_ppa_file"
	fi
	config_load ppa
	config_foreach prepare_ppa_cmds ppa
	prepare_ppa_cmds_wireless
	procd_open_instance
	procd_set_param command "/bin/ppa.sh" "$sys_cli_ppa_file"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	ppacmd exit
}

service_triggers()
{
	procd_add_reload_trigger "ppa"
}

reload_service()
{
	stop
	start
}
