#!/bin/sh

create_rootfs_data() {
	is_emmc_flash=0

	cat /proc/partitions | grep -q "mmcblk0p" && is_emmc_flash=1

	# Create rootfs_data partition for nand flash based LGP boards.
	if [ $is_emmc_flash == 0 ];then
		ubinfo /dev/ubi0 --name=rootfs_data  &>/dev/null || ubimkvol /dev/ubi0 -N rootfs_data -s 0x2000000
	fi
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main create_rootfs_data
