#!/bin/sh

mount_root_lgm() {
	local state rootfs_data_partname overlay_container_a_partname securestore_a_partname securestore_b_partname lcm_data_partname
	
	for partition in $(ls /sys/class/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0*/uevent); do
		partname=$(grep -q -w "PARTNAME=rootfs_data" "$partition" && grep "DEVNAME" "$partition" | cut -d= -f2)
		if [ $? -eq 0 ]; then
			rootfs_data_partname=$partname
		fi
		partname=$(grep -q -w "PARTNAME=overlay_container_a" "$partition" && grep "DEVNAME" "$partition" | cut -d= -f2)
		if [ $? -eq 0 ]; then
			overlay_container_a_partname=$partname
		fi
		partname=$(grep -q -w "PARTNAME=securestore_a" "$partition" && grep "DEVNAME" "$partition" | cut -d= -f2)
		if [ $? -eq 0 ]; then
			securestore_a_partname=$partname
		fi
		partname=$(grep -q -w "PARTNAME=securestore_b" "$partition" && grep "DEVNAME" "$partition" | cut -d= -f2)
		if [ $? -eq 0 ]; then
			securestore_b_partname=$partname
		fi
		partname=$(grep -q -w "PARTNAME=lcm_data" "$partition" && grep "DEVNAME" "$partition" | cut -d= -f2)
		if [ $? -eq 0 ]; then
			lcm_data_partname=$partname
		fi

	done
	
	overlay_partname="$([ -n "$rootfs_data_partname" ] && echo "$rootfs_data_partname" || [ -n "$overlay_container_a_partname" ] && echo "$overlay_container_a_partname")"

	[ ! -z "$overlay_partname" ] && [ -e "/dev/$overlay_partname" ] && {
		e2fsck -p /dev/$overlay_partname > /dev/null
		ret=$?

		if [ $(( ret&4 )) -eq 4 ]; then
			echo "e2fsck recovery failed"
			e2fsck -y /dev/$overlay_partname > /dev/null
		fi

		mount -t ext4 /dev/$overlay_partname /overlay/ || {
			mkfs.ext4 /dev/$overlay_partname
			mount -t ext4 /dev/$overlay_partname /overlay/
		}

		state=$(readlink /overlay/.fs_state)
		if ! [ -n "$state" -a "$state" = "2" ]; then
			# Do a factory reset if .fs_state file missing or shows something else otherthan 2.
			rm -rf /overlay/* /overlay/*.*

			# XXX
			# Below link (.fs_state) should be pointing to 1 instead of 2.
			# Currently 'mount_root done' command from /etc/init.d/done is not working which changes this to 2.
			# Once that works, we need to change below line to ln -sf 1 /overlay/.fs_state
			ln -sf 2 /overlay/.fs_state
		fi

		mkdir -p /overlay/upper /overlay/work

		[ -d /overlay/upper -a -d /overlay/work ] && {
			mount -t overlay overlayfs:/overlay -o rw,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /mnt
			mount -o move /proc /mnt/proc && \
				pivot_root /mnt /mnt/rom && {
					mount -o move /rom/dev /dev
					mount -o move /rom/sys /sys 2>&-
					mount -o move /rom/overlay /overlay 2>&-
			}
			mount -t tmpfs tmpfs /tmp
			mkdir -p /tmp/run /tmp/state
		}
	}
	
	[ ! -z "$securestore_a_partname" ] && [ -e "/dev/$securestore_a_partname" ] && {
		if [ ! -d "/cfg" ]; then
			mkdir /cfg
			chmod 600 /cfg
		fi
		
		e2fsck -p /dev/$securestore_a_partname > /dev/null
		ret=$?
		
		if [ $(( ret&4 )) -eq 4 ]; then
			echo "e2fsck recovery failed"
			e2fsck -y /dev/$securestore_a_partname > /dev/null
		fi
		
		mount -t ext4  /dev/$securestore_a_partname /cfg || {
			mkfs.ext4 /dev/$securestore_a_partname
			mount -t ext4 /dev/$securestore_a_partname /cfg
		}

		ln -s /cfg /tmp/securestore

		[ -d /tmp/securestore -a -e /securestore ] || {
			ln -s /tmp/securestore /securestore
		}
	}

	[ ! -z "$securestore_b_partname" ] && [ -e "/dev/$securestore_b_partname" ] && {
		mkdir -p /tmp/securestore_b
		chmod 600 /tmp/securestore_b

		e2fsck -p /dev/$securestore_b_partname > /dev/null
		ret=$?

		if [ $(( ret&4 )) -eq 4 ]; then
			echo "e2fsck recovery failed"
			e2fsck -y /dev/$securestore_b_partname > /dev/null
		fi

		mount -t ext4  /dev/$securestore_b_partname /tmp/securestore_b || {
			mkfs.ext4 /dev/$securestore_b_partname
			mount -t ext4 /dev/$securestore_b_partname /tmp/securestore_b
		}

		[ -d /tmp/securestore_b -a -e /securestore_b ] || {
			ln -s /tmp/securestore_b /securestore_b
		}
	}

	[ ! -z "$lcm_data_partname" ] && [ -e "/dev/$lcm_data_partname" ] && {
		if [ ! -d "/lcm" ]; then
			mkdir /lcm
			chmod 600 /lcm
		fi

		e2fsck -p /dev/$lcm_data_partname > /dev/null
		ret=$?

		if [ $(( ret&4 )) -eq 4 ]; then
			echo "e2fsck recovery failed"
			e2fsck -y /dev/$lcm_data_partname > /dev/null
		fi

		mount -t ext4  /dev/$lcm_data_partname /lcm || {
			mkfs.ext4 /dev/$lcm_data_partname
			mount -t ext4 /dev/$lcm_data_partname /lcm
		}

	}

}

boot_hook_add preinit_main mount_root_lgm
