#!/bin/sh

update_ipsec_link_ramfs()
{
	ln -sf /tmp/ipsec/ipsec.conf /etc/ipsec.conf 2>/dev/null
	ln -sf /tmp/ipsec/strongswan.conf /etc/strongswan.conf 2>/dev/null
	ln -sf /tmp/ipsec/ipsec.secrets /etc/ipsec.secrets 2>/dev/null
}

boot_hook_add preinit_main update_ipsec_link_ramfs
