#!/bin/sh -x

OLD_VPATH="opt/lantiq"
_old_pas=""
NEW_PATH="upper/opt/intel"


c_clr="\033[00;00m"
c_red="\033[31;01m"

_err()
{
        echo -en "${c_red}Error: $@${c_clr}\n";
}

upgrade()
{
        vol_data=`ls /sys/class/ubi/ubi0*/name 2>/dev/null | xargs grep data_vol | cut -d'/' -f6`
	local cmd_line t_active_bank active_bank t_update_chk update_chk
	mkdir -p /tmp/upgrade
	cmd_line="`cat /proc/cmdline`";
	[ -z "${cmd_line##*active_bank=[AB]*}" ] && {
		t_active_bank=${cmd_line##*active_bank=};
		active_bank=${t_active_bank::1};
	} || active_bank=A;

	[ -z "${cmd_line##*update_chk=[0-4]*}" ] && {
		t_update_chk=${cmd_line##*update_chk=};
		update_chk=${t_update_chk::1};
	} || update_chk=0;

	if [ "$active_bank" = "B" -a "$update_chk" = "0" ] || [ "$active_bank" = "A" -a "$update_chk" != "0" ]; then
		if [ "$vol_data" == "name:data_vol" ]; then
			ubirename /dev/ubi0 data_vol rootfs_data
		fi
		vol_name=`ls /sys/class/ubi/ubi0*/name|xargs grep -w rootfs_data|cut -d'/' -f5`
		mkdir /tmp/rootfs_data
		mount -t ubifs /dev/$vol_name /tmp/rootfs_data/
		rc=$?
		if [ $rc = 0 ]; then
			export LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
			mkdir /tmp/dbmerge
			cd /tmp/rootfs_data

			secureNode=`cat /proc/devices | grep secure* | cut -d " " -f1`
			mknod /dev/secure_service_driver c $secureNode 0

			if [ -d "$NEW_PATH" ]; then
				[ -f "$NEW_PATH/csd/etc/csdswap" ] && file="$NEW_PATH/csd/etc/csdswap" || file="$NEW_PATH/etc/csd/csdswap"
				_lastmodified=`cat $file | cut -d \= -f 2`

				[ -d "$NEW_PATH/csd/config/" ] && oldDbPath="$NEW_PATH/csd/config" || oldDbPath="$NEW_PATH/config" _old_pas="set"
				if [[ $_lastmodified -eq 1 ]] ; then
					oldDb="$oldDbPath/.run-data.xml"
				else
					oldDb="$oldDbPath/.run-data-swp.xml"
				fi

			elif [ -d "$OLD_VPATH" ]; then
				file="$OLD_VPATH/etc/csd/csdswap"
				_old_pas="set"
				_lastmodified=`cat $file | cut -d \= -f 2`
				if [[ $_lastmodified -eq 1 ]] ; then
					oldDb="$OLD_VPATH/config/.run-data.xml"
				else
					oldDb="$OLD_VPATH/config/.run-data-swp.xml"
				fi
			fi
			if [ -n "$oldDb" ]; then
				VPATH=${NEW_PATH/upper}
				#bootcore init to complete
				sleep 5
				$VPATH/usr/sbin/csdutil merge "$oldDb" $VPATH/csd/etc/datacfg $VPATH/csd/etc/ctrlcfg $VPATH/etc/db_merge.conf /tmp/dbmerge/ $_old_pas >&- 2>&-
				rc=$?
				if [ $rc = 0 ]; then
					cp $NEW_PATH/etc/upgrade/.upg_state_file /tmp/dbmerge/
					cp $NEW_PATH/etc/upgrade/.flash_cnt_chk /tmp/dbmerge/

					rm -rf *
					mkdir -p $NEW_PATH/csd/config/
					mkdir -p $NEW_PATH/csd/etc/
					mkdir -p $NEW_PATH/etc/upgrade/
					mkdir -p upper/etc/config/
					mkdir -p upper/etc/uci-defaults/
					cp /tmp/dbmerge/.run-data.xml /tmp/dbmerge/.run-control.xml $NEW_PATH/csd/config/
					cp /tmp/dbmerge/csdswap $NEW_PATH/csd/etc/

					cp /tmp/dbmerge/.upg_state_file $NEW_PATH/etc/upgrade/
					cp /tmp/dbmerge/.flash_cnt_chk $NEW_PATH/etc/upgrade/
					ln -s 2 .fs_state
				else
					rm -rf *
					_err "Confg Merge failed"
				fi
			else
				_err "Db file not found"
			fi
			cd ../../
			umount /tmp/rootfs_data/
			rm -rf /tmp/rootfs_data
			rm -rf /tmp/dbmerge
		else
			_err "Mount unsuccessful"
			rm -rf /tmp/rootfs_data
		fi
	fi
}

upgrade
