#!/bin/sh /etc/rc.common

USE_PROCD=1
START=20

PROG=/opt/intel/usr/sbin/fwupgrade

start_service() {
	mkdir -p /tmp/upgrade
	[ ! -d "/mnt/upgrade" ] && mkdir -p /tmp/mount_upgrade && ln -s /tmp/mount_upgrade /mnt/upgrade	
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
