version opencryptoki-3.24

disable-event-support
statistics (off)
# The following defaults are defined:
#       hwversion = "0.0"
#       firmwareversion = "0.0"
#       description = Linux
#       manufacturer = IBM
#       usergroup = pkcs11
#
# The slot definitions below may be overridden and/or customized.
# For example:
#       slot 0
#       {
#          stdll = libpkcs11_cca.so
#          description = "OCK CCA Token"
#          manufacturer = "MyCompany Inc."
#          hwversion = "2.32"
#          firmwareversion = "1.0"
#          tpkname = mytoken
#          usergroup = mygroup
#       }
#
# See man(5) opencryptoki.conf for further information.
#
slot 0
{
    stdll = libpkcs11_mxl.so
    tokversion = 1.0
    tokname = mxl-tep
}
