#!/bin/sh

_help()
{
	echo "Resets system configuration and applications.";
	exit $1;
}

[ -n "$1" ] && {
	case "$1" in
		-h) _help 0;
		;;
		*) _help 1;
		;;
        esac
}

rm -rf /overlay/.fs_state
sync
reboot
