#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

start_daemon() {
	local cfg="$1"

	local atmdev disabled

	config_get_bool disabled "$cfg" disabled 0
	[ "$disabled" -eq 1 ] && return

	config_get atmdev "$cfg" atmdev 0

	local nameprefix
	config_get nameprefix "$cfg" nameprefix "nas"

	local unit
	config_get unit "$cfg" unit 0

	local vpi
	config_get vpi "$cfg" vpi 8

	local vci
	config_get vci "$cfg" vci 35

	local encaps
	config_get encaps "$cfg" encaps

	case "$encaps" in
		1|vc) encaps=1;;
		*) encaps=0;;
	esac

	local payload
	config_get payload "$cfg" payload

	case "$payload" in
		0|routed) payload=0;;
		*) payload=1;;
	esac

	local qos
	config_get qos "$cfg" qos

	local sendsize
	config_get sendsize "$cfg" sendsize

	found=
	for device in /sys/class/atm/atm-device-00; do
		[ -d "$device" ] || break
		[ "$(cat $device/atmindex)" = "$atmdev" ] || continue
		found=1
		break
	done

	[ -n "$found" ] || return

	local circuit="$atmdev.$vpi.$vci"

	procd_open_instance $cfg
	procd_set_param command \
		/usr/sbin/br2684ctl_wrap "${nameprefix}${unit}" \
		-n "$nameprefix" -c "$unit" -e "$encaps" -p "$payload" \
		-a "$circuit" ${qos:+-q "$qos"} ${sendsize:+-s "$sendsize"} \
		-S /lib/netifd/br2684-up
	[ -f /usr/share/capabilities/br2684_cap.json ] && {
		procd_set_param user nwk
		procd_set_param capabilities /usr/share/capabilities/br2684_cap.json
	}
	procd_close_instance
}

service_triggers() {
	local script=$(readlink "$initscript")
	local name=$(basename ${script:-$initscript})

	procd_add_reload_trigger network
	procd_add_config_trigger "config.change" "atm_up" /etc/init.d/$name reload
	procd_add_config_trigger "config.change" "atm_down" /etc/init.d/$name reload off
}

atm_off() {
	local cfg="$1"
	procd_kill br2684ctl $cfg
}

br2684ctl_off()
{
	config_load network
	config_foreach atm_off atm-bridge
}

start_service() {
	config_load network
	config_foreach start_daemon atm-bridge
}

reload_service() {
	if [ -n "$1" -a "$1" = "off" ]; then
		br2684ctl_off;
	else
		stop
		start
	fi
}
