#!/bin/sh /etc/rc.common

START=12

USE_PROCD=1
NAME=rpcd
PROG=/sbin/rpcd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	[ -f /usr/share/capabilities/rpcd_cap.json ] && {
		procd_set_param user rpcd
		procd_set_param capabilities /usr/share/capabilities/rpcd_cap.json
	}
	procd_close_instance
}

stop() {
	service_stop /sbin/rpcd
}

reload() {
	service_reload /sbin/rpcd
}
