#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
		procd_open_instance
		procd_set_param command "$PROG" -F -l /bin/login
		## Commenting below Procd jail adaptations, as UGW Automation is completely dependent on telnet service.
		## If enabled Procd jail options, user is limited to do only few operations.
		##procd_add_jail telnetd
		##procd_add_jail_mount /etc/shadow /etc/passwd /bin/login /bin/busybox /bin/ash /dev /dev/pts
		procd_close_instance
}

