#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

USE_PROCD=1
START=50

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/vsftpd
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
