#!/bin/sh /etc/rc.common

APP=ppmd
USE_PROCD=1
START=99
STOP=20
DELAY=20

start_service() {
    check4pon
    check4dsl
    check4eth
    sleep ${DELAY}
    rm -fr /tmp/ppmd/
    mkdir -p /tmp/ppmd/
    cp /etc/config/ppmdcfg /tmp/ppmd/
    chown -R sscript:pwrgrp /tmp/ppmd/ 2> /dev/null
    chmod 770 /tmp/ppmd/
    chmod 440 /tmp/ppmd/ppmdcfg
    procd_open_instance ppmd
    procd_set_param env PATH=${PATH}:/opt/intel/bin
    procd_set_param command ${APP} -l
    procd_set_param user ppmd
	[ -f /usr/share/capabilities/ppmd_cap.json ] && {
		procd_set_param capabilities /usr/share/capabilities/ppmd_cap.json
	}
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "ppmdcfg"
}

reload_service() {
    tstamp=$(date)
    echo "${tstamp}: ppmd reload service triggered" >> /tmp/ppmd_service_log.txt
    DELAY=0
    stop
    start
}

service_stopped() {
    ppmd -a5
}

restart() {
    DELAY=0
    start
}

check4pon() {
    ps | grep -v grep | grep omci > /dev/null
    if [ $? -eq 0 ]; then
        uci set ppmdcfg.pon.enable=1
        uci commit ppmdcfg
    else
        uci set ppmdcfg.pon.enable=0
        uci commit ppmdcfg
    fi
}

check4dsl() {
    ps | grep -v grep | grep dsl_daemon > /dev/null
    if [ $? -eq 0 ]; then
        uci set ppmdcfg.dsl.enable=1
        uci commit ppmdcfg
    else
        uci set ppmdcfg.dsl.enable=0
        uci commit ppmdcfg
    fi
}

check4eth() {
    file="/tmp/eth_tmp.txt"
    ls -l /sys/class/net/ | grep "soc.[/,:,a-z,]*eth[0-9,a-z,@]*/net/" | awk '{print $9}' > $file
    if [ -s $file ];then
        uci set ppmdcfg.eth.enable=1
        uci set ppmdcfg.eth.phy_ifi=
        while read var; do
            uci add_list ppmdcfg.eth.phy_ifi="$var"
            uci commit ppmdcfg
        done < "$file"
    else
        uci set ppmdcfg.eth.enable=0
        uci commit ppmdcfg
    fi
    rm -f $file
}
