#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Maxlinear Inc.

# Enable to create CPU queues by pon_net_lib
enable_CPU_queues() {
	uci set omci.net=omci
	uci set omci.net.enable_cpu_queues=1
}

enable_CPU_queues
