#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	local ucidflt_found=0

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		ucidflt_found=1
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
	[ -n "$ucidflt_found" ] && {
		chown rpcd:rpcd /etc/config/*
		chmod 640 /etc/config/*
		chown rpcd:rpcd -R /tmp/.uci
		chmod 700 /tmp/.uci
		chmod 600 /tmp/.uci/*
	}
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/lock/procd
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	mkdir -p /tmp/resolv.conf.d
	chmod +x /tmp/resolv.conf.d
	touch /tmp/resolv.conf.d/resolv.conf.auto
	ln -sf /tmp/resolv.conf.d/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	grep -q bpf /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime,mode=0700 -t bpf bpffs /sys/fs/bpf
	grep -q pstore /proc/filesystems && /bin/mount -o noatime -t pstore pstore /sys/fs/pstore
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# The execution of wireless script is for cases when the config file is not found for
	# any reason, which can result in wifi interfaces not coming up
	# Example scenario could be: remove wireless uci config and reboot
	[ ! -f /etc/config/wireless -o ! -f /overlay/upper/etc/config/wireless ] && {
		cp /rom/etc/uci-defaults/wireless /etc/uci-defaults/wireless >/dev/null
		# compat for brcm47xx and mvebu
		sleep 1
	}
	# The execution of wireless script is required for when backup configuration
	# restore as phy detection is not happening and also db backup doesn't have
	# phy param which is added in wireless uci conf file on firstboot only
	[ -f /etc/config/wireless ] && {
		grep -q "option phy" /etc/config/wireless || cp /rom/etc/uci-defaults/wireless /etc/uci-defaults/ >/dev/null
	}

	/bin/config_generate
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config
}
