#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

FIREWALL_ZONE_FILE=/tmp/firewall/fw3.zone
validate_firewall_redirect()
{
	uci_validate_section firewall redirect "${1}" \
		'proto:or(uinteger, string)' \
		'src:string' \
		'src_ip:cidr' \
		'src_dport:or(port, portrange)' \
		'dest:string' \
		'dest_ip:cidr' \
		'dest_port:or(port, portrange)' \
		'target:or("SNAT", "DNAT")'
}

validate_firewall_rule()
{
	uci_validate_section firewall rule "${1}" \
		'proto:or(uinteger, string)' \
		'src:string' \
		'dest:string' \
		'src_port:or(port, portrange)' \
		'dest_port:or(port, portrange)' \
		'target:string'
}

service_triggers() {
	procd_add_reload_trigger firewall	

	procd_open_validate
	validate_firewall_redirect
	validate_firewall_rule
	procd_close_validate
}

start_service() {
	procd_open_instance
	procd_set_param command firewalld
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param user firewall
	procd_set_param capabilities /usr/share/capabilities/firewall_cap.json
	procd_set_param pseudofs_acl /usr/share/pseudofs_acl/firewall_pseudofs_acl.json
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
firewall_get_interface(){
    local zone=$1
    config_get network $zone network
    echo "$zone: $network" >> $FIREWALL_ZONE_FILE
}
reload_service() {
    >$FIREWALL_ZONE_FILE
    config_load firewall
    config_foreach firewall_get_interface zone    
    procd_send_signal firewall '*' SIGUSR1
}
