#!/bin/sh /etc/rc.common

START=20
STOP=85
USE_PROCD=1

PROCD_DEBUG=1

start_service() {
	if ! [ -s /etc/config/dhcp ]; then
		while ! [ -s /etc/config/dhcp ]
		do
			sleep 3;
		done
		#Wait for a while after updating the config file
		sleep 2;
	fi
	mkdir -p /tmp/dhcp_uci
	cp -rf /etc/config/dhcp /tmp/dhcp_uci/
	chmod 750 /tmp/dhcp_uci
	chmod 640 /tmp/dhcp_uci/dhcp
	chown -R sscript:odhcpd /tmp/dhcp_uci
	procd_open_instance
	procd_set_param command /usr/sbin/odhcpd -c /tmp/dhcp_uci/
	procd_set_param user odhcpd
	procd_set_param capabilities /usr/share/capabilities/odhcpd_cap.json
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	#procd_add_jail odhcpd ubus sysfs procfs log odhcpd-update
	#procd_add_jail_mount /etc/config/dhcp /dev/urandom /etc/hosts /overlay/upper/etc/config/dhcp
	#procd_add_jail_mount_rw /tmp/hosts/ /tmp/odhcpd.leases /tmp/dhcp_uci/dhcp
	procd_close_instance
}

reload_service() {
	mkdir -p /tmp/dhcp_uci
	cat /etc/config/dhcp > /tmp/dhcp_uci/dhcp
	chmod 750 /tmp/dhcp_uci
	chmod 640 /tmp/dhcp_uci/dhcp
	chown -R sscript:odhcpd /tmp/dhcp_uci
	procd_send_signal odhcpd
}

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

