#!/bin/sh /etc/rc.common

START=90
STOP=90

USE_PROCD=1

PROG=/opt/intel/usr/sbin/qosd

export PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin
export LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}

start_service() {
	/etc/qos/uci2dcf.sh						#Parse UCI to generate daemon config file

	procd_open_instance qosd
	procd_set_param user qosd
	procd_set_param capabilities /usr/share/capabilities/qos_cap.json
	procd_set_param command	$PROG
	procd_set_param env PATH=${PATH} LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
	procd_close_instance
}

reload_service() {
	/etc/qos/uci2dcf.sh						#Parse UCI to generate daemon config file
	procd_send_signal qos qosd SIGUSR1		#Send signal to daemon to read daemon config file
}

service_triggers() {
	 procd_add_reload_trigger qos
}

