#!/bin/sh /etc/rc.common

USE_PROCD=1
START=18

no_framework_mode()
{
	local _isframeworkmode="$(grep "no_framework=1" /proc/cmdline)"
	[ -n "$_isframeworkmode" ]
}

start_service() {
	no_framework_mode && return
	procd_open_instance
	procd_set_param command servd
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param user servd
	procd_set_param capabilities /usr/share/capabilities/servd_cap.json
	procd_set_param pseudofs_acl /usr/share/pseudofs_acl/servd_pseudofs_acl.json
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

