#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=10
USE_PROCD=1

validate_system_section()
{
	uci_load_validate system system "$1" "$2" \
		'hostname:string:OpenWrt' \
		'conloglevel:uinteger' \
		'buffersize:uinteger' \
		'timezone:string:UTC' \
		'zonename:string'
}

system_config() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	ubus call system hostname '{ "value": "'$hostname'" }'
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}
	mkdir -p /tmp/timezone
	echo "$timezone" > /tmp/timezone/TZ
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && \
		ln -sf "/usr/share/zoneinfo/$zonename" /tmp/localtime && rm -f /tmp/timezone/TZ

	# apply timezone to kernel
	hwclock -u --systz
	
	#Set the WDT timeout 
	#ubus call system watchdog '{ "timeout" : 120, "frequency" : 60 }'
	ubus call system watchdog '{ "magicclose": true, "stop": true }'
}

reload_service() {
	config_load system
	config_foreach validate_system_section system system_config
}

service_triggers()
{
	procd_add_reload_trigger "system"
	procd_add_validation validate_system_section
}

start_service() {
	reload_service
}
