#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10
BIN=/opt/intel/usr/sbin/wsd

start_service() {
        procd_open_instance
        procd_set_param command $BIN
        procd_set_param env LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param user wsd
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

