#!/bin/sh
# Copyright (c) 2020 - 2021 MaxLinear, Inc.
# Copyright (c) 2019 - 2020 Intel Corporation

. /lib/pon.sh

count_ptp_xgmac_clk() {
	local cnt
	cnt=`grep XGMAC /sys/class/ptp/ptp*/clock_name |wc -l`
	echo $cnt
}

# Update config only on PRX systems
pon_is_10g_platform || return 0

# the names are fixed on PRX
uci set ieee_1588.tod2phc.xpectd_mc_name='PONIP TOD 1'
uci set ieee_1588.tod2phc.xpectd_sc_name='XGMAC 2'
uci set ieee_1588.tod2ktimer.xpectd_phc_name='PONIP TOD 1'

# currently fixed, until concept for multi-lan setup is defined (see below)
uci set ieee_1588.ptp_sync.interface=$(pon_default_lct_get)

pon_clk=$(count_ptp_xgmac_clk)
xgmac_clk=$(expr $pon_clk - 1)

uci set ieee_1588.tod2phc.slave_clock=ptp$xgmac_clk
uci set ieee_1588.tod2phc.master_clock=ptp$pon_clk
uci set ieee_1588.tod2ktimer.phc_clk=ptp$pon_clk

# Sync_offset between PONIP TOD and XGMAC2 PTP wall clocks
uci set ieee_1588.tod2phc.sync_offset='8'
