### Overlay whitelist  ######
# Format: <file path>    [d]
#############################

/securestore
/securestore_b
/etc/board.json
/etc/dropbear/dropbear_rsa_host_key
/etc/passwd
/etc/passwd-
/etc/group
/etc/group-
/etc/hosts
/etc/certs/lighttpd/lighttpd.pem
/etc/certs/vsftpd/vsftpd.pem
/etc/shadow
/etc/shadow-
/etc/urandom.seed
# UCI defaults will be deleted run-time.
/etc/uci-defaults/ppa				d
/etc/uci-defaults/13_fix_group_user		d
/etc/uci-defaults/10_migrate-shadow		d
/etc/uci-defaults/11_migrate-sysctl		d
/etc/uci-defaults/30_luci-theme-openwrt		d
/etc/uci-defaults/12_network-generate-ula	d
/etc/uci-defaults/ethernet			d
/etc/uci-defaults/users				d
/etc/uci-defaults/99-miniupnpd			d
/etc/uci-defaults/system			d
/etc/uci-defaults/uhttpd			d
/etc/uci-defaults/firewall			d
/etc/uci-defaults/30_luci-theme-bootstrap	d
/etc/uci-defaults/20_migrate-feeds		d
/etc/uci-defaults/lxc-unprivileged		d
/etc/uci-defaults/99-prplmesh-update-config.sh	d
/etc/uci-defaults/10-fstab			d
/etc/uci-defaults/wireless			d
/etc/uci-defaults/odhcpd.defaults		d
/etc/uci-defaults/uboot_cfg_bridgeip		d
# UCI files
/etc/config/tod
/etc/config/minidlna
/etc/config/serdes
/etc/config/optic
/etc/config/gpon
/etc/config/omci
/etc/config/ppa
/etc/config/dhcp
/etc/config/rpcd
/etc/config/network
/etc/config/dropbear
/etc/config/ntpclient
/etc/config/ethernet
/etc/config/gaccess
/etc/config/ipsec
/etc/config/upnpd
/etc/config/system
/etc/config/firewall
/etc/config/qos
/etc/config/devm
/etc/config/mcast
/etc/config/wireless
/etc/wifi_max_vap_count
/etc/config/voip
/etc/config/voip_diag
/etc/config/mwan3
/etc/config/dsl
/etc/config/ftp
/etc/config/lighttpd
/etc/config/lxc-auto
/etc/config/minissdpd
/etc/config/stunnel
/etc/config/prplmesh
/etc/ethers
/etc/ipsec.conf
/etc/strongswan.conf
/etc/ipsec.secrets
/etc/resolv.conf
/opt/intel/csd/etc/csdswap
/opt/intel/csd/etc/AliasCnt.txt
/opt/intel/csd/config/.run-data-swp.xml
/opt/intel/csd/config/.run-data.xml
/opt/intel/csd/config/.run-control.xml
/opt/intel/csd/config/.config_upgrade
/opt/intel/etc/.certchk
/opt/intel/etc/debug_level
/opt/intel/etc/devmd/vendor_data
/opt/intel/servd/etc/nextmac.conf
/opt/intel/servd/etc/.resv-mac.conf
/opt/intel/servd/etc/servd.conf
/opt/intel/etc/usermgmt/vsftpd.users
/opt/intel/etc/lighttpd/lighttpd.attempts
/opt/intel/etc/usermgmt/lighttpd.user
/.rnd
/opt/intel/etc/upgrade/.upg_state_file
/opt/intel/etc/upgrade/.flash_cnt_chk
/opt/intel/wave/conf/ch_dfs_state.db
/opt/intel/wave/conf/ch_dfs_state_low.db
/opt/intel/wave/conf/ch_dfs_state_high.db
# LxC specifics
/run
/usr/bin/newuidmap
/usr/bin/newgidmap
/usr/lib/lxc/lxc-user-nic
/etc/subuid
/etc/subuid-
/etc/subgid
/etc/subgid-
/etc/lxc/lxc-usernet
# for VRX618 debug mode only
/opt/intel/bin/vrx618_startup_user_cfg.sh
/opt/intel/bin/vrx618_startup_user_cfg_co.sh
