#!/bin/sh /etc/rc.common

START=90
STOP=90

USE_PROCD=1

PROG=/opt/intel/usr/sbin/qosd

export PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin
export LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}

start_service() {
	procd_open_instance qosd
	procd_set_param user
	procd_set_param command	$PROG
	procd_set_param env PATH=${PATH} LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
	procd_close_instance
}

reload_service() {
	procd_send_signal qos qosd SIGUSR1
}

service_triggers() {
	 procd_add_reload_trigger qos
}
