#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

APPBINARY=/usr/sbin/netdata
CONFIGFILE=/etc/netdata/netdata.conf

start_service() {
	procd_open_instance
	procd_set_param command $APPBINARY -nd -c $CONFIGFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_open_data
	json_add_array firewall
	json_add_object ""
	json_add_string type rule
	json_add_string src "lan"
	json_add_string proto tcp
	json_add_string dest_port "19999"
	json_add_string target ACCEPT
	json_close_object
	procd_close_data
	procd_close_instance
}

service_started() {
	procd_set_config_changed firewall
}

stop_service() {
	procd_set_config_changed firewall
}
