#!/bin/sh

#Create the fw_env.config file dynamically for fw_printenv/fw_setenv utility
fw_env_config() {
	f_fw_env_config="/etc/fw_env.config"

	if [ ! -f "$f_fw_env_config" ]; then
		if [ -d "/sys/class/ubi/ubi0" ]; then
			echo "# Configuration file for fw_printenv/fw_setenv utility." > $f_fw_env_config
			echo "# device name   Device offset   Env. size   Flash sector size  Number of sectors" >> $f_fw_env_config
			for U in 'ubootconfigA' 'ubootconfigB' ;
			do
				dev_name=$(grep "$U" "/proc/mtd" | cut -d: -f1)
				env_size=$(printf "0x%X" $(cat /sys/devices/soc0/e0f00000.ebu_nand/mtd/$dev_name/size))
				f_sec_size=$(cat /sys/devices/soc0/e0f00000.ebu_nand/mtd/$dev_name/mtdblock$(echo "$dev_name" | cut -c 4)/size)
				f_sec_size=$(printf "0x%X" `expr "$f_sec_size" \* 256`)
				no_of_sec=$((env_size / f_sec_size))
				echo "" >> $f_fw_env_config
				echo "# MTD device name   Device offset   Env. size   Flash sector size  Number of sectors" >> $f_fw_env_config
				echo "/dev/$dev_name      0x00            $env_size   $f_sec_size        $no_of_sec" >> $f_fw_env_config
				echo "" >> $f_fw_env_config
			done
		fi
	fi
	if [ -d "/sys/class/mmc_host/mmc0" ]; then
		dir='/sys/class/mmc_host/mmc0/mmc0:0001/block/mmcblk0'
		for U in 'env_a' 'env_b' ;
		do
			f_uboot_conf=$(find "$dir"  -type f | xargs grep -l "$U")
			dev_name=$(grep "DEVNAME" "$f_uboot_conf" | cut -d= -f2)
			env_size=0
			cur_env_size=0
			[ -b /dev/$dev_name ] && {
				env_size=$(printf "0x%X" `expr $(cat "$dir/$dev_name/size" | cut -d= -f1) \* 512`)
			}
			[ ! -b /dev/$dev_name -o $env_size -eq 0 ] && {
				echo "Error: wrong device $dev_name or env size $env_size" > /dev/console
				continue;
			}
			if [ -f "$f_fw_env_config" ]; then
				cur_env_size="$(grep $dev_name /etc/fw_env.config | awk '{print $3}')"
			fi
			if [ -z "$cur_env_size" ] || [ $env_size != $cur_env_size ]; then
				if [ $U == "env_a" ]; then
					echo "# Configuration file for fw_(printenv/setenv) utility." > $f_fw_env_config
					echo "# device name   Device offset   Env. size   Flash sector size" >> $f_fw_env_config
				fi;
				echo "" >> $f_fw_env_config
				echo "/dev/$dev_name      0x00            $env_size" >> $f_fw_env_config
				echo "" >> $f_fw_env_config
			fi
		done
	fi
}

boot_hook_add preinit_main fw_env_config
