#!/bin/sh
#
# Copyright © 2017 OpenWrt.org
#

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

board="$(cat /tmp/sysinfo/board_name)" 2>/dev/null
wan_ifname="$(cat /proc/device-tree/wan/ifname)" 2>/dev/null

case "$board" in
pc-engines-apu|pc-engines-apu2)
	ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
	;;
traverse-technologies-geos)
	ucidef_set_interface_lan "eth0 eth1"
	ucidef_add_atm_bridge "0" "35" "llc" "bridged"
	ucidef_set_interface_wan "nas0" "dhcp"
	macaddr="$(cat /sys/class/net/eth0/address)" 2>/dev/null
	[ -n "$macaddr" ] && ucidef_set_interface_macaddr "wan" "$macaddr"
	;;
mxl,lgm|mxl,osp-tb341|mxl,osp-tb341-v2)
	ucidef_set_interface_lan "eth0_1 eth0_2 eth0_3 eth0_4 eth0_5"
	ucidef_set_interface_wan "$wan_ifname" "dhcp"
	;;

esac
board_config_flush

exit 0
