#!/bin/sh

file_name="/tmp/servd/servd_all_init_done"

# Update UCI and fix permissions
uci commit
chown rpcd:rpcd /etc/config/*
chmod 640 /etc/config/*
chown rpcd:rpcd -R /tmp/.uci
chmod 700 /tmp/.uci
chmod 600 /tmp/.uci/*

# start daemons
/etc/init.d/log start
/etc/init.d/rpcd start
/etc/init.d/csd start
/etc/init.d/polld start
/etc/init.d/servd start

# check servd all init done
index=0
while [ $index -lt 60 ]; do
	if [ -f "$file_name" ]; then
		rm -f "$file_name"
		break
	fi
	sleep 1
	index=$(( index + 1 ))
done
