# OpenCryptoki strength example corresponding to NIST recommendations
# See https://www.keylength.com/en/4/
# Move/copy to /etc/opencryptoki/strength.conf to use it with opencryptoki.
# Then chown it to root:pkcs11 and chmod it to 0640.

version strength-0

strength 112 {
         MOD_EXP   =  2048
         ECC       =   224
         SYMMETRIC =   112
         digest    =   224
         signature =   112
}
