#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 MaxLinear, Inc.

. /lib/functions/uci-defaults.sh


migrate_uni_conf() {
	local uni=$1
	shift

	if ! uci -q get network.$uni ; then
		return 0;
	fi

	uci set omci.$uni=device
	uci set omci.$uni.name=$(uci -q get network.$uni.name)
	uci set omci.$uni.multicast_name=$(uci -q get network.$uni.multicast_name)
	uci set omci.$uni.broadcast_name=$(uci -q get network.$uni.broadcast_name)
	uci set omci.$uni.macaddr=$(uci -q get network.$uni.macaddr)
	uci set network.$uni._comment="moved to omci configuration, keept here for backwards compatibility with PON SDK 1.18 and older"
}

# Migrate uni and veip configuration to omci uci file, needed since PON SDK 1.19
for dev in uni1 uni2 veip1 veip2 veip3 veip4; do
	migrate_uni_conf $dev
done

# Migrate vlan_forwarding option to omci uci file, needed since PON SDK 1.19
if uci -q get ponnetwork.common.vlan_forwarding ; then
	uci set omci.net.vlan_forwarding=$(uci -q get ponnetwork.common.vlan_forwarding)
	uci set ponnetwork.common._comment="moved to omci configuration, keept here for backwards compatibility with PON SDK 1.18 and older"
fi
