#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021-2022 Maxlinear Inc.

# Prevent creation of DS priority queues for UNI and VEIP interface
disable_ds_pq() {
	uci set omci.net=omci
	uci set omci.net.no_ds_prio_queues=1
}

# Check if device for HGU / routing is present
if ip link show VUNI0_0 >/dev/null 2>&1; then
	disable_ds_pq
fi
