#!/bin/sh
[ "$ACTION" = add ] || exit

# take lock to avoid multiple running instances of script.
exec 512>/var/lock/rfs.lock
flock 512 || exit 1

dir="/sys/class/net/"
lpdev=$(printf "%s%s" "$dir" "lpdev0")

max_rx_q=64

set_val() {
	local file="$1"
	local val="$2"
	echo "$val" > "$file"
}

rps_sock_flow_entries="$(cat /etc/sysctl.d/prpl_sysctl.conf | grep rps_sock_flow_entries | cut -d = -f2-3)"
[ "$rps_sock_flow_entries" == 0 ] && exit

dev=$(printf "%s%s" "$dir" "$INTERFACE")
[ -d "$dev" ] || exit

# ignore virtual interfaces except litepath
[ "$dev" == "$lpdev" ] || \
[[ -n "$(ls "${dev}/" | grep '^lower_')" ] && exit ] && \
[[ -d "${dev}/device" ] || exit ]
    # apply rfs to lpdev and base interfaces.
    for q in ${dev}/queues/rx-*; do
      set_val "$q/rps_flow_cnt" $(($rps_sock_flow_entries / $max_rx_q))
    done

