#!/bin/bash

prpl_reset()
{
os_name=$(grep '^NAME=' /etc/os-release | cut -d'=' -f2- | tr -d '"')

if [ "$os_name" = "prplOS" ]; then
        rm -rf /etc/rc.button/reset
        ln -s /etc/rc.button/reset-prpl /etc/rc.button/reset
fi
}
boot_hook_add preinit_main prpl_reset

