#!/bin/sh

[ -n "$1" ] && {
	case "$1" in
		backup) backup=1;
		;;
		restore) restore=1;
        esac
}

[ -n "$backup" ] && {
	umask 0022
	cp -f /etc/config/samba /tmp/upgrade_uci/samba
	cp -f /etc/config/ipsec /tmp/upgrade_uci/ipsec
	chmod 644 /tmp/upgrade_uci/*
	exit;
}

[ -n "$restore" ] && {
        umask 0022
        cp -f /tmp/upgrade_uci/samba /etc/config/samba
        cp -f /tmp/upgrade_uci/ipsec /etc/config/ipsec
        exit;
}

