#!/bin/sh

# Copyright (C) 2009 OpenWrt.org
# Copyright (C) 2014 lantiq.com
# Copyright (C) 2018 - 2020 Intel Corporation

. $IPKG_INSTROOT/lib/pon.sh

file="/etc/fw_env.config"

fw_env_create() {
	# TODO: Extend to read from /proc/mtd
	case $(pon_board_name) in
	*)
		echo "# MTD device name;Device offset;Env. size;Flash sector size" > $file
		echo "# board: $(pon_board_name)" >> $file
		echo "/dev/mtd1 0x0 0x4000 0x00020000" >> $file
		echo "/dev/mtd2 0x0 0x4000 0x00020000" >> $file
		return
	esac

}

fw_env_create
