#!/bin/sh
#
# Copyright (C) 2020 Intel Corporation
#

if [ -f $IPKG_INSTROOT/lib/pon.sh ]; then
	. $IPKG_INSTROOT/lib/pon.sh
fi

case $(pon_board_name) in
prx126-sfp-pon)
	# Disable Dying Gasp in SFP+ boards because of not working HW design
	uci set optic.common.dg_dis=1
	;;
esac
