#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 MaxLinear, Inc.
# Copyright (C) 2020 Intel Corporation.

touch /etc/config/omci

# Check if device for HGU / routing is present
if ip link show VUNI0_0 >/dev/null 2>&1; then
	uci set omci.veip1=device
	uci set omci.veip1.name="VUNI0_0"
	uci set omci.veip1.multicast_name="VUNI0_1"
	uci set omci.veip1.broadcast_name="VUNI0_2"
	uci -q set ppa.VANI0=interface
	uci -q set ppa.VANI0.alias="VANI0"
	ifnames=$(uci -q get ppa.wan.ifname)
	uci -q set ppa.wan.ifname="$ifnames VANI0"
	true # in case the ppa config file does not exist
else
	uci set omci.veip1=device
	uci set omci.veip1.name="eth0_0"
	uci set omci.veip1.multicast_name="eth0_0_2"
	uci set omci.veip1.broadcast_name="eth0_0_3"
fi
