#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10


start_service() {
        #commands to launch dwpald
        procd_open_instance
        procd_set_param user root
        procd_set_param capabilities /usr/share/capabilities/netifd_cap.json
        procd_set_param command dwpald
        procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
        procd_set_param respawn ${respawn_retry:-0}
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
