#!/bin/sh

USERNAME=$3

cd $HOME/

PPID_VAL=`sh -c 'echo $PPID'`

if [ -n "$USERNAME" ]; then
        printf '\n\033[42mCreating cgroup hierarchy\033[m\n\n' &&
        for d in /sys/fs/cgroup/*; do
               echo $PPID_VAL > $d/$USERNAME/tasks
        done
fi

lxc-start -n $1 -P $2
