#!/bin/sh
if [ "$ACTION" = "ifup" ]; then
{
	proto=$(uci get network.$INTERFACE.proto)
	[ "$proto" == "gre" ] || [ "$proto" == "grev6" ] && {
		tunipaddr=$(uci get network.$INTERFACE.tunipaddr)
		tunnetmask=$(uci get network.$INTERFACE.tunnetmask)
		[ "$proto" == "grev6" ] && {
			ip addr add $tunipaddr dev gre6-$INTERFACE
			ip route add $tunnetmask dev gre6-$INTERFACEi
			ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -I INPUT -p gre -j ACCEPT"}'
			ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -I FORWARD -p gre -j ACCEPT"}'
			ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -I OUTPUT  -p gre -j ACCEPT"}'
		} || {

			prefix=`echo $tunnetmask | awk '
			function count1s(N){
			    c = 0
			    for(i=0; i<8; ++i) if(and(2**i, N)) ++c
			    return c
			}
			function subnetmaskToPrefix(subnetmask) {
			    split(subnetmask, v, ".")
			    return count1s(v[1]) + count1s(v[2]) + count1s(v[3]) + count1s(v[4])
			}
			{
			    print("/" subnetmaskToPrefix($1))
			}'`

			network=`echo $tunipaddr $tunnetmask | awk '
			
			function ip2int(ip) {
			    ret = 0
			    n=split(ip,a,"\.")
			    for (x=1;x<=n;x++) {
			        ret=or(lshift(ret,8),a[x])
			    }
			    return ret
			}
			function int2ip(ip,ret,x) {
			    ret=and(ip,255)
			    ip=rshift(ip,8)
			    for(x=0;x<3;x++){
			        ret=and(ip,255)"."ret
			        ip=rshift(ip,8)
			    }
			    return ret
			}
			{
			ipaddr=ip2int($1)
			netmask=ip2int($2)
			print(int2ip(and(ipaddr,netmask)))
			}'`

				ip addr add $tunipaddr dev gre4-$INTERFACE
				ip route add $network$prefix dev gre4-$INTERFACE
				ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -I INPUT -p gre -j ACCEPT"}'
				ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -I FORWARD -p gre -j ACCEPT"}'
				ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -I OUTPUT  -p gre -j ACCEPT"}'
		}
	}
}
elif [ "$ACTION" = "ifdown" ]; then
{
	if [ "${INTERFACE::3}" = "gre" ]; then
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -D INPUT -p gre -j ACCEPT"}'
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -D FORWARD -p gre -j ACCEPT"}'
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"ip6tables -D OUTPUT  -p gre -j ACCEPT"}'
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -D INPUT -p gre -j ACCEPT"}'
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -D FORWARD -p gre -j ACCEPT"}'
		ubus call firewalld notify_netifd_update '{"add_gre_rule":"iptables -D OUTPUT  -p gre -j ACCEPT"}'
	fi

}
fi
