#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
PROCD_DEBUG=1
PROG=/opt/intel/bin/sys_eth

start_service() {
        procd_open_instance
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
        procd_set_param command $PROG -r
        procd_set_param user syseth
        procd_set_param pseudofs_acl /usr/share/pseudofs_acl/syseth_pseudofs_acl.json
        procd_set_param capabilities /usr/share/capabilities/syseth_cap.json
        procd_close_instance
}
