#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org

START=40

boot() {
        timeout=10

        while [ ! -e /tmp/blockd/fstab ]; do
        sleep 1;
        timeout=$((timeout-1))
        if [ $timeout == 0 ]; then
        echo "/tmp/blockd/fstab file is not created after 10 sec wait time.."
        break;
        fi
        done

        /sbin/block mount
}

start() {
        return 0
}

restart() {
        return 0
}

stop() {
        /sbin/block umount
}
