#!/bin/sh /etc/rc.common

START=90
STOP=90

USE_PROCD=1

PROG=/opt/intel/usr/sbin/qosd

export PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin
export LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}

#Add redirection switch rules for port i 15 (ETH WAN)
add_switch_rules() {
	i=0
	while [ $i -lt 16 ];
	do
		switch_cli dev=1 GSW_QOS_QUEUE_PORT_SET nPortId=15  nTrafficClassId=$i nQueueId=30 bRedirectionBypass=0 nRedirectPortId=0
		switch_cli dev=1 GSW_QOS_QUEUE_PORT_SET nPortId=15  nTrafficClassId=$i nQueueId=31 bRedirectionBypass=1 nRedirectPortId=15
		i=$(($i+1))
	done
}

start_service() {
	add_switch_rules
	mkdir /tmp/qosd/
	/etc/qos/uci2dcf.sh						#Parse UCI to generate daemon config file

	procd_open_instance qosd
	procd_set_param user
#	procd_set_param capabilities /usr/share/capabilities/qos_cap.json
	procd_set_param command	$PROG
	procd_set_param env PATH=${PATH} LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
	procd_close_instance
}

reload_service() {
	/etc/qos/uci2dcf.sh						#Parse UCI to generate daemon config file
	procd_send_signal qos qosd SIGUSR1		#Send signal to daemon to read daemon config file
}

service_triggers() {
	 procd_add_reload_trigger qos
}
