#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=90

USE_PROCD=1
PROG=/usr/sbin/ppacmd

start_service() {
		procd_open_instance
		procd_set_param command "$PROG" init
		procd_close_instance
}

