#!/bin/sh
#
# Copyright © 2017 OpenWrt.org
#

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

board="$(cat /tmp/sysinfo/board_name)" 2>/dev/null

case "$board" in
pc-engines-apu|pc-engines-apu2)
	ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
	;;
traverse-technologies-geos)
	ucidef_set_interface_lan "eth0 eth1"
	ucidef_add_atm_bridge "0" "35" "llc" "bridged"
	ucidef_set_interface_wan "nas0" "dhcp"
	macaddr="$(cat /sys/class/net/eth0/address)" 2>/dev/null
	[ -n "$macaddr" ] && ucidef_set_interface_macaddr "wan" "$macaddr"
	;;
mxl,lgm)
	ucidef_set_interface_lan "eth0_1 eth0_2 eth0_3 eth0_4 eth0_5"
	ucidef_set_interface_wan "eth1" "dhcp"

	OUTPUT=$(cat /proc/cmdline)
	INDEX=$(awk -v a="$OUTPUT" -v b=ethaddr 'BEGIN{print index(a,b)}')
	INDEX="$((INDEX-1))"
	ETHVAR=${OUTPUT:INDEX:25}
	macaddr=$(echo "$ETHVAR" | cut -d= -f2)

	[ -n "$macaddr" ] && ucidef_set_interface_macaddr "wan" "$macaddr"
	;;

esac
board_config_flush

exit 0
