#!/bin/sh

add_sys_users() {
	#local user_list="nwk syseth wsd rpcd logd lighttpd dbgrp"
	local user_name;

	for user_name in $user_list; do
		groupadd $user_name -r 2>/dev/null && {
			adduser $user_name -G $user_name -D -H -S 2>/dev/null
		}
	done
	chmod 777 /var/run
	chmod 777 /var/state
	mkdir -p /tmp/upgrade /tmp/upgrade_uci /tmp/backup_restore
	touch /tmp/backup_restore/db-backup.tar.gz
	touch /tmp/upgrade_uci/samba
	touch /tmp/upgrade_uci/ipsec
	chmod 755 /tmp/upgrade_uci
	chmod 770 /tmp/upgrade
	chmod 770 /tmp/backup_restore
	chmod 770 /tmp/backup_restore/db-backup.tar.gz
	chmod 644 /tmp/upgrade_uci/samba /tmp/upgrade_uci/ipsec
	chown lighttpd:dbgrp /tmp/backup_restore /tmp/backup_restore/db-backup.tar.gz 2>/dev/null
	chown rpcd:rpcd /tmp/upgrade_uci /tmp/upgrade_uci/samba /tmp/upgrade_uci/ipsec 2>/dev/null
}

boot_hook_add preinit_main add_sys_users
