#!/bin/sh

. /lib/functions.sh

[ "$ACTION" != "ifup" -o "$INTERFACE" != "lan" ] && exit 0

add_to_bridge() {

	local section="$1"

	config_get ifname $section ifname
	[ -n $ifname ] && {

		[ -d "/sys/class/net/$ifname" ] && {
			brctl addif $DEVICE $ifname
			logger Adding interface $ifname to bridge $DEVICE
		}
	}
}

add_to_bridge_pwhm_enabled() {

	apidx=1

	apmax="$(ubus list | grep -E "^WiFi\.AccessPoint\.[0-9]+\.?$" | wc -l)"

	while [ $apidx -le $apmax ]
	do

		ifname="$(ubus call WiFi.AccessPoint.$apidx _get | sed -n 's/.*"Alias": "\(.*\)",/\1/p' | tr -d ' ')"
		brname="$(ubus call WiFi.AccessPoint.$apidx _get | sed -n 's/.*"BridgeInterface": "\(.*\)",/\1/p' | tr -d ' ')"

		if [ "${brname}" = "$DEVICE" ]; then

			[ -d "/sys/class/net/$ifname" ] && {
				brctl addif $DEVICE $ifname
				logger Adding interface $ifname to bridge $DEVICE
			}
		fi

		apidx=$(( $apidx + 1 ))

	done
}

if [ -s /etc/config/wireless ]
then
	config_load wireless
	config_foreach add_to_bridge wifi-iface
else
    add_to_bridge_pwhm_enabled
fi

exit 0
