#!/bin/sh

lxc_user_setup()
{
	local i
	mkdir -p /tmp/run
	ln -s /tmp/run /run

	mkdir -p /home
	useradd -m $1
	touch /etc/subuid
	touch /etc/subgid
	usermod --add-subuids 20000-21000 root
	usermod --add-subgids 20000-21000 root
	usermod --add-subuids 20000-21000 $1
	usermod --add-subgids 20000-21000 $1
	echo "$1 veth br-lan 10 " >  /etc/lxc/lxc-usernet
	#chmod 4755 /usr/bin/newuidmap
	#chmod 4755 /usr/bin/newgidmap
	chmod 4755 /usr/libexec/lxc/lxc-user-nic

}

lxc_user_setup lxcuser
