#!/bin/sh

# uboot_env_br_ip file will be used to store the bridge IP from uboot env. It will
# be used by network SL to update the bridge IP address and delete this file.
uboot_ipaddr_file="/tmp/uboot_env_br_ip"

do_get_uboot_ipaddr() {
	# get the uboot ipaddr
	/usr/sbin/uboot_env --get --name ipaddr > $uboot_ipaddr_file
}

do_get_uboot_ipaddr
