#!/bin/sh

container_name="$1"
container_user="$2"
shift; shift;

cd $HOME/

PPID_VAL=`sh -c 'echo $PPID'`

if [ -n "$container_user" ]; then
	echo "Creating cgroup hierarchy";
	for d in /sys/fs/cgroup/*; do
		echo $PPID_VAL > $d/$container_user/tasks
	done
fi

rm -f /tmp/lxc-${container_name}.log

lxc-start $@ --logfile /tmp/lxc-${container_name}.log
