listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_root=/mnt/usb/
secure_chroot_dir=/mnt/
allow_writeable_chroot=YES
seccomp_sandbox=NO
local_enable=YES
write_enable=YES
chown_uploads=YES
chown_username=ftp
local_umask=022
check_shell=NO
nopriv_user=ftp
session_support=NO
userlist_deny=NO
userlist_enable=YES
userlist_file=/opt/intel/etc/usermgmt/vsftpd.users
ssl_enable=NO
require_ssl_reuse=NO
force_local_data_ssl=NO
force_local_logins_ssl=NO
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
ssl_ciphers=HIGH
rsa_cert_file=/etc/certs/vsftpd/vsftpd.pem
connect_from_port_20=YES
pasv_enable=YES
pasv_promiscuous=YES
pasv_min_port=33300
pasv_max_port=33350
chroot_local_user=NO
use_sendfile=YES
