/******************************************************************************** 

  Copyright © 2020 MaxLinear, Inc.
  Copyright (C) 2017-2018 Intel Corporation 
  Lantiq Beteiligungs-GmbH & Co. KG 
  Lilienthalstrasse 15, 85579 Neubiberg, Germany  

  For licensing information, see the file 'LICENSE' in the root folder of 
  this software module. 

********************************************************************************/

/* Do Not modify this file manually, This file will be updated with ErrorStrings by script */

#include "ugw_proto.h"
#include "ugw_notify_defs.h"

char *getNIDString(int nErrCode)
{
        switch(nErrCode) {
		case 	NOTIFY_DEFAULT_LAN_UP: return "NOTIFY_DEFAULT_LAN_UP";
		case 	NOTIFY_DEFAULT_LAN_DOWN: return "NOTIFY_DEFAULT_LAN_DOWN";
		case 	NOTIFY_DEFAULT_WAN_UP: return "NOTIFY_DEFAULT_WAN_UP";
		case 	NOTIFY_DEFAULT_WAN_DOWN: return "NOTIFY_DEFAULT_WAN_DOWN";
		case 	NOTIFY_DEFAULT_DSL_UP: return "NOTIFY_DEFAULT_DSL_UP";
		case 	NOTIFY_DEFAULT_DSL_DOWN: return "NOTIFY_DEFAULT_DSL_DOWN";
		case 	NOTIFY_DEFAULT_WWAN_UP: return "NOTIFY_DEFAULT_WWAN_UP";
		case 	NOTIFY_DEFAULT_WWAN_DOWN: return "NOTIFY_DEFAULT_WWAN_DOWN";
		case 	NOTIFY_FIRMWARE_UPGRADE_PRE: return "NOTIFY_FIRMWARE_UPGRADE_PRE";
		case 	NOTIFY_NTP_SYNC: return "NOTIFY_NTP_SYNC";
		case 	NOTIFY_NTP_SYNC_ERROR: return "NOTIFY_NTP_SYNC_ERROR";
		case 	NOTIFY_INTERFACE_UP: return "NOTIFY_INTERFACE_UP";
		case 	NOTIFY_INTERFACE_DOWN: return "NOTIFY_INTERFACE_DOWN";
		case 	NOTIFY_INTERFACE_REGISTRATION: return "NOTIFY_INTERFACE_REGISTRATION";
		case 	NOTIFY_INTERFACE_DEREGISTRATION: return "NOTIFY_INTERFACE_DEREGISTRATION";
		case 	NOTIFY_WIFI_RADIO_STATUS_CHANGE: return "NOTIFY_WIFI_RADIO_STATUS_CHANGE";
		case 	NOTIFY_WIFI_SSID_STATUS_CHANGE: return "NOTIFY_WIFI_SSID_STATUS_CHANGE";
		case 	NOTIFY_WIFI_DEVICE_ASSOCIATED: return "NOTIFY_WIFI_DEVICE_ASSOCIATED";
		case 	NOTIFY_WIFI_WPS_ACTION: return "NOTIFY_WIFI_WPS_ACTION";
		case 	NOTIFY_WIFI_WPS_NEW_AP_SETTINGS: return "NOTIFY_WIFI_WPS_NEW_AP_SETTINGS";
		case 	NOTIFY_WIFI_WPS_STATUS: return "NOTIFY_WIFI_WPS_STATUS";
		case 	NOTIFY_WIFI_UPDATE_PARAM: return "NOTIFY_WIFI_UPDATE_PARAM";
		case 	NOTIFY_DSL_INTERFACE_STATUS: return "NOTIFY_DSL_INTERFACE_STATUS";
		case 	NOTIFY_DSL_DATARATE_STATUS: return "NOTIFY_DSL_DATARATE_STATUS";
		case 	NOTIFY_DSL_DATARATE_STATUS_US: return "NOTIFY_DSL_DATARATE_STATUS_US";
		case 	NOTIFY_IPv6_PREFIX_UP: return "NOTIFY_IPv6_PREFIX_UP";
		case 	NOTIFY_IPv6_PREFIX_DOWN: return "NOTIFY_IPv6_PREFIX_DOWN";
		case 	NOTIFY_IPv6_RA_RECEIVED: return "NOTIFY_IPv6_RA_RECEIVED";
		case 	NOTIFY_DSLITE_STATIC_UP: return "NOTIFY_DSLITE_STATIC_UP";
		case 	NOTIFY_DSLITE_DYNAMIC_UP: return "NOTIFY_DSLITE_DYNAMIC_UP";
		case 	NOTIFY_INTERFACE_STATUS: return "NOTIFY_INTERFACE_STATUS";
		case 	NOTIFY_IPADDRESS_CHANGE: return "NOTIFY_IPADDRESS_CHANGE";
		case 	NOTIFY_ARP_CHANGE: return "NOTIFY_ARP_CHANGE";
		case 	NOTIFY_ROUTE_CHANGE: return "NOTIFY_ROUTE_CHANGE";
		case 	NOTIFY_DEFAULT_ROUTE_CHANGE: return "NOTIFY_DEFAULT_ROUTE_CHANGE";
		case 	NOTIFY_LAN_BR_INTERFACE_UP: return "NOTIFY_LAN_BR_INTERFACE_UP";
		case 	NOTIFY_LAN_BR_INTERFACE_DOWN: return "NOTIFY_LAN_BR_INTERFACE_DOWN";
		case 	NOTIFY_FIREWALL_PORT_OPEN: return "NOTIFY_FIREWALL_PORT_OPEN";
		case 	NOTIFY_FIREWALL_PORT_CLOSE: return "NOTIFY_FIREWALL_PORT_CLOSE";
		case 	NOTIFY_FIREWALL_PORT_CHANGE: return "NOTIFY_FIREWALL_PORT_CHANGE";
		case 	NOTIFY_FIREWALL_LOG_START: return "NOTIFY_FIREWALL_LOG_START";
		case 	NOTIFY_FIREWALL_LOG_STOP: return "NOTIFY_FIREWALL_LOG_STOP";
		case 	NOTIFY_FIREWALL_DELETE_OBJECT: return "NOTIFY_FIREWALL_DELETE_OBJECT";
		case 	NOTIFY_FW_VOIP_ALG_ENABLED: return "NOTIFY_FW_VOIP_ALG_ENABLED";
		case 	NOTIFY_FW_VOIP_ALG_DISABLED: return "NOTIFY_FW_VOIP_ALG_DISABLED";
		case 	NOTIFY_FW_FTP_ALG_ENABLED: return "NOTIFY_FW_FTP_ALG_ENABLED";
		case 	NOTIFY_FW_FTP_ALG_DISABLED: return "NOTIFY_FW_FTP_ALG_DISABLED";
		case 	NOTIFY_FW_TFTP_ALG_ENABLED: return "NOTIFY_FW_TFTP_ALG_ENABLED";
		case 	NOTIFY_FW_TFTP_ALG_DISABLED: return "NOTIFY_FW_TFTP_ALG_DISABLED";
		case 	NOTIFY_FW_PPTP_ALG_ENABLED: return "NOTIFY_FW_PPTP_ALG_ENABLED";
		case 	NOTIFY_FW_PPTP_ALG_DISABLED: return "NOTIFY_FW_PPTP_ALG_DISABLED";
		case 	NOTIFY_FW_IPSEC_ALG_ENABLED: return "NOTIFY_FW_IPSEC_ALG_ENABLED";
		case 	NOTIFY_FW_IPSEC_ALG_DISABLED: return "NOTIFY_FW_IPSEC_ALG_DISABLED";
		case 	NOTIFY_DEFAULT_USBNET_ADD: return "NOTIFY_DEFAULT_USBNET_ADD";
		case 	NOTIFY_DEFAULT_USBNET_REMOVE: return "NOTIFY_DEFAULT_USBNET_REMOVE";
		case 	NOTIFY_WAN_ADD: return "NOTIFY_WAN_ADD";
		case 	NOTIFY_WAN_DEL: return "NOTIFY_WAN_DEL";
		case 	NOTIFY_WAN_MODIFY: return "NOTIFY_WAN_MODIFY";
		case 	NOTIFY_INTERFACE_STATUS_SLMSG: return "NOTIFY_INTERFACE_STATUS_SLMSG";
		case 	NOTIFY_IPADDRESS_CHANGE_SLMSG: return "NOTIFY_IPADDRESS_CHANGE_SLMSG";
		case 	NOTIFY_DHCP_CLIENT_UP: return "NOTIFY_DHCP_CLIENT_UP";
		case 	NOTIFY_DHCP_CLIENT_DOWN: return "NOTIFY_DHCP_CLIENT_DOWN";
		case 	NOTIFY_DHCP_DNSMASQ_DELALL: return "NOTIFY_DHCP_DNSMASQ_DELALL";
		case 	NOTIFY_IPv6_RDNSS: return "NOTIFY_IPv6_RDNSS";
		case 	NOTIFY_IPv6_DNSSL: return "NOTIFY_IPv6_DNSSL";
		case 	NOTIFY_PPP_UP: return "NOTIFY_PPP_UP";
		case 	NOTIFY_PPP_DOWN: return "NOTIFY_PPP_DOWN";
		case 	NOTIFY_DYNAMIC_6RD: return "NOTIFY_DYNAMIC_6RD";
		case 	NOTIFY_DSLITE_AFTER: return "NOTIFY_DSLITE_AFTER";
		case 	NOTIFY_DSLITE_HOSTNAME: return "NOTIFY_DSLITE_HOSTNAME";
		case 	NOTIFY_NETIFD_IPADDRESS_ADD: return "NOTIFY_NETIFD_IPADDRESS_ADD";
		case 	NOTIFY_NETIFD_IPADDRESS_REM: return "NOTIFY_NETIFD_IPADDRESS_REM";
		case 	NOTIFY_WAN_UP: return "NOTIFY_WAN_UP";
		case 	NOTIFY_WAN_DOWN: return "NOTIFY_WAN_DOWN";
		case 	NOTIFY_TEST: return "NOTIFY_TEST";
		case 	NOTIFY_QOS_ENABLED: return "NOTIFY_QOS_ENABLED";
		case 	NOTIFY_QOS_DISABLED: return "NOTIFY_QOS_DISABLED";
		case 	NOTIFY_LTE_WAN_ENABLED: return "NOTIFY_LTE_WAN_ENABLED";
		case 	NOTIFY_LTE_WAN_DISABLED: return "NOTIFY_LTE_WAN_DISABLED";
		case 	NOTIFY_SYS_UPDATE: return "NOTIFY_SYS_UPDATE";
		case 	NOTIFY_SYS_PPA_INIT: return "NOTIFY_SYS_PPA_INIT";
		case 	NOTIFY_SYS_PPA_INTF_ADD: return "NOTIFY_SYS_PPA_INTF_ADD";
		case 	NOTIFY_SYS_PPA_INTF_DEL: return "NOTIFY_SYS_PPA_INTF_DEL";
		case 	NOTIFY_SYS_PPA_ENABLE: return "NOTIFY_SYS_PPA_ENABLE";
		case 	NOTIFY_ETH_MODULE_LOAD_COMPLETE: return "NOTIFY_ETH_MODULE_LOAD_COMPLETE";
		case 	NOTIFY_ETH_BOND_INTERFACE_REGISTRATION: return "NOTIFY_ETH_BOND_INTERFACE_REGISTRATION";
		case 	NOTIFY_AUTOWAN_NETWORK_AUTOWAN_DIAGNOSTICS: return "NOTIFY_AUTOWAN_NETWORK_AUTOWAN_DIAGNOSTICS";
		case 	NOTIFY_NETWORK_AUTOWAN_AUTOWAN_STATUS: return "NOTIFY_NETWORK_AUTOWAN_AUTOWAN_STATUS";
		case 	NOTIFY_DEFAULT_WAN_CHANGE: return "NOTIFY_DEFAULT_WAN_CHANGE";
		case 	NOTIFY_DEFAULT_LAN_MODIFY: return "NOTIFY_DEFAULT_LAN_MODIFY";
		case 	NOTIFY_IPV6_NEW_PREFIX: return "NOTIFY_IPV6_NEW_PREFIX";
		case 	NOTIFY_IPV6_NEW_PREFIX_UPDATE: return "NOTIFY_IPV6_NEW_PREFIX_UPDATE";
		case 	NOTIFY_STATIC_DNS_CHANGE: return "NOTIFY_STATIC_DNS_CHANGE";
		case 	NOTIFY_TC_CHANGE: return "NOTIFY_TC_CHANGE";
		case 	NOTIFY_LOOPBACK_UP: return "NOTIFY_LOOPBACK_UP";
		case 	NOTIFY_LOOPBACK_DOWN: return "NOTIFY_LOOPBACK_DOWN";
		case 	NOTIFY_L2_IFACE_ADD: return "NOTIFY_L2_IFACE_ADD";
		case 	NOTIFY_L2_IFACE_REM: return "NOTIFY_L2_IFACE_REM";
		case 	NOTIFY_SYSLOG_VIEWER: return "NOTIFY_SYSLOG_VIEWER";
		case 	NOTIFY_BRIDGED_WAN_UP: return "NOTIFY_BRIDGED_WAN_UP";
		case 	NOTIFY_BRIDGED_WAN_DOWN: return "NOTIFY_BRIDGED_WAN_DOWN";
		case 	NOTIFY_BRIDGED_WAN_ADD: return "NOTIFY_BRIDGED_WAN_ADD";
		case 	NOTIFY_BRIDGED_WAN_DEL: return "NOTIFY_BRIDGED_WAN_DEL";
		case 	NOTIFY_FW_UPGRADE: return "NOTIFY_FW_UPGRADE";
		case 	NOTIFY_FW_UPGRADE_PRE_DL: return "NOTIFY_FW_UPGRADE_PRE_DL";
		case 	NOTIFY_FW_UPGRADE_POST_DL: return "NOTIFY_FW_UPGRADE_POST_DL";
		case 	NOTIFY_FWUPGRADE_STATUS: return "NOTIFY_FWUPGRADE_STATUS";
		case 	NOTIFY_WPS_STATUS: return "NOTIFY_WPS_STATUS";
		case 	NOTIFY_AUTOWAN_STATUS: return "NOTIFY_AUTOWAN_STATUS";
		case 	NOTIFY_ALL_INIT_COMPLETED: return "NOTIFY_ALL_INIT_COMPLETED";
		case 	NOTIFY_IFACE_DELETE: return "NOTIFY_IFACE_DELETE";
		case 	NOTIFY_VLAN_CONFIG: return "NOTIFY_VLAN_CONFIG";
		case 	NOTIFY_DSL_STATUS: return "NOTIFY_DSL_STATUS";
		case 	NOTIFY_DSL_SWITCHOVER: return "NOTIFY_DSL_SWITCHOVER";
		case 	NOTIFY_WANMODE_CHANGE: return "NOTIFY_WANMODE_CHANGE";
		case 	NOTIFY_GR909_EXE_TEST: return "NOTIFY_GR909_EXE_TEST";
		case 	NOTIFY_DECT_XRAM_TEST: return "NOTIFY_DECT_XRAM_TEST";
		case 	NOTIFY_DECT_TBR6_TEST: return "NOTIFY_DECT_TBR6_TEST";
		case 	NOTIFY_DECT_TPC_TEST: return "NOTIFY_DECT_TPC_TEST";
		case 	NOTIFY_IPV6_ADD: return "NOTIFY_IPV6_ADD";
		case 	NOTIFY_IPV6_DEL: return "NOTIFY_IPV6_DEL";
		case 	NOTIFY_UPNP_UPDATE_REQ: return "NOTIFY_UPNP_UPDATE_REQ";
		case 	NOTIFY_UPNP_ROUTE_ADD: return "NOTIFY_UPNP_ROUTE_ADD";
		case 	NOTIFY_UPNP_ROUTE_DEL: return "NOTIFY_UPNP_ROUTE_DEL";
		case 	NOTIFY_MWAN_INFO: return "NOTIFY_MWAN_INFO";
		case 	NOTIFY_MWAN_UP: return "NOTIFY_MWAN_UP";
		case 	NOTIFY_MWAN_DOWN: return "NOTIFY_MWAN_DOWN";
		case 	NOTIFY_MWAN_REQ_DEFWAN_CHANGE: return "NOTIFY_MWAN_REQ_DEFWAN_CHANGE";
		case 	NOTIFY_DECT_MODEM_RESET: return "NOTIFY_DECT_MODEM_RESET";
		case 	NOTIFY_FACTORY_RESET: return "NOTIFY_FACTORY_RESET";
		case 	NOTIFY_BRIDGE_ADD: return "NOTIFY_BRIDGE_ADD";
		case 	NOTIFY_BRIDGE_DEL: return "NOTIFY_BRIDGE_DEL";
		case 	NOTIFY_BRIDGE_MODIFY: return "NOTIFY_BRIDGE_MODIFY";
		case 	NOTIFY_BRIDGE_UP: return "NOTIFY_BRIDGE_UP";
		case 	NOTIFY_BRIDGE_DOWN: return "NOTIFY_BRIDGE_DOWN";
		case 	NOTIFY_DYNDNS_STATUS_UPDATE: return "NOTIFY_DYNDNS_STATUS_UPDATE";
		case 	NOTIFY_FORCE_DEFAULT_WAN: return "NOTIFY_FORCE_DEFAULT_WAN";
		case 	NOTIFY_TEST_FEATURE_SL1: return "NOTIFY_TEST_FEATURE_SL1";
		case 	NOTIFY_TEST_APP_SL1: return "NOTIFY_TEST_APP_SL1";
		case 	NOTIFY_USB_DEVICE_CONNECTED: return "NOTIFY_USB_DEVICE_CONNECTED";
		case 	NOTIFY_USB_DEVICE_MOUNTED: return "NOTIFY_USB_DEVICE_MOUNTED";
		case 	NOTIFY_WIFI_BRIDGE_RELOAD: return "NOTIFY_WIFI_BRIDGE_RELOAD";
		case 	NOTIFY_CONFIG_RESTORE: return "NOTIFY_CONFIG_RESTORE";
		case 	NOTIFY_FIREWALL_RULES: return "NOTIFY_FIREWALL_RULES";
		case 	NOTIFY_AUTOSENSE_DEFAULT_WAN_CHANGE: return "NOTIFY_AUTOSENSE_DEFAULT_WAN_CHANGE";
		case 	NOTIFY_AUTOSENSE_MAC_ADDRESS_CHANGE: return "NOTIFY_AUTOSENSE_MAC_ADDRESS_CHANGE";
		case 	NOTIFY_CHANGE_WAN_MODE: return "NOTIFY_CHANGE_WAN_MODE";
		case 	NOTIFY_WIFI_WPS_ENDPOINT_DONE: return "NOTIFY_WIFI_WPS_ENDPOINT_DONE";
		case    NOTIFY_TEST_WANSL: return "NOTIFY_TEST_WANSL";
		case 	__NOTIFY_DEFS_TOTAL_COUNT: return "__NOTIFY_DEFS_TOTAL_COUNT";
                default: return "Operation Failed !!";
        }
}

