#!/bin/sh
[ "$ACTION" = "add" ] || exit

NPROCS="$(grep -c "^processor.*:" /proc/cpuinfo)"
[ "$NPROCS" -gt 1 ] || exit

PROC_MASK="$(( (1 << $NPROCS) - 1 ))"

find_irq_cpu() {
	local dev="$1"
	local match="$(grep -m 1 "$dev\$" /proc/interrupts)"
	local cpu=0

	[ -n "$match" ] && {
		set -- $match
		shift
		for cur in `seq 1 $NPROCS`; do
			[ "$1" -gt 0 ] && {
				cpu=$(($cur - 1))
				break
			}
			shift
		done
	}

	echo "$cpu"
}

set_hex_val() {
	local file="$1"
	local val="$2"
	val="$(printf %x "$val")"
	[ -n "$DEBUG" ] && echo "$file = $val"
	echo "$val" > "$file"
}

# take lock to avoid multiple running instances of script.
exec 512>/var/lock/xps.lock
flock 512 || exit 1

dir="/sys/class/net/"
lpdev=$(printf "%s%s" "$dir" "lpdev0")

dev=$(printf "%s%s" "$dir" "$INTERFACE")
[ -d "$dev" ] || exit

# ignore virtual interfaces except litepath
[ "$dev" == "$lpdev" ] || \
[[ -n "$(ls "${dev}/" | grep '^lower_')" ] && exit ] && \
[[ -d "${dev}/device" ] || exit ]
	device="$(readlink "${dev}/device")"
	device="$(basename "$device")"
	irq_cpu="$(find_irq_cpu "$device")"

	idx=$(($irq_cpu + 1))
	# apply xps to lpdev and base interfaces.
	for q in ${dev}/queues/tx-*; do
		set_hex_val "$q/xps_cpus" "$((1 << $idx))"
		let "idx = idx + 1"
		[ "$idx" -ge "$NPROCS" ] && idx=0
	done

