#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95

UPG_NONE=0
UPG_REQ=1
UPG_INPROG=2
UPG_SUCC=3
UPG_FAIL=4
UPG_COMMIT_REQ=5
UPG_COMMIT_SUCC=6
UPG_COMMIT_FAIL=7
STATE_PATH="/opt/intel/etc/upgrade/.upg_state_file"

boot() {

	ubus call system done
	local udv

	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	state="$(cat $STATE_PATH)"

	if [ "$state" -eq "$UPG_REQ" -o "$state" -eq "$UPG_INPROG" ] ; then
		udt_status=`/usr/sbin/uboot_env --get --name udt_status`
		if [ $udt_status -eq $UPG_INPROG ];then
			echo $UPG_COMMIT_REQ > $STATE_PATH
			/usr/sbin/uboot_env --set --name udt_status --value $UPG_COMMIT_REQ
			logger -t "Commiting image..."
			ubus call system reboot
		elif [ $udt_status -eq $UPG_FAIL ] ; then
			echo $UPG_FAIL > $STATE_PATH
			logger -t "upgrade failure recovered working image"
		fi
	elif [ "$state" -eq "$UPG_COMMIT_REQ" ] ; then
		udt_status=`/usr/sbin/uboot_env --get --name udt_status`
		if [ $udt_status -eq $UPG_COMMIT_SUCC ] ; then
			#Basic sanity check
			ubus list | grep csd > /dev/null
			if [ $? -ne 0 ] ; then 
				echo $UPG_FAIL > $STATE_PATH
				logger -t "upgrade done" "Basic sanity failed , system going for reboot"
				reboot 	
			else
				echo $UPG_SUCC > $STATE_PATH
			fi 

			loop=0
			while [ $loop -lt 3 ]
			do
				ubus list | grep servd > /dev/null
				if [ $? -ne 0 ] ; then
					sleep 2
				else
					echo $UPG_SUCC > $STATE_PATH
					break
				fi
				loop=`expr $loop + 1`
			done
			state="$(cat $STATE_PATH)"
			if [ "$state" -eq "$UPG_SUCC" ] ; then
				/usr/sbin/uboot_env --set --name udt_status --value $UPG_SUCC
				logger -t "Upgrade successful"
			else
				echo $UPG_SUCC > $STATE_PATH
				logger -t "upgrade done" "Basic sanity failed , system going for reboot"
				#reboot
			fi
		elif [ $udt_status -eq $UGP_FAIL ] ; then
			echo $UPG_FAIL > $STATE_PATH
			logger -t "upgrade failure"
		fi
	fi

	# set leds to normal state
	. /etc/diag.sh
	set_state done
}
