#!/bin/sh /etc/rc.common

# Copyright (C) 2022 MaxLinear, Inc.

USE_PROCD=1
START=75

start_service() {
	rm  /tmp/pon_uci_cfg 2> /dev/null
	procd_open_instance
	procd_set_param command /lib/pon/pondb.sh
	procd_set_param user servd
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
