#!/bin/sh /etc/rc.common
START=80
USE_PROCD=1

start_service() {
	local aon_mode
	local aon_pol
	local gpon_mode=1

	config_load optic
	config_get aon_mode "common" "aon_mode" "0"
	config_get aon_pol "common" "aon_pol" "0"

	if [ $aon_mode -eq 1 ]; then
		procd_open_instance
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param command /usr/bin/pond -r "${gpon_mode}" -a "${aon_pol}" -m "aon"
		procd_close_instance
	fi
}

service_triggers()
{
	procd_add_reload_trigger "optic"
}
