#!/bin/sh /etc/rc.common

START=70
USE_PROCD=1

container_base_path="/srv/lxc"
uid_start="20000"
uid_range_max="1000"
gid_start="20000"
gid_range_max="1000"
script_name="$(basename ${basescript:-$initscript})"

validate_container_section()
{
	local default_arch="$(uname -m)"
	container_count="${container_count:-1}"

	uci_load_validate lxc-auto container "$1" "$2" \
		'container_name:string:'container$container_count \
		'container_command:or("up", "down"):down' \
		'container_path:string:'$container_base_path \
		'arch:string:'$default_arch \
		'rootfs_targz_url:string' \
		'container_privilege:or("privileged", "unprivileged"):unprivileged' \
		'lxcuser:string:lxcuser' \
		'lxcuser_home:string' \
		'uid_rootmap:uinteger:'$uid_start \
		'uid_range:uinteger:'$uid_range_max \
		'gid_rootmap:uinteger:'$gid_start \
		'gid_range:uinteger:'$gid_range_max \
		'kill_timeout:uinteger:0' \
		'utsname:string' \
		'network_ipv4_gw:ip4addr:192.168.1.1' \
		'network_ipv6_gw:ip6addr' \
		'interfaces:string' \
		'mount_auto:string' \
		'include_path:file' \
		'cap_bounding:string' \
		'cap_permitted:string'
		'cap_effective:string'
		'cap_ambient:string'
		'cap_inheritable:string'

	container_count=$((container_count+1))
}

validate_network_section()
{
	uci_load_validate lxc-auto network "$1" "$3" \
		'type:or("none", "empty", "veth", "vlan", "macvlan")' \
		'flags:or("up", "down"):up' \
		'link:string:br-lan' \
		'hwaddr:macaddr' \
		'name:string:veth_0' \
		'mtu:uinteger:1500' \
		'ipv4:ip4addr' \
		'ipv6:ip6addr' \
		'vlan_id:uinteger' \
		'macvlan_mode:string'

}

write_lxcconf_start()
{
	rm -f "$container_config"
	> "$container_config"
}

write_lxcconf_data()
{
	if [ -n "$1" -a -n "$2" ]; then
		echo "$2 = $1" >> "$container_config"
	elif [ -n "$1" ]; then
		if [ "${1#lxc.*=}" != "$1" ]; then
			echo "$1" >> "$container_config"
		fi
	fi
}

write_lxcconf_head()
{
	echo -en "\n#--------$@--------#\n" >> "$container_config"
}

add_network()
{
	[ "$2" = 0 ] || {
		echo "Error: Validation failed"
		return 1
	}

	local _idx="$((c-1))"

	write_lxcconf_data "$type" lxc.net.${_idx}.type
	write_lxcconf_data "$flags" lxc.net.${_idx}.flags
	if [ "$type" != "none" -a "$type" != "empty" ]; then
		write_lxcconf_data "$link" lxc.net.${_idx}.link
		write_lxcconf_data "$name" lxc.net.${_idx}.name
	fi
	if [ "$type" = "vlan" ]; then
		if [ -z "$vlan_id" ]; then
			echo "Error: Provide vlan ID for interface '$1'"
			return 1
		fi
		write_lxcconf_data "$vlan_id" lxc.net.${_idx}.vlan.id
	elif [  "$type" = "macvlan" ]; then
		if [ -z "$macvlan_mode" ]; then
			echo "Error: Provide macvlan mode for interface: '$1'"
			return 1
		fi
		write_lxcconf_data "$macvlan_mode" lxc.net.${_idx}.macvlan.mode
	fi

	write_lxcconf_data "$hwaddr" lxc.net.${_idx}.hwaddr
	write_lxcconf_data "$mtu" lxc.net.${_idx}.mtu
	write_lxcconf_data "$ipv4" lxc.net.${_idx}.ipv4.address
}

add_container()
{
	[ "$2" = 0 ] || {
		echo "Error: Validation failed"
		return 1
	}

	lxcuser_home=${lxcuser_home:-/home/$lxcuser};
	utsname=${utsname:-$container_name};

	if ! [ -d "${container_path}/" ]; then
		echo "Error: container base path '$container_path' not available or not mounted"
	fi

	local rootfs_path="$container_path/$container_name/rootfs"

	if [ "$container_privilege" = "unprivileged" ]; then
		if [ "$uid_range" -gt "$uid_range_max" ]; then
			echo "Error: Specify uid_range within or upto '$uid_range_max'"
			return 1
		fi
		if [ "$gid_range" -gt "$gid_range_max" ]; then
			echo "Error: Specify gid_range within or upto '$gid_range_max'"
			return 1
		fi
		if [ "$uid_rootmap" -lt "$uid_start" ]; then
			echo "Error: Specify uid_rootmap starting from '$uid_start'"
			return 1
		fi
		if [ "$gid_rootmap" -lt "$gid_start" ]; then
			echo "Error: Specify gid_rootmap starting from '$gid_start'"
			return 1
		fi
	fi

	if [ -n "$cap_bounding" -a -n "$cap_permitted" -a -n "$cap_effective" \
			-a -n "$cap_ambient" -a -n "$cap_inheritable" ]; then
		echo "Error: Cannot specify 'cap_bounding', 'cap_permitted', \
			'cap_effective', 'cap_ambient' and 'cap_inheritable' for '$container_name'"
		return 1
	fi

	local container_config_path="/tmp/lxc/$container_name"
	local container_config="$container_config_path/config"

	[ "$container_command" = "down" ] && return 0

	mkdir -p "$container_config_path"

	write_lxcconf_start

	write_lxcconf_head "Container configuration file"
	config_list_foreach "$1" include_path write_lxcconf_data "lxc.include"

	write_lxcconf_data "$arch" lxc.arch

	write_lxcconf_head "Container Specific Configurations"
	write_lxcconf_data "$rootfs_path" lxc.rootfs.path
	write_lxcconf_data "$utsname" lxc.uts.name

	write_lxcconf_head "Network Configurations"
	config_list_foreach "$1" interfaces validate_network_section network add_network

	write_lxcconf_head "CGroups Configurations"
	config_list_foreach "$1" cgroups write_lxcconf_data "lxc.cgroup"

	write_lxcconf_head "Mount Configurations"
	config_list_foreach "$1" mount_auto write_lxcconf_data "lxc.mount.auto"
	config_list_foreach "$1" mount_entry write_lxcconf_data "lxc.mount.entry"

	write_lxcconf_head "Capabilities Configurations"
	write_lxcconf_data "$cap_bounding" lxc.bounding
	write_lxcconf_data "$cap_permitted" lxc.permitted
	write_lxcconf_data "$cap_effective" lxc.effective
	write_lxcconf_data "$cap_ambient" lxc.ambient
	write_lxcconf_data "$cap_inheritable" lxc.inheritable

	write_lxcconf_head "Custom Configurations"
	config_list_foreach "$1" custom_config write_lxcconf_data

	if [ "$container_privilege" = "unprivileged" ]; then
		write_lxcconf_data "u 0 $uid_rootmap $uid_range" lxc.idmap
		write_lxcconf_data "g 0 $gid_rootmap $gid_range" lxc.idmap
	else
		lxcuser=""
	fi

	procd_open_instance lxcprep-${container_name}
	procd_set_param command /usr/sbin/lxc-prepare
	procd_append_param command "$rootfs_path" "$container_name" "$rootfs_targz_url"
	procd_append_param command "$container_privilege" "$lxcuser"
	procd_set_param env uid_rootmap=$uid_rootmap gid_rootmap=$gid_rootmap uid_range=$uid_range gid_range=$uid_range
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

add_config_trigger()
{
	config_get container_name $1 container_name
	config_get container_privilege $1 container_privilege
	config_get lxcuser $1 lxcuser
	procd_add_config_trigger "config.change" "lxcrun_$container_name" /etc/init.d/lxc-auto reload start_container $container_name \
		$container_privilege $lxcuser
}

service_triggers()
{
	procd_add_reload_trigger "lxc-auto"
	procd_add_validation validate_container_section
	procd_add_validation validate_network_section
	config_load lxc-auto
	config_foreach add_config_trigger container
}

start_container()
{
	local container_name="$1"
	local container_privilege="$2"
	local container_user="$3"
	local privileged;

	[ -n "$container_name" -a -n "$container_privilege" ] || return 1

	procd_kill "$script_name" "lxcprep-${container_name}"
	
	if [ "$container_privilege" = "unprivileged" ]; then
		[ -n "$container_user" ] || return 1
	fi

	procd_open_service "$script_name" "$initscript"
	procd_open_instance lxcstart-$container_name
	if [ "$container_privilege" = "privileged" ]; then
		procd_set_param command lxc-start
		procd_append_param command -F -n "$container_name" -P "/tmp/lxc/$container_name" -f "/tmp/lxc/$container_name/config"
	else
		procd_set_param command /usr/sbin/lxc-start-user
		procd_append_param command "$container_name" "$container_user"
		procd_append_param command -F -n "$container_name" -P "/tmp/lxc/$container_name" -f "/tmp/lxc/$container_name/config"
		procd_set_param user "$container_user"
		procd_set_param env HOME=/tmp/lxc_homes/$container_name
	fi
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	procd_close_service add
}

start_service() {
	config_load lxc-auto
	config_foreach validate_container_section container add_container
}

stop_container()
{
	config_get container_name $1 container_name
	config_get kill_timeout $1 kill_timeout
	local kill_args="-k"

	if ! [ -n "$2" -a "$2" = "force" ]; then
		if [ -n "$kill_timeout" -a -z "${kill_timeout//[0-9]}" ]; then
			if [ "$kill_timeout" -gt 0 ]; then
				kill_args="-t $kill_timeout"
			fi
		fi
	fi

	([ -n "$2" -a "$2" = "force" ] || procd_running "$script_name" "lxcstart-${container_name}") && {
		procd_open_service "$script_name" "$initscript"
		procd_open_instance lxcstop-$container_name
		procd_set_param command /usr/bin/lxc-stop -n "$container_name" -P "/tmp/lxc/$container_name" $kill_args
		procd_close_instance
		procd_close_service add
		sleep 2
	}
}

stop_service() {
	config_load lxc-auto
	config_foreach stop_container container "$1"
	[ -n "$1" ] && procd_kill lxc-auto
}

reload_service() {
	if [ -n "$1" ]; then
		if [ -n "$2" -a "$1" = "start_container" ]; then
			shift
			start_container $@
		fi
	else
		stop
		sleep 2;
		start
	fi
}

