#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Intel Corporation

START=99

start() {
        switch_cli xgmac 5 reset 1
        switch_cli xgmac 5 init
        switch_cli xgmac 6 reset 1
        switch_cli xgmac 6 init
        switch_cli xgmac 7 reset 1
        switch_cli xgmac 7 init
        switch_cli xgmac 8 reset 1
        switch_cli xgmac 8 init
}
