# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the MaxLinear(R) UMT driver
#
# Copyright (C) 2020-2022 MaxLinear, Inc.
# Copyright (C) 2018-2020 Intel Corporation.

obj-$(CONFIG_MXL_UMT) += umt.o
obj-$(CONFIG_MXL_UMT_TEST) += umt_test.o
