# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Maxlinear network device drivers.
#

obj-$(CONFIG_MXL_ETH) += mxl_eth_drv.o
obj-$(CONFIG_MXL_PON_HGU_VUNI) += mxl_pon_hgu_vuni.o
obj-$(CONFIG_EIP160S_MACSEC) += mxl_eth_macsec.o
