cm_param_do_not_merge=Device.DeviceInfo.VendorConfigFile.1.X_LANTIQ_COM_Path
cm_param_do_not_merge=Device.DeviceInfo.VendorConfigFile.2.X_LANTIQ_COM_Path
cm_param_do_not_merge=Device.Firewall.Chain.X.Name
cm_obj_do_not_merge=Device.DeviceInfo.VendorLogFile.X.

