#!/bin/sh /etc/rc.common

USE_PROCD=1
START=11

start_service() {
        #commands to launch dwpal_daemon
        procd_open_instance
        procd_set_param user root
        procd_set_param capabilities /usr/share/capabilities/dwpal_daemon_cap.json
        procd_set_param command /usr/sbin/dwpal_daemon -i wlan0 -i wlan2 -i wlan4 -s
        procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
