##################################################################################
#                                                                                #
#       Copyright © 2020 MaxLinear, Inc.                                         #
#                                                                                #
#  For licensing information, see the file 'LICENSE' in the root folder of       #
#  this software module.                                                         #
##################################################################################

obj-$(CONFIG_LOOP_ETH_DEV) += ifx_loop_eth_dev.o

