#!/bin/sh
# Copyright (C) 2011 OpenWrt.org
# Copyright (C) 2014 lantiq.com
# Copyright (C) 2020 Intel Corporation
# Copyright (C) 2023 MaxLinear, Inc.

. /lib/functions/uci-defaults.sh
. /lib/pon.sh

# uci has errors if the file does not exist:
touch /etc/config/network
touch /etc/config/omci

ucidef_set_interface_loopback

uci -q delete network.lan
# Remove br-lan
uci -q delete network.@device[0]

uci_set_section() {
	local section=$1
	shift
	local type=$1
	shift
	local name=$1
	shift

	[ -z "$type" -o -z "$name" ] && return

	uci set $section.$name=$type

	while [ -n "$1" ]; do
		local opt=$1
		shift
		local val=$1
		shift

		[ -n "$opt" -a -n "$val" ] || break

		uci set $section.$name.$opt=$val
	done
}

uci_set_device() {
	uci_set_section network device $*
}

uci_set_device_pon() {
	uci_set_section omci device $*
}

uci_set_interface() {
	uci_set_section network interface $*
}

dev_alias() {
	case $1 in
	eth0_0)
		echo "uni1"
		;;
	eth0_1)
		echo "uni2"
		;;
	*)
		echo "$1"
		;;
	esac
}

ext_dev_alias_mxl862xx() {
	case $1 in
	eth0_0_p1 | eth0_1_p1)
		echo "uni1"
		;;
	eth0_0_p2 | eth0_1_p2)
		echo "uni2"
		;;
	eth0_0_p3 | eth0_1_p3)
		echo "uni3"
		;;
	eth0_0_p4 | eth0_1_p4)
		echo "uni4"
		;;
	eth0_0_p13 | eth0_1_p13)
		echo "uni5"
		;;
	eth0_0 | eth0_1)
		echo "uni6"
		;;
	*)
		echo "$1"
		;;
	esac
}

ext_dev_alias_gsw140() {
	case $1 in
	eth0_1_p0)
		echo "uni1"
		;;
	eth0_1_p1)
		echo "uni2"
		;;
	eth0_1_p2)
		echo "uni3"
		;;
	eth0_1_p3)
		echo "uni4"
		;;
	eth0_0)
		echo "uni5"
		;;
	*)
		echo "$1"
		;;
	esac
}

ext_dev_alias() {
	dev=$1; shift

	case $(pon_board_name) in
	*gsw*140*muni)
		ext_dev_alias_gsw140 "$dev"
		;;
	*mxl862xx*)
		ext_dev_alias_mxl862xx "$dev"
		;;
	esac
}

add_ip_host() {
	for index in $(seq 1 2); do
		# for IP host (IPv4)
		uci_set_interface iphost"$index" ifname "iphost$index" \
			proto 'static' auto '0' \
			ipaddr '0.0.0.0' netmask '0.0.0.0' \
			macaddr "$(pon_mac_get iphost "$index")"

		# for IPv6 host, sharing netdev with IP host
		uci_set_interface ip6host"$index" ifname "ip6host$index" \
			proto 'static' auto '0'

		uci_set_device iphost"$index"_bp name "iphost${index}_bp"
	done
}

case $(pon_board_name) in
# This is configured for Multi UNI PON
*gsw*140*muni | *mxl862xx*)
	# Prepare Network Configuration
	devs="eth0_0 eth0_1"
	case $(pon_board_name) in
	*gsw*140*muni)
		ext_devs="eth0_1_p0 eth0_1_p1 eth0_1_p2 eth0_1_p3"
		;;
	*mxl862xx*)
		ext_devs="eth0_0_p1 eth0_0_p2 eth0_0_p3 eth0_0_p4 eth0_0_p13"
		;;
	esac
	for dev in $devs; do
		uci_set_device "$dev" name "$dev" macaddr "$(pon_mac_get "$dev")"
	done
	for dev in $ext_devs; do
		uci_set_device "$dev" name "$dev"
	done

	# Prepare OMCI Configuration
	case $(pon_board_name) in
	*gsw*140*muni)
		ext_switch="eth0_1"
		devs="eth0_0"
		;;
	*mxl862xx*)
		ext_switch="eth0_0"
		devs="eth0_1"
		;;
	esac
	uci_set_device_pon "ext_switch" name "$ext_switch"

	ext_id=10
	for dev in $ext_devs; do
		uci_set_device_pon "$(ext_dev_alias "$dev")" name "$dev" ext_master "$ext_switch" id $ext_id multicast_name "${dev}_mc" broadcast_name "${dev}_bc"
		ext_id=$((ext_id + 10))
	done
	for dev in $devs; do
		uci_set_device_pon "$(ext_dev_alias $dev)" name "$dev" macaddr "$(pon_mac_get $dev)" multicast_name "${dev}_2" broadcast_name "${dev}_3"
	done

	add_ip_host

	uci set default.lct_port="5"
	;;

# This is configured for Ethernet WAN (or a HGU board)
*eth | *hgu*)
	case $(pon_board_name) in
	*eth)
		devs="eth0_0 eth0_1 eth1"
		;;
	*hgu*)
		devs="eth0_0 eth0_1 VANI0"
		add_ip_host
		;;
	esac

	for dev in $devs; do
		uci_set_device $dev name "$dev" macaddr "$(pon_mac_get $dev)"
	done
	uci_set_interface bridge type 'bridge' proto 'static' \
		ipaddr '0.0.0.0' netmask '0.0.0.0' auto '1' \
		macaddr $(pon_mac_get wan)
	uci set network.bridge.ifname="$devs"
	;;

# This is configured for PON WAN
*)
	case $(pon_board_name) in
	*w5500*)
		uci_set_interface mgmt ifname eth0 proto 'static'
		;;
	esac

	devs="eth0_0 eth0_1"
	for dev in $devs; do
		uci_set_device_pon "$(dev_alias $dev)" name "$dev" macaddr "$(pon_mac_get $dev)"
	done

	default_lct=$(pon_default_lct_get)

	uci_set_interface lct ifname $default_lct \
		ipaddr '192.168.1.1' netmask '255.255.255.0' \
		proto 'static' auto '0' \
		macaddr $(pon_mac_get $default_lct)
	add_ip_host
	;;
esac
