#!/bin/sh

uci batch << EOF
add_list firewall.@zone[0].network='lct'
EOF

if [ -f /etc/init.d/dropbear ]; then
	uci batch << EOF
	add firewall rule
	set firewall.@rule[-1].name='Allow-SSH'
	set firewall.@rule[-1].src='lan'
	set firewall.@rule[-1].proto='tcpudp'
	set firewall.@rule[-1].dest_port='22'
	set firewall.@rule[-1].target='ACCEPT'
EOF
fi

if [ -f /usr/sbin/ptp4l ]; then
	uci batch << EOF
	add firewall rule
	set firewall.@rule[-1].name='Allow-PTP'
	set firewall.@rule[-1].src='lan'
	set firewall.@rule[-1].proto='udp'
	set firewall.@rule[-1].dest_port='319:320'
	set firewall.@rule[-1].target='ACCEPT'
EOF
fi

uci batch << EOF
add firewall rule
set firewall.@rule[-1].name='Default-Block-WAN'
set firewall.@rule[-1].src='wan'
set firewall.@rule[-1].proto='tcpudp'
set firewall.@rule[-1].target='REJECT'
add firewall rule
set firewall.@rule[-1].name='Default-Block-LAN'
set firewall.@rule[-1].src='lan'
set firewall.@rule[-1].proto='tcpudp'
set firewall.@rule[-1].target='REJECT'
EOF
