#!/bin/sh
#
# Copyright (C) 2010 OpenWrt.org
# Copyright (C) 2020 Intel Corporation
# Copyright (C) 2022 MaxLinear
#

. /lib/pon.sh

board=$(pon_board_name)

# these are alternate images for SFU Ref boards, so keep the prompt
case $board in
prx321-hgu-qspi-pon | prx321-sfu-qspi-w5500-pon)
	board=prx321-sfu-qspi-pon
	;;
prx321-sfu-v1-10-w5500-pon)
	board=prx321-sfu-v1-10-pon
	;;
esac

set_hostname() {
	uci set system.@system[0].hostname=${board}
}

if [ -n "${board}" ]; then
	set_hostname
fi
