#!/bin/sh

add_dyn_mask()
{
	# $1 dir, $2 file, $3 own, $4 mask
	local path

	mkdir -p "$1"
	if [ -n "$2" ]; then
		path="$1/$2"
		touch "$path"
	else
		path="$1"
	fi

	chown $3 "$path"
	chmod $4 "$path"
}

add_dir_ownership()
{
	if [ -f "/rom/etc/dynamic_mask.conf" ]; then
		. /rom/etc/dynamic_mask.conf
	fi
}

boot_hook_add preinit_main add_dir_ownership
