#!/bin/sh

if [ "$ACTION" = "add" -a "$DEVTYPE" = "disk" ]; then
	# UGW_SW-77845: Kernel 5.x uses optimal_io_size to update
	# read_ahead_kb - which is causing less throughput for READ.

	# This value is used in 4.x Kernel, same fixes READ in 5.x Kernel
	echo 128 > /sys/$DEVPATH/queue/read_ahead_kb

	# Select BFQ IO scheduler as CFQ scheduler removed from 5.x Kernel
	echo bfq > /sys/$DEVPATH/queue/scheduler
	bfq_status=$?

	if [ $bfq_status -eq 0 ]; then
		# Tune BFQ scheduler parameters to get best throughput like CFQ
		echo 1 > /sys/$DEVPATH/queue/iosched/low_latency # Def: 0
		echo 1 > /sys/$DEVPATH/queue/iosched/strict_guarantees # Def: 0
		echo 8 > /sys/$DEVPATH/queue/iosched/timeout_sync # Def: 124
		echo 8192 > /sys/$DEVPATH/queue/iosched/max_budget # Def: 0
		sleep 1
		echo 1 > /sys/$DEVPATH/queue/iosched/slice_idle # Def: 8
	fi
fi

