#!/bin/sh /etc/rc.common

USE_PROCD=1
START=36
STOP=93

start_service() {

	config_load devm
	config_get status cwmp disabled
	if [ -n $status ] && [ $status -eq 0 ]
	then
		procd_open_instance
		procd_set_param command /opt/intel/usr/sbin/devmd
		procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
		procd_set_param user devmd
		procd_set_param capabilities /usr/share/capabilities/devmd_cap.json 
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_add_jail devmd ubus sysfs procfs log stunnel
		procd_add_jail_mount /bin/cp /bin/tar /bin/mv /bin/ubus /usr/bin/curl /usr/bin/taskset /bin/dd /opt/intel/usr/sbin/mgmt.sh /etc/passwd /etc/group /etc/shadow /usr/bin/stunnel /opt/intel/etc/upgrade /usr/bin/openssl /usr/sbin/uboot_env /usr/sbin/nanddump /var/log/messages
		procd_add_jail_mount_rw /tmp/devmd/ /tmp/csd /tmp/upgrade /tmp/upgrade_uci /opt/intel/etc/devmd /tmp/backup_restore 
		procd_close_instance
	fi
}

service_triggers()
{
        procd_add_reload_trigger "devm"
}

reload_service()
{
        stop
        start
}
