#!/bin/sh /etc/rc.common

USE_PROCD=1
START=22
start_service() {
	procd_open_instance
	procd_set_param command urlfilterd
	procd_set_param env PATH=${PATH}:/opt/intel/sbin:/opt/intel/usr/sbin:/opt/intel/bin LD_LIBRARY_PATH=/opt/intel/lib:/opt/intel/usr/lib:${LD_LIBRARY_PATH}
	procd_set_param user firewall
	procd_set_param capabilities /usr/share/capabilities/urlfilterd_cap.json
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger firewall	
}

reload_service() {
	restart
}
