#!/bin/sh /etc/rc.common

USE_PROCD=1
START=11
STOP=99

WDT_FREQUENCY=60
WDT_TIMEOUT=5

no_watchdog_mode()
{
	local _cmdline="$(cat /proc/cmdline)"
	[ -n "$_cmdline" -a -z "${_cmdline//*no_watchdog=1*}" ]
}

start_service() {
	no_watchdog_mode && return

	local cpu i=0

	for cpu in $(sed -n '/^processor.*:/{;s/processor.*: //g;p}' /proc/cpuinfo); do
		procd_open_instance
		procd_set_param command /bin/nice -n -20
		procd_append_param command taskset $(printf "0x%.8X" $((1<<$cpu)))
		procd_append_param command watchdog -T $WDT_FREQUENCY -t $WDT_TIMEOUT /dev/watchdog$i -F
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
		i=$((i+1))
	done
}
