#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=/usr/sbin/xl2tpd
RUN_D="/var/run/xl2tpd"
PID_F="/var/run/xl2tpd.pid"

start_service() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"
	chown :ppp "$RUN_D"
	chmod 770 "$RUN_D"

	chown nwk /etc/xl2tpd/xl2tpd.conf
	chmod 660 /etc/xl2tpd/xl2tpd.conf

	procd_open_instance
	procd_set_param command $BIN -D -l -p "$PID_F"
	procd_set_param user nwk
	procd_set_param capabilities /usr/share/capabilities/xl2tpd_cap.json
	procd_set_param respawn
	procd_close_instance

}

stop_service() {
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}
