/*****************************************************************************
 * Copyright (c) 2020 - 2022 MaxLinear, Inc.
 * Copyright (c) 2019 Intel Corporation
 *
 * For licensing information, see the file 'LICENSE' in the root folder of
 * this software module.
 *****************************************************************************/

/**
 * \file
 * This file holds the rule definitions for OMCI-controlled VLAN tag
 * manipulations.
 */

/** \addtogroup PON_NET_LIB
 *
 *  @{
 */

/** \defgroup PON_NET_EXT_VLAN_RULES PON Netlink Extended VLAN Rule Definitions
 *  These are the definitions for OMCI Extended VLAN rules.
 *
 *  @{
 */

/** The VLAN priority values are valid within a range of 0 to 7.
 *  There are 8 possible priority values.
 */
#define PRIO_COUNT 8
/** This is a special priority code point that means:
 *  Match all priority values.
 */
#define PRIO_ANY 8
/** This is a special priority code point that means:
 * Copy the priority from the inner tag of the received frame.
 */
#define PRIO_COPY_INNER 8
/** This is a special priority code point that means:
 * Copy the priority from the outer tag of the received frame.
 */
#define PRIO_COPY_OUTER 9
/** This is a special priority code point that means:
 * Add an outer tag, and derive P bits from the DSCP field of the
 * incoming frame according to the DSCP to P-bit mapping attribute.
 */
#define PRIO_DSCP 10
/* Matches against anything */
#define NA -1
/* Match against any filter VLAN (0 - 4094) */
#define VIDc -2
/* Match against any filter VLAN (0 - 4094) */
#define VIDs -3
/** Match against any treatment VLAN (0 - 4094), or filter VLAN in
 * reversed rule
 */
#define VIDx -4
/* Match against any VLAN (0 - 4094), or filter VLAN in reversed rule */
#define VIDy -5
/* Match against any filter priority (0 - 7) */
#define Pc -6
/** Match against any treatment priority (0 - 7), or filter priority in
 * reversed rule
 */
#define Px -7
/** Match against any treatment priority (0 - 7), or filter priority in
 * reversed rule
 */
#define Py -8
/* Match against any priority (0 - 7) or 8 */
#define PxOr8 -10
/* Match against any priority (0 - 7) or 8 */
#define PyOr8 -11
/* Match against default inner VID */
#define default_inner_VID -12
/* Match against default outer VID */
#define default_outer_VID -13
/* Match against any filter priority (0 - 7)*/
#define Ps -15
/* Match against 0, 2, 4, 6, 7 TPID values */
#define m_0_2_4_6_7 -40
/* Match against 0-7 TPID values */
#define m_0_7 -41
/* Match against 0-4 TPID values */
#define m_0_4 -42
/* Match against 0, 2, 5, 6, 7 TPID values */
#define m_0_4_5_6_7 -43
/* Match against 1-4 TPID values */
#define m_1_4 -44
/* Match against 4, 6, 7 TPID values */
#define m_4_6_7 -45

/** Filter on the outer VLAN priority (PCP) */
#define fop -1001
/** Filter on the outer VLAN ID (VID) */
#define fov -1002
/** Filter on the outer TPID */
#define fot -1003
/** Filter on the inner VLAN priority (PCP) */
#define fip -1004
/** Filter on the inner VLAN ID (VID) */
#define fiv -1005
/** Filter on the inner TPID */
#define fit -1006
/** Treatment of the outer VLAN priority */
#define top -1007
/** Treatment of the outer VLAN ID (VID) */
#define tov -1008
/** Treatment of the outer TPID */
#define tot -1009
/** Treatment of the inner VLAN priority (PCP) */
#define tip -1010
/** Treatment of the inner VLAN ID (VID) */
#define tiv -1011
/** Treatment of the inner TPID */
#define tit -1012
/** Filter on the Ethertype */
#define fe -1013
/** Treatment to remove */
#define tr -1014

/** OMCI Extended VLAN rule */
struct omci_rule {
	/** Rule index - major */
	uint16_t major;
	/** Rule index - minor */
	uint16_t minor;
	/** Default rule indication */
	uint8_t def;
	/** Rule description */
	const char *description;
	/** VLAN filter */
	struct pon_adapter_ext_vlan_filter f;
};

/** OMCI Extended VLAN rule set */
struct omci_rules {
	/** Upstream rule */
	struct omci_rule up;
	/** Downstream rule */
	struct omci_rule down;
};

/** VLAN filter rule template */
struct filter_template {
	/** Next rule */
	struct filter_template *next;
	/** Enable outer VLAN filtering */
	int outer_vlan_enable;
	/** Outer VLAN ID for filtering */
	int outer_vlan_id;
	/** Outer VLAN priority (PCP) for filtering */
	int outer_vlan_prio;
	/** Outer VLAN protocol (TPID) for filtering) */
	int outer_vlan_proto;
	/** Enable inner VLAN for filtering */
	int inner_vlan_enable;
	/** Inner VLAN ID for filtering */
	int inner_vlan_id;
	/** Inner VLAN priority (PCP) for filtering */
	int inner_vlan_prio;
	/** Inner VLAN protocol (TPID) for filtering */
	int inner_vlan_proto;
	/** Protocol (Ethertype) for filtering */
	int proto;
	/** Action to perform on matched packets,
	 *  see enum netlink_filter_act
	 */
	int act;
	/** Operation on VLAN to take if act is netlink_filter_act,
	 *  see enum netlink_filter_act_vlan
	 */
	int act_vlan;
	/** VLAN ID action */
	int act_vlan_id;
	/** VLAN Priority action */
	int act_vlan_prio;
	/** VLAN Protocol action */
	int act_vlan_proto;
	int act_svlan_id;
	/** VLAN Priority action */
	int act_svlan_prio;
	/** VLAN Protocol action */
	int act_svlan_proto;
	/** IPv4 type of service */
	int ip_tos;
	/** Unused */
	int unused;
	/** Custom ops */
	int custom_ops;
};

/** VLAN rule number */
struct rule_number {
	/** VLAN rule major part
	 * - 0: Untagged rules
	 * - 1: Single-tagged rules
	 * - 2: Double-tagged rules
	 */
	int major;
	/** VLAN rule minor part */
	int minor;
};

static const struct omci_rules omci_rules[] = {
	/* Action Type */
	/* Untagged ingress frames */
	{{0, 1, 1,
	"Do nothing (default flow)",
		{15, 4096, 0, 15, 4096, 0, 0, 0, 15, NA, NA, 15, NA, NA},
	},
	{0, 1, 1,
	"If untagged, do nothing",
		{15, 4096, 0, 15, 4096, 0, 0, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 2, 0,
	"Do nothing (non-default flow)",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 0, 15, NA, NA, 15, NA, NA},
	},
	{0, 2, 0,
	"If untagged, do nothing",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 3, 1,
	"Drop all (default flow)",
		{15, 4096, 0, 15, 4096, 0, 0, 3, 15, 4096, 0, 15, 4096, 0},
	},
	{0, 3, 1,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{0, 4, 0,
	"Drop all (non-default flow)",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 3, 15, 4096, 0, 15, 4096, 0},
	},
	{0, 4, 0,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{0, 5, 1,
	"Insert one full tag X with fixed prio (default flow)",
		{15, 4096, 0, 15, 4096, 0, 0, 0, 15, NA, NA, m_0_7, VIDx,
		m_4_6_7},
	},
	{0, 5, 1,
	"If single-tagged with X, remove outer tag X",
		{15, 4096, 0, 8, VIDx, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 6, 1,
	"Insert one full tag X with prio from DSCP (default flow)",
		{15, 4096, 0, 15, 4096, 0, 0, 0, 15, NA, NA, 10, VIDx,
		m_4_6_7},
	},
	{0, 6, 1,
	"If single-tagged with X and any priority, remove outer tag X",
		{15, 4096, 0, 8, VIDx, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 7, 0,
	"Insert one full tag X with prio from DSCP for filtered Ethertype (non-default flow)",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 0, 15, NA, NA, 10, VIDx,
		m_4_6_7},
	},
	{0, 7, 0,
	"If single-tagged with X and any priority, remove outer tag X",
		{15, 4096, 0, 8, VIDx, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 8, 0,
	"Insert one full tag X with fixed prio for given Ethertype",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 0, 15, NA, NA, m_0_7, VIDx,
		m_4_6_7},
	},
	{0, 8, 0,
	"If single-tagged with X, remove outer tag X",
		{15, 4096, 0, 8, VIDx, 0, m_1_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 9, 1,
	"Insert two full tags (outer=Y, inner=X) (default flow)",
		{15, 4096, 0, 15, 4096, 0, 0, 0, m_0_7, VIDy, m_4_6_7, m_0_7,
		VIDx, m_4_6_7},
	},
	{0, 9, 1,
	"If double-tagged with Y-X, remove two outer tags (outer=Y, inner=X)",
		{8, VIDy, 0, 8, VIDx, 0, 0, 2, 15, NA, 0, 15, NA, 0},
	} },
	{{0, 10, 0,
	"Insert two full tags (outer=Y, inner=X)",
		{15, 4096, 0, 15, 4096, 0, m_1_4, 0, m_0_7, VIDy, m_4_6_7,
		m_0_7, VIDx, m_4_6_7},
	},
	{0, 10, 0,
	"If double-tagged with Y-X, remove two outer tags (outer=Y, inner=X)",
		{8, VIDy, 0, 8, VIDx, 0, m_1_4, 2, 15, NA, 0, 15, NA,
		0},
	} },
	{{1, 1, 1,
	"Do nothing (default flow)",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA, NA, 15, NA,
		NA},
	},
	{1, 1, 1,
	"If single-tagged, do nothing (default flow)",
		{15, 4096, 0, 14, 4096, 0, 0, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 2, 1,
	"Add an outer VID and copy prio (default flow)",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA, NA, 8,
		VIDx, m_0_7},
	},
	{1, 2, 1,
	"If double-tagged with outer VIDx, remove outer tag",
		{14, VIDx, 0, 14, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 3, 0,
	"Do nothing (non-default flow)",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, m_1_4, 0, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 3, 0,
	"If single-tagged, do nothing (non-default flow)",
		{15, 4096, 0, 14, 4096, 0, m_1_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 4, 1,
	"Drop all (default flow)",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, 0, 3, 15, 4096, 0, 15,
		4096, 0},
	},
	{1, 4, 1,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{1, 5, 1,
	"Drop all with VID filter (default flow)",
		{15, 4096, 0, 14, VIDc, m_0_4_5_6_7, 0, 3, 15, 4096, 0, 15,
		4096, 0},
	},
	{1, 5, 1,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{1, 6, 0,
	"Drop all (non-default flow)",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, m_1_4, 3, 15, 4096, 0,
		15, 4096, 0},
	},
	{1, 6, 0,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{1, 7, 0,
	"Insert one full tag X to all single-tagged, new priority",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 7, 0,
	"If double-tagged with VIDx and given outer priority, remove one tag X from all double-tagged",
		{PxOr8, VIDx, 0, 15, 4096, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 8, 0,
	"Insert one full tag X to all single-tagged, copy priority",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 8,
		VIDx, m_0_2_4_6_7},
	},
	{1, 8, 0,
	"If double-tagged with outer VIDx any outer priority, remove one tag X from all double-tagged",
		{8, VIDx, 0, 15, 4096, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 9, 0,
	"Drop all single-tagged with S-tag",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 3, 15, 4096, 0, 15,
		4096, 0},
	},
	{1, 9, 0,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{1, 10, 0,
	"Drop all single-tagged with S-tag and VIDs",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 3, 15, 4096, 0, 15,
		4096, 0},
	},
	{1, 10, 0,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{1, 11, 0,
	"Insert one full tag X if outer tag is C",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 11, 0,
	"If double-tagged, remove one tag X if inner tag is C",
		{PxOr8, VIDx, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 12, 0,
	"Insert one tag X if outer tag is C, copy prio form C",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 8,
		VIDx, m_0_2_4_6_7},
	},
	{1, 12, 0,
	"If double-tagged, remove one tag X if inner tag is C",
		{8, VIDx, 0, 8, VIDc, 0, m_0_4, 2, 15, NA, 0, 9, VIDc, 0},
	} },
	{{1, 13, 0,
	"Insert one tag X if outer tag is C, derive prio from DSCP",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 10,
		VIDx, m_0_2_4_6_7},
	},
	{1, 13, 0,
	"If double-tagged, remove one tag X if inner tag is C and copy prio from X to C",
		{8, VIDx, 0, 8, VIDc, 0, m_0_4, 2, 15, NA, 0, 9, VIDc, 0},
	} },
	{{1, 14, 0,
	"Modify tag to X if outer tag is C, derive prio from DSCP",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 10,
		VIDx, m_0_2_4_6_7},
	},
	{1, 14, 0,
	"If single-tagged and outer tag is X, change to C and keep prio.",
		{8, 4096, 0, 8, VIDx, 0, m_0_4, 1, 15, NA, 0, 9, VIDc, 0},
	} },
	{{1, 15, 0,
	"Insert two full tags Y-X to all single-tagged",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 0, m_0_7, VIDy,
		m_0_2_4_6_7, m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 15, 0,
	"If triple-tagged, remove two tags, if outer is Y and inner is X",
		{PyOr8, VIDy, 0, PxOr8, VIDx, 0, m_0_4, 2, 15, NA, 0, 15, NA,
		0},
	} },
	{{1, 16, 0,
	"Insert two full tags Y-X to all single-tagged if outer tag is C",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, m_0_7, VIDy,
		m_0_2_4_6_7, m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 16, 0,
	"If triple-tagged, remove two tags, if outer is Y and inner is X",
		{PyOr8, VIDy, 0, PxOr8, VIDx, 0, m_0_4, 2, 15, NA, 0, 15, NA,
		0},
	} },
	{{1, 17, 0,
	"Modify tag if tag is C (new VIDx, new prio Px)",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 17, 0,
	"If single-tagged and tag is X, modify to C and copy prio",
		{15, 4096, 0, PxOr8, VIDx, 0, m_0_4, 1, 15, NA, 0, 8, VIDc, 0},
	} },
	{{1, 18, 0,
	"Modify tag if tag is C (new VIDx, keep prio Pc)",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 8,
		VIDx, m_0_2_4_6_7},
	},
	{1, 18, 0,
	"If single-tagged and tag is X, modify to C and copy prio",
		{15, 4096, 0, 8, VIDx, 0, m_0_4, 1, 15, NA, 0, 8, VIDc, 0},
	} },
	{{1, 19, 0,
	"Do not modify anything if tag is C.",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 19, 0,
	"Do not modify anything if tag is C.",
		{15, 4096, 0, 8, VIDc, 0, m_0_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 20, 0,
	"Modify tag if tag is C with given prio (new VIDx, new prio Px)",
		{15, 4096, 0, Pc, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 20, 0,
	"If single-tagged and tag is X, modify to C and set prio",
		{15, 4096, 0, PxOr8, VIDx, 0, m_0_4, 1, 15, NA, 0, Pc, VIDc,
		0},
	} },
	{{1, 21, 0,
	"Modify tag if tag is C with given prio (new VIDx, copy prio)",
		{15, 4096, 0, Pc, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 8,
		VIDx, m_0_2_4_6_7},
	},
	{1, 21, 0,
	"If single-tagged and tag is X, modify to C and set prio",
		{15, 4096, 0, PxOr8, VIDx, 0, m_0_4, 1, 15, NA, 0, Pc, VIDc,
		0},
	} },
	{{1, 22, 1,
	"Modify tag if tag is C with any prio (new VIDx, new Px, default rule)",
		{15, 4096, 0, 14, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 22, 1,
	"If single-tagged and tag is X with any prio, modify to C and copy prio",
		{15, 4096, 0, PxOr8, VIDx, 0, m_0_4, 1, 15, NA, 0, 8, VIDc, 0},
	} },
	{{1, 23, 1,
	"Modify tag if tag is C with same prio (new VIDx, old Px, default rule)",
		{15, 4096, 0, 14, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 8,
		VIDx, m_0_2_4_6_7},
	},
	{1, 23, 1,
	"If single-tagged and tag is X with any prio, modify to C and copy prio",
		{15, 4096, 0, 8, VIDx, 0, m_0_4, 1, 15, NA, 0, 8, VIDc, 0},
	} },
	{{1, 24, 1,
	"Do not modify tag if tag is C with any priority (old VIDc, old Pc, default rule)",
		{15, 4096, 0, 14, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 8,
		4096, m_0_2_4_6_7},
	},
	{1, 24, 1,
	"If single-tagged and tag is C with any prio, keep VLAN unchanged",
		{15, 4096, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 8, 4096, 0},
	} },
	{{1, 25, 0,
	"Modify tag if tag is C with prio from DSCP (old VIDc, new Pc from DSCP)",
		{15, 4096, 0, 14, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 10,
		4096, m_0_2_4_6_7},
	},
	{1, 25, 0,
	"If single-tagged and tag is C with any prio, keep VLAN unchanged",
		{15, 4096, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 8, 4096, 0},
	} },
	{{1, 26, 0,
	"Modify tag if tag is anything with given prio (new VIDx, new prio Px)",
		{15, 4096, 0, Pc, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 26, 0,
	"If single-tagged and tag is X, modify to 0 and set prio",
		{15, 4096, 0, PxOr8, VIDx, 0, m_0_4, 1, 15, NA, 0, Pc, 0, 0},
	} },
	{{1, 27, 0,
	"Modify TPID if tag is anything with given prio (new VIDx, new prio Px)",
		{15, 4096, 0, Pc, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, 4096, m_0_2_4_6_7},
	},
	{1, 27, 0,
	"Modify TPID if tag is anything with given prio (new VIDx, new prio Px)",
		{15, 4096, 0, PxOr8, 4096, 0, m_0_4, 1, 15, NA, 0, Pc, 4096,
		0},
	} },
	{{1, 28, 0,
	"Modify a the existing tag (C->X) and add another one Y",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, m_0_7, VIDy, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 28, 0,
	"If double-tagged, remove the outer tag Y and change the inner from X to C.",
		{Py, VIDy, 0, Px, VIDx, 0, m_0_4, 2, 15, NA, 0, 0, VIDc, 0},
	} },
	{{1, 29, 0,
	"Modify the existing tag (C->X, copy prio) and add another one Y with fixed",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, m_0_7, VIDy, NA,
		8, VIDx, m_0_2_4_6_7},
	},
	{1, 29, 0,
	"If double-tagged with Y/X, remove the outer tag Y and change the inner from X to C, copy prio from inner.",
		{PyOr8, VIDy, 0, 8, VIDx, 0, m_0_4, 2, 15, NA, 0, 8, VIDc, 0},
	} },
	{{1, 30, 0,
	"Remove the tag, if tag is VIDc",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 30, 0,
	"If untagged, add a single tag C with prio 0",
		{15, 4096, 0, 15, 4096, 0, m_0_4, 0, 15, NA, 0, 0, VIDc, 0},
	} },
	{{1, 31, 0,
	"Remove the tag, if tag is VIDc and prio is Pc",
		{15, 4096, 0, Pc, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 31, 0,
	"If untagged, add a single tag C with prio Pc",
		{15, 4096, 0, 15, 4096, 0, m_0_4, 0, 15, NA, 0, Pc, VIDc, 0},
	} },
	{{1, 32, 0,
	"Remove the tag, whatever it is",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 32, 0,
	"If untagged, add a zero tag (priority-tagged)",
		{15, 4096, 0, 15, 4096, 0, m_0_4, 0, 15, NA, 0, 0, 0, 0},
	} },
	{{1, 33, 0,
	"Replace the tag, whatever it is, depending on Ethertype",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 33, 0,
	"If tagged with VIDx/Px and Ethertype matches, replace with zero tag (priority-tagged)",
		{15, 4096, 0, Px, VIDx, 0, m_0_4, 1, 15, NA, 0, 0, 0, 0},
	} },
	{{1, 34, 0,
	"Insert one full tag X to all single-tagged, copy priority if single tagged and prio is Pc",
		{15, 4096, 0, Pc, 4096, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA,
		m_0_7, VIDx, m_0_2_4_6_7},
	},
	{1, 34, 0,
	"If double-tagged with outer VIDx any outer priority, remove one tag X from all double-tagged",
		{PxOr8, VIDx, 0, 15, 4096, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 35, 0,
	"Do not modify anything if tag is C and prio is Pc.",
		{15, 4096, 0, Pc, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 35, 0,
	"Do not modify anything if tag is C and prio is Pc.",
		{15, 4096, 0, Pc, VIDc, 0, m_0_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 36, 0,
	"Do not modify anything if prio is Pc.",
		{15, 4096, 0, Pc, 4096, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA, 15,
		NA, NA},
	},
	{1, 36, 0,
	"Do not modify anything if prio is Pc.",
		{15, 4096, 0, Pc, 4096, 0, m_0_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 37, 0,
	"Insert one full tag X if outer tag is C and outer prio ix Pc",
		{15, 4096, 0, Pc, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA, NA,
		Px, VIDx, m_0_2_4_6_7},
	},
	{1, 37, 0,
	"If double-tagged, remove one tag X if inner tag is C",
		{PxOr8, VIDx, 0, Pc, VIDc, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 38, 1,
	"Add an outer VID and set prio",
		{15, 4096, 0, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA, NA, Px,
		VIDx, m_0_7},
	},
	{1, 38, 1,
	"If double-tagged with outer VIDx, remove outer tag",
		{14, VIDx, 0, 14, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{1, 39, 0,
	"Change priority to Px if tagged and Insert one full tag, copy prio",
		{15, 4096, 0, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 8, VIDy,
		m_0_2_4_6_7, m_0_7, 4096, m_0_2_4_6_7},
	},
	{1, 39, 0,
	"If double-tagged with outer VIDy any outer priority, remove outer and copy prio to inner",
		{8, VIDy, 0, Px, 4096, 0, m_0_4, 2, 15, NA, 0, 8, 4096, 0},
	} },
	{{1, 40, 0,
	"Change tag to VIDx if tag is C and Insert one full tag, copy prio",
		{15, 4096, 0, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 8, VIDy,
		m_0_2_4_6_7, 8, VIDx, m_0_2_4_6_7},
	},
	{1, 40, 0,
	"If double-tagged with outer VIDy any outer priority, remove outer and copy prio to inner",
		{8, VIDy, 0, 8, 4096, 0, m_0_4, 2, 15, NA, 0, 8, 4096, 0},
	} },
	{{2, 1, 1,
	"Do nothing (default flow)",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 1, 1,
	"If double-tagged (or more), do nothing (default flow)",
		{14, 4096, 0, 14, 4096, 0, 0, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 2, 0,
	"Add a 3rd tag VIDx, copy prio from outer",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, 9, VIDx, NA},
	},
	{2, 2, 0,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{14, VIDx, 0, 14, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 3, 0,
	"Do nothing (non-default flow)",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, m_1_4, 0, 15,
		NA, NA, 15, NA, NA},
	},
	{2, 3, 0,
	"If double-tagged (or more), do nothing (default flow)",
		{14, 4096, 0, 14, 4096, 0, m_1_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 4, 1,
	"Drop all (default flow)",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, 0, 3, 15, 4096,
		0, 15, 4096, 0},
	},
	{2, 4, 1,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{2, 5, 1,
	"Drop all with VID filter (default flow)",
		{14, VIDs, m_0_4_5_6_7, 14, VIDc, m_0_4_5_6_7, 0, 3, 15, 4096,
		0, 15, 4096, 0},
	},
	{2, 5, 1,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{2, 6, 0,
	"Drop all (non-default flow)",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, m_1_4, 3, 15,
		4096, 0, 15, 4096, 0},
	},
	{2, 6, 0,
	"There is no reverse rule for dropping",
		{NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA},
	} },
	{{2, 7, 0,
	"Add another tag X to tags S (outer) and C (inner) with fixed prio",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA,
		NA, m_0_7, VIDx, m_0_7},
	},
	{2, 7, 0,
	"If triple-tagged with VIDx/Vids/VIDc, remove the tag",
		{PxOr8, VIDx, 0, 8, VIDs, 0, m_0_4, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 8, 0,
	"Add another tag X to tags S (outer) and C (inner), copy prio from outer tag S",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 15, NA,
		NA, 9, VIDx, m_0_7},
	},
	{2, 8, 0,
	"If triple-tagged with VIDx/VIDs/VIDc, copy the prio from old outer to new outer tag, remove the outer tag",
		{8, VIDx, 0, 8, VIDs, 0, m_0_4, 2, 9, VIDs, 0, 15, NA, 0},
	} },
	{{2, 9, 0,
	"Add two tags Y (outer) and  X (inner) to tags S (outer) and C (inner) with fixed prios",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, m_0_7,
		VIDy, m_0_7, m_0_7, VIDx, m_0_7},
	},
	{2, 9, 0,
	"If quad-tagged with Y-X-S-C, remove two tags.",
		{PyOr8, VIDy, 0, PxOr8, VIDx, 0, m_0_4, 2, 15, NA, 0, 15, NA,
		0},
	} },
	{{2, 10, 0,
	"Add two tags Y (outer) and  X (inner) to tags S (outer) and C (inner) with copied prios",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 0, 9,
		VIDy, m_0_7, 8, VIDx, m_0_7},
	},
	{2, 10, 0,
	"If quad-tagged with Y-X-S-C, remove two tags.",
		{8, VIDy, 0, 8, VIDx, 0, m_0_4, 2, 9, NA, 0, 8, NA, 0},
	} },
	{{2, 11, 0,
	"Modify the outer tag to new VIDx and new prio",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, m_0_7, VIDx, m_0_7},
	},
	{2, 11, 0,
	"If double-tagged with X-C, modify the outer tag to S.",
		{PxOr8, VIDx, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
	{{2, 12, 0,
	"Modify the outer tag if outer tag matches",
		{8, VIDs, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, m_0_4, 1, 15,
		NA, NA, 9, VIDx, m_0_7},
	},
	{2, 12, 0,
	"Modify the outer tag if outer tag matches",
		{8, VIDx, 0, 14, 4096, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
	{{2, 13, 0,
	"Modify the outer tag if outer tag and outer pbit matches",
		{Ps, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15,
		NA, NA, Px, VIDx, m_0_7},
	},
	{2, 13, 0,
	"Modify the outer tag if outer tag and prio matches",
		{PxOr8, VIDx, 0, 14, 4096, 0, m_0_4, 1, 15, NA, 0, Ps, VIDs,
		0},
	} },
	{{2, 14, 0,
	"Modify outer VLAN TPID if outer pbit matches",
		{Ps, 4096, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15,
		NA, NA, Px, 4096, m_0_7},
	},
	{2, 14, 0,
	"Modify outer VLAN TPID if outer pbit matches",
		{PxOr8, 4096, 0, 8, 4096, 0, m_0_4, 1, 15, NA, 0, Ps, 4096, 0},
	} },
	{{2, 15, 0,
	"Modify the outer tag to new VID and keep prio for inner tag VIDc and any inner prio",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, 9, VIDx, m_0_7},
	},
	{2, 15, 0,
	"If double-tagged with X-S with any Px and any Ps, modify the outer tag, keep outer prio.",
		{8, VIDx, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
	{{2, 16, 0,
	"Modify the outer tag to new VID and keep prio for any inner tag and inner prio",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, 9, VIDx, m_0_7},
	},
	{2, 16, 0,
	"If double-tagged with X-S with any Px and any Ps, modify the outer tag, keep outer prio.",
		{8, VIDx, 0, 8, VIDc, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
	{{2, 17, 0,
	"Do nothing, if outer VID matches, ignore prio",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 0, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 17, 0,
	"Do nothing, if outer VID matches, ignore prio",
		{8, VIDs, 0, 8, 4096, 0, m_0_4, 0, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 18, 0,
	"Modify the outer VID and prio if outer VID matches",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, m_0_7, VIDx, m_0_7},
	},
	{2, 18, 0,
	"Modify the outer VID if outer tag matches, keep prio",
		{PxOr8, VIDx, 0, 8, 4096, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
	{{2, 19, 0,
	"Modify both tags to new fixed values and new prios",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 2, m_0_7,
		VIDy, m_0_7, m_0_7, VIDx, m_0_7},
	},
	{2, 19, 0,
	"If double-tagged with Y-X, modify both tags to old values S-C, keep priorities.",
		{PyOr8, VIDy, 0, PxOr8, VIDx, 0, m_0_4, 2, 9, VIDs, 0, 8,
		VIDc, 0},
	} },
	{{2, 20, 0,
	"Modify both tags to new fixed values and keep prios",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 2, 9,
		VIDy, m_0_7, 8, VIDx, m_0_7},
	},
	{2, 20, 0,
	"If double-tagged with Y-X, modify both tags to old values S-C and copy prios.",
		{8, VIDy, 0, 8, VIDx, 0, m_0_4, 2, 9, VIDs, 0, 8, VIDc, 0},
	} },
	{{2, 21, 0,
	"Swap both tags",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 2, 8,
		4096, m_0_7, 9, 4097, m_0_7},
	},
	{2, 21, 0,
	"If double-tagged, swap both tags back.",
		{8, VIDs, 0, 8, VIDc, 0, m_0_4, 2, 8, 4096, 0, 9, 4097, 0},
	} },
	{{2, 22, 0,
	"Remove the outer tag, if tags are S and C..",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 22, 0,
	"If single-tagged with C, add a tag S.",
		{15, 4096, 0, 8, VIDc, 0, m_0_4, 0, 15, NA, 0, 0, VIDc, 0},
	} },
	{{2, 23, 0,
	"Remove both tags, if tags are S and C.",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 2, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 23, 0,
	"If untagged, add two tags C and S.",
		{15, 4096, 0, 15, 4096, 0, m_0_4, 0, 0, VIDs, 0, 0, VIDc, 0},
	} },
	{{2, 24, 0,
	"Remove the inner tag, if tags are S and C. Retain the priority of the outer tag.",
		{8, VIDs, m_0_4_5_6_7, 8, VIDc, m_0_4_5_6_7, m_0_4, 2, 15, NA,
		NA, 9, VIDx, m_0_7},
	},
	{2, 24, 0,
	"If single-tagged with S, add an inner tag C. Use the priority of S for both.",
		{15, 4096, 0, 8, VIDs, 0, m_0_4, 1, 9, VIDs, 0, 9, VIDc, 0},
	} },
	{{2, 25, 0,
	"Remove both tags.",
		{8, 4096, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 2, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 25, 0,
	"If untagged, add two tags.",
		{15, 4096, 0, 15, 4096, 0, m_0_4, 0, 0, default_inner_VID, 0,
		0, default_outer_VID, 0},
	} },
	{{2, 26, 0,
	"Remove outer Tag, if outer tag is C",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15, NA,
		NA, 15, NA, NA},
	},
	{2, 26, 0,
	"If untagged, add a single tag C with prio 0",
		{15, 4096, 0, 8, 4096, 0, m_0_4, 0, 15, NA, 0, 0, VIDc, 0},
	} },
	{{2, 27, 0,
	"Remove outer Tag, if outer tag is C",
		{Ps, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15,
		NA, NA, 15, NA, NA},
	},
	{2, 27, 0,
	"If untagged, add a single tag C with prio Ps",
		{15, 4096, 0, 8, 4096, 0, m_0_4, 0, 15, NA, 0, Ps, VIDc, 0},
	} },
	{{2, 28, 0,
	"Add a 3rd tag VIDx, copy prio from outer if double tagged and outer prio is Ps",
		{Ps, 4096, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, m_0_7, VIDx, NA},
	},
	{2, 28, 0,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{PxOr8, VIDx, 0, Ps, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 29, 0,
	"Add a 3rd tag Px/VIDx if double tagged with outer Ps/VIDs",
		{Ps, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, Px, VIDx, NA},
	},
	{2, 29, 0,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{PxOr8, VIDx, 0, Ps, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 30, 0,
	"Add a 3rd tag Px/VIDx if double tagged with outer VIDs",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, Px, VIDx, NA},
	},
	{2, 30, 0,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{PxOr8, VIDx, 0, Ps, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 31, 0,
	"Add a 3rd tag VIDx and copy prio if double tagged with outer VIDs",
		{8, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, 9, VIDx, NA},
	},
	{2, 31, 0,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{PxOr8, VIDx, 0, Ps, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 32, 1,
	"Add a 3rd tag VIDx, set prio",
		{14, 4096, m_0_4_5_6_7, 14, 4096, m_0_4_5_6_7, 0, 0, 15, NA,
		NA, Px, VIDx, NA},
	},
	{2, 32, 1,
	"If double-tagged  (or more) with outer VIDx, strip outer tag (default flow)",
		{14, VIDx, 0, 14, 4096, 0, 0, 1, 15, NA, 0, 15, NA, 0},
	} },
	{{2, 33, 0,
	"Modify the outer tag if outer tag and outer pbit matches, copy prio",
		{Ps, VIDs, m_0_4_5_6_7, 8, 4096, m_0_4_5_6_7, m_0_4, 1, 15,
		NA, NA, 9, VIDx, m_0_7},
	},
	{2, 33, 0,
	"Modify the outer tag if outer tag and prio matches, copy prio",
		{PxOr8, VIDx, 0, 14, 4096, 0, m_0_4, 1, 15, NA, 0, 9, VIDs, 0},
	} },
};

static struct rule {
	const char *description;
	struct rule_number rule_number;
	struct filter_template upstream;
	struct filter_template downstream;
} ext_vlan_rules[] = {
	{
		.rule_number = {0, 1},
		.upstream = {
			.proto = 0,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.proto = 0,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {0, 3},
		.upstream = {
			.proto = 0,
			.act = NETLINK_FILTER_ACT_DROP,
		},
		.downstream = {
			.unused = 1
		}
	},
	{
		.rule_number = {0, 5},
		.upstream = {
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {0, 6},
		.upstream = {
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_DSCP,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {0, 7},
		.upstream = {
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_DSCP,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {0, 8},
		.upstream = {
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 1},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {1, 2},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 4},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_DROP,
		},
		.downstream = {
			.unused = 1
		}
	},
	{
		.rule_number = {1, 7},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = 0,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 8},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = 0,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 11},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = 0,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = 0,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 12},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = 0,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = 0,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 13},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_DSCP,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP_AND_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 14},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_DSCP,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = NETLINK_FILTER_UNUSED,
			.act_vlan_proto = tit,
		}
	},
	{
		.rule_number = {1, 17},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = tip,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = NETLINK_FILTER_UNUSED,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 18},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = NETLINK_FILTER_UNUSED,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = NETLINK_FILTER_UNUSED,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 19},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {1, 20},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = tip,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = fip,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 21},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = fip,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 22},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = tip,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 23},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 24},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_INNER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 26},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = 0,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 28},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY_AND_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
			.act_svlan_id = tov,
			.act_svlan_prio = top,
			.act_svlan_proto = tot,
			.custom_ops = 1,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tov,
			.outer_vlan_prio = top,
			.outer_vlan_proto = tot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = tip,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP_AND_MODIFY,
			.act_vlan_id = fiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 30},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		},
		.downstream = {
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = fiv,
			.act_vlan_prio = 0,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 31},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		},
		.downstream = {
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = fiv,
			.act_vlan_prio = fip,
			.act_vlan_proto = fit,
		}
	},
	{
		.rule_number = {1, 33},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = tiv,
			.inner_vlan_prio = tip,
			.inner_vlan_proto = tit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = 0,
			.act_vlan_prio = 0,
			.act_vlan_proto = 6,
		}
	},
	{
		.rule_number = {1, 34},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 35},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {1, 36},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {1, 37},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = 0,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = 0,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 38},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {1, 39},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fip,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY_AND_PUSH,
			.act_vlan_id = NETLINK_FILTER_UNUSED,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
			.act_svlan_id = tov,
			.act_svlan_prio = PRIO_COPY_INNER,
			.act_svlan_proto = tot,
			.custom_ops = 1,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tov,
			.outer_vlan_prio = top,
			.outer_vlan_proto = tot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP_AND_MODIFY,
			.act_vlan_id = NETLINK_FILTER_UNUSED,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		}
	},
	{
		.rule_number = {1, 40},
		.upstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY_AND_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
			.act_svlan_id = tov,
			.act_svlan_prio = PRIO_COPY_INNER,
			.act_svlan_proto = tot,
			.custom_ops = 1,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tov,
			.outer_vlan_prio = top,
			.outer_vlan_proto = tot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = tit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP_AND_MODIFY,
			.act_vlan_id = NETLINK_FILTER_UNUSED,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		}
	},
	{
		.rule_number = {2, 1},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {2, 2},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 4},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_DROP,
		},
		.downstream = {
			.unused = 1
		}
	},
	{
		.rule_number = {2, 7},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fov,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 8},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fov,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP_AND_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 11},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 12},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 13},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = fop,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = fop,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 15},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = fiv,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 16},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = NETLINK_FILTER_UNUSED,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 17},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_OK,
		}
	},
	{
		.rule_number = {2, 18},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 26},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = fov,
			.act_vlan_prio = 0,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 27},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = fop,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		},
		.downstream = {
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = fov,
			.act_vlan_prio = fop,
			.act_vlan_proto = fot,
		}
	},
	{
		.rule_number = {2, 28},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = fop,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = fop,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 29},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = fop,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 30},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 31},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
	{
		.rule_number = {2, 32},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = NETLINK_FILTER_UNUSED,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_PUSH,
			.act_vlan_id = tiv,
			.act_vlan_prio = tip,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = NETLINK_FILTER_UNUSED,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fot,
			.proto = 0,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_POP,
		}
	},
		{
		.rule_number = {2, 33},
		.upstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = fov,
			.outer_vlan_prio = fop,
			.outer_vlan_proto = fot,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = tiv,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = tit,
		},
		.downstream = {
			.outer_vlan_enable = 1,
			.outer_vlan_id = tiv,
			.outer_vlan_prio = tip,
			.outer_vlan_proto = tit,
			.inner_vlan_enable = 1,
			.inner_vlan_id = NETLINK_FILTER_UNUSED,
			.inner_vlan_prio = NETLINK_FILTER_UNUSED,
			.inner_vlan_proto = fit,
			.proto = fe,
			.act = NETLINK_FILTER_ACT_VLAN,
			.act_vlan = NETLINK_FILTER_ACT_VLAN_MODIFY,
			.act_vlan_id = fov,
			.act_vlan_prio = PRIO_COPY_OUTER,
			.act_vlan_proto = fot,
		}
	},
};
/** @} */ /* PON_NET_EXT_VLAN_RULES */

/** @} */ /* PON_NET_LIB */
