@startuml
title DUT Component Diagram

package "IQlite (C++)" {
  [IQlite]
}

package "LitePoint.dll" {
  [LitePoint]
}

package "dut_gui.exe (C#)" {
  [Form]
  [DUT_t]
}

package "dut_cli_wrapper.dll (C++/CLI)" {
  [dut_wrapper]
}

package "dut_cli (C++)" {
  [dut_cli]
}

package "dut.lib (C++)" {
  [Log]
  [Dut]
  [Country]
  [Nvm]
  [CalibrationFile]
  [Client]
  [Messenger]
  [Protocol]
  [Connection]
package "shared_header (C)" as shared_header {
  [mhi_dut_h]
  [mhi_hdk_h]
  [mhi_umi_h]
  [mhi_umi_propr_h]
}
}

[Form] --> [DUT_t]
[IQlite] --> [Dut]
[LitePoint] <- [IQlite]

[DUT_t] --> [dut_wrapper]

[dut_wrapper] --> [Dut]
[dut_cli] --> [Dut]

[Dut] --> [Nvm]
[Dut] --> [CalibrationFile]
[Dut] --> [Client]
[Client] --> [Messenger]
[Messenger] --> [Connection]
[Messenger] -> [Protocol]
[Connection] ..> Socket
[CalibrationFile] -> [Nvm]
[Nvm] -> [Client]

@enduml
