#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1
BIN=/usr/sbin/pkcsslotd
SHM_DIR=/tmp/shm

start_service() {
	if [ -d $SHM_DIR ];then
		rm -rf $SHM_DIR
	fi
	mkdir -p $SHM_DIR
	cp -f /etc/providers.cnf /var/etc/ssl/providers.cnf
	cp -f /etc/engines.cnf /var/etc/ssl/engines.cnf

	procd_open_instance
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_set_param command $BIN -F
	procd_close_instance
}

stop_service() {
	rm -rf $SHM_DIR
	killall pkcsslotd
}
