##################################################################################
#                                                                                #
#       Copyright © 2020-2021 MaxLinear, Inc.                                    #
#                                                                                #
#  For licensing information, see the file 'LICENSE' in the root folder of       #
#  this software module.                                                         #
##################################################################################

obj-$(CONFIG_PPA)		+= platform/ ppa_api/ mac_violation_mirror/
obj-$(CONFIG_QOS_MGR)		+= qos/
obj-$(CONFIG_DSL_DFE_LOOPBACK)	+= dsl_dfe_loopback/
obj-$(CONFIG_LOOP_ETH_DEV)	+= loop_eth_dev/
obj-$(CONFIG_LTQ_PORT_MIRROR)	+= portmirror/
obj-$(CONFIG_PTM_VECTORING)	+= vectoring/
obj-$(CONFIG_PPA_ATM_BONDING)	+= bonding/
ccflags-y := -Werror
