#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 MaxLinear, Inc.

. $IPKG_INSTROOT/lib/pon.sh

setup_iphost() {
	touch /etc/config/network
	for index in $(seq 1 2); do
		# for IP host (IPv4)
		uci set network.iphost"$index"=interface
		uci set network.iphost"$index".ifname="iphost${index}"
		uci set network.iphost"$index".proto="static"
		uci set network.iphost"$index".auto="0"
		uci set network.iphost"$index".ipaddr="0.0.0.0"
		uci set network.iphost"$index".netmask="0.0.0.0"
		uci set network.iphost"$index".macaddr="$(pon_mac_get iphost "$index")"
		# for IPv6 host, sharing netdev with IP host
		uci set network.ip6host"$index"=interface
		uci set network.ip6host"$index".ifname=iphost"$index"
		uci set network.ip6host"$index".proto="static"
		uci set network.ip6host"$index".auto="0"

		uci set network.iphost"$index"_bp=device
		uci set network.iphost"$index"_bp.name="iphost${index}_bp"
		uci set network.iphost"$index"_bp.proto="static"
	done
}

setup_iphost



