#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021, 2023 MaxLinear, Inc.

. $IPKG_INSTROOT/lib/pon.sh

setup_uni() {
	touch /etc/config/omci
	uci set omci.uni1=device
	uci set omci.uni1.name="VUNI0_0"
	uci set omci.uni1.multicast_name="VUNI0_1"
	uci set omci.uni1.broadcast_name="VUNI0_2"
	uci set omci.uni1.macaddr=$(pon_mac_get wan)
}

setup_uni
