#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021, 2023 MaxLinear, Inc.
# Copyright (C) 2020 Intel Corporation.

. $IPKG_INSTROOT/lib/pon.sh

board_name=$(pon_board_name)

setup_veip() {
	case $board_name in
	lgm*|urx851*)
		touch /etc/config/omci
		uci set omci.veip1=device
		uci set omci.veip1.name="VUNI0_0"
		uci set omci.veip1.multicast_name="VUNI0_1"
		uci set omci.veip1.broadcast_name="VUNI0_2"
		uci set omci.veip1.ani_name="VANI0"
		;;
	esac
}

if [ -n "$board_name" ]; then
	setup_veip
fi

