##################################################################################
#                                                                                #
#       Copyright © 2020 MaxLinear, Inc.                                         #
#                                                                                #
#  For licensing information, see the file 'LICENSE' in the root folder of       #
#  this software module.                                                         #
##################################################################################

obj-$(CONFIG_PPA_MAC_VIOLATION_MIRROR) += mac_violation_mirror.o
