# SPDX-License-Identifier: GPL-2.0
# Makefile for EIP160s MACsec function.
#
obj-$(CONFIG_EIP160S_MACSEC) += eip160s_macsec.o
eip160s_macsec-objs += aes_crypto.o
eip160s_macsec-objs += eip160s_egress.o
eip160s_macsec-objs += eip160s_ingress.o
eip160s_macsec-objs += eip160s_internal.o
#obj-y += eip160s_macsec.o
#eip160s_macsec-objs += aes_crypto.o eip160s_egress.o eip160s_ingress.o eip160s_internal.o
